### ISSUE TITLE
location is not defined

### ISSUE THREAD

**Issue by SamWangCoder** [vuejs/vitepress#1017]
### Describe the bug

When I run `vitepress build docs`, an error comes out
``` shell
PS D:\Ysh\Repos\ysh-ui-proj\proj\ysh-ui> npm run docs:build

> ysh-ui@0.0.1 docs:build
> vitepress build docs

vitepress v1.0.0-alpha.4
⠼ building client + server bundles...
(!) Some chunks are larger than 500 KiB after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/guide/en/#outputmanualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
✓ building client + server bundles...
✖ rendering pages...
build error:
 ReferenceError: location is not defined
    at Module.<anonymous> (D:\Ysh\Repos\ysh-ui-proj\proj\ysh-ui\docs\.vitepress\.temp\app.js:4087:12)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:201:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:183:25)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async renderPage (file:///D:/Ysh/Repos/ysh-ui-proj/proj/ysh-ui/node_modules/vitepress/dist/node/serve-05342c3d.js:39534:25)
    at async build (file:///D:/Ysh/Repos/ysh-ui-proj/proj/ysh-ui/node_modules/vitepress/dist/node/serve-05342c3d.js:39853:9)
```

### Reproduction

I have import a component form `ysh-ui\docs\.vitepress\theme\components`, my component need load `location.hash` when create.
``` ts
let hash: string = location.hash.slice(1);
```

### Expected behavior

Is it the cause of SSR? 

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
    Memory: 3.28 GB / 15.89 GB
  Binaries:
    Node: 16.5.0 - C:\Program Files\nodejs\node.EXE     
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD    
    npm: 7.19.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.62)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vitepress: ^1.0.0-alpha.4 => 1.0.0-alpha.4
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
> Is it the cause of SSR?

Yeah. Put it inside `onMounted` or do something like `let hash = typeof location !== 'undefined' ? location.hash.slice(1) : ''`. You can also wrap your component inside `<client-only>`.

**Comment by SamWangCoder** [comment]
Thanks for your help, I'll try later.
