### ISSUE TITLE
'vitepress build docs' error

### ISSUE THREAD

**Issue by gittig11** [vuejs/vitepress#1025]
### Describe the bug

.md file contains content: 

    ```js
    js
    ```

    ```mjs
    mjs
    ```

    ```cjs
    cjs
    ```

    * `records` {string\[] | Object\[] | Object}

when runs `vitepress build docs`, errors occur:

```
Language does not exist: mjs
Language does not exist: cjs

[vite:vue] Duplicate attribute.

build error:
 Error [SyntaxError]: Duplicate attribute.
    at createCompilerError (my-docs\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:18:19)
    at emitError (my-docs\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:1566:29)        
    at parseAttribute (my-docs\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:1310:9)    
    at parseAttributes (my-docs\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:1286:22)  
    at parseTag (my-docs\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:1175:17)
    at parseElement (my-docs\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:1104:21)     
    at parseChildren (my-docs\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:933:28)     
    at parseElement (my-docs\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:1120:22)     
    at parseChildren (my-docs\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:933:28)     
    at parseElement (my-docs\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:1120:22) {   
  id: 'my-docs/docs/guide/hhh.md',
  plugin: 'vite:vue',
  loc: {
    file: 'my-docs/docs/guide/hhh.md',
    line: 21,
    column: 34
  },
  hook: 'transform',
  code: 'PLUGIN_ERROR',
  watchFiles: [
    'my-docs/node_modules/vitepress/dist/client/app/index.js',
    'my-docs/docs/config/index.md',
    'my-docs/docs/guide/hhh.md',
    'my-docs/docs/guide/index.md',
    'my-docs/docs/index.md',
    'my-docs/node_modules/vitepress/dist/client/app/utils.js',
    'my-docs/node_modules/vitepress/dist/client/app/router.js',
    'my-docs/node_modules/vitepress/dist/client/app/data.js',
    'my-docs/node_modules/vitepress/dist/client/app/composables/head.js',
    'my-docs/node_modules/vitepress/dist/client/app/composables/preFetch.js',
    'my-docs/node_modules/vitepress/dist/client/app/components/Content.js',
    'my-docs/node_modules/vitepress/dist/client/app/components/ClientOnly.js',
    'my-docs/node_modules/vitepress/dist/client/app/components/Debug.vue',
    'my-docs/node_modules/vue/dist/vue.runtime.esm-bundler.js',
    'my-docs/node_modules/vitepress/dist/client/theme-default/index.js',
    'plugin-vue:export-helper'
  ]
}
[!] Error: unfinished hook action(s) on exit:
(vite:load-fallback) load "my-docs/node_modules/vitepress/dist/client/app/utils.js"
(vite:load-fallback) load "my-docs/node_modules/vitepress/dist/client/app/router.js"
(vite:load-fallback) load "my-docs/node_modules/vitepress/dist/client/app/data.js"
(vite:load-fallback) load "my-docs/node_modules/vitepress/dist/client/app/composables/head.js"
(vite:load-fallback) load "my-docs/node_modules/vitepress/dist/client/app/composables/preFetch.js"
(vite:load-fallback) load "my-docs/node_modules/vitepress/dist/client/app/components/Content.js"
(vite:load-fallback) load "my-docs/node_modules/vitepress/dist/client/app/components/ClientOnly.js"
(vite:load-fallback) load "my-docs/node_modules/vitepress/dist/client/app/components/Debug.vue"
(vite:load-fallback) load "my-docs/node_modules/vue/dist/vue.runtime.esm-bundler.js"
(vite:load-fallback) load "my-docs/node_modules/vitepress/dist/client/theme-default/index.js"
(vite:load-fallback) load "my-docs/node_modules/vitepress/dist/client/app/utils.js"
(vite:load-fallback) load "my-docs/node_modules/vitepress/dist/client/app/router.js"
(vite:load-fallback) load "my-docs/node_modules/vitepress/dist/client/app/data.js"
(vite:load-fallback) load "my-docs/node_modules/vitepress/dist/client/app/composables/head.js"
(vite:load-fallback) load "my-docs/node_modules/vitepress/dist/client/app/composables/preFetch.js"
(vite:load-fallback) load "my-docs/node_modules/vitepress/dist/client/app/components/Content.js"
(vite:load-fallback) load "my-docs/node_modules/vitepress/dist/client/app/components/ClientOnly.js"
(vite:load-fallback) load "my-docs/node_modules/vitepress/dist/client/app/components/Debug.vue"
(vite:load-fallback) load "my-docs/node_modules/vitepress/dist/client/theme-default/index.js"

error Command failed with exit code 1.

```

### Reproduction

vitepress build docs

### Expected behavior

vitepress renders .md files normally.

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 1.09 GB / 7.83 GB
  Binaries:
    Node: 16.13.2 - D:\nodejs\node.EXE
    Yarn: 1.22.19 - D:\nodejs\yarn.CMD
    npm: 8.1.2 - D:\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.62)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vitepress: ^0.21.6 => 0.21.6
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Only these languages are supported: https://github.com/shikijs/shiki/blob/main/docs/languages.md#all-languages

So change your specified `mjs`/`cjs` language to js (syntax highlighting won't break). Secondly, wrap that whole record thing inside back ticks (including that part inside curly braces) (alternatively you can disable markdown-it-attrs).

**Comment by brc-dd** [comment]
Yeah it doesn't, you need to write ` ```js`
