### ISSUE TITLE
TypeError: code.split is not a function when attempting to build

### ISSUE THREAD

**Issue by CodyBontecou** [vuejs/vitepress#1114]
### Describe the bug

I am getting the following error when trying to run Vitepress' build command:

```
✖ rendering pages...
build error:
 TypeError: code.split is not a function
    at prettifyMessage (/Users/codybontecou/Code/blog/node_modules/vite/dist/node/chunks/dep-c9998dc6.js:19904:28)
    at /Users/codybontecou/Code/blog/node_modules/vite/dist/node/chunks/dep-c9998dc6.js:19794:35
    at Array.forEach (<anonymous>)
    at transformWithEsbuild (/Users/codybontecou/Code/blog/node_modules/vite/dist/node/chunks/dep-c9998dc6.js:19793:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///Users/codybontecou/Code/blog/node_modules/vitepress/dist/node/serve-05342c3d.js:39642:22
    at async Promise.all (index 11)
    at async renderPage (file:///Users/codybontecou/Code/blog/node_modules/vitepress/dist/node/serve-05342c3d.js:39614:7)
    at async build (file:///Users/codybontecou/Code/blog/node_modules/vitepress/dist/node/serve-05342c3d.js:39853:9)
```

### Reproduction

1. Clone this repo + branch - https://github.com/CodyBontecou/blog/tree/vitepress-migration
2. Install dependencies
3. Run build command - `yarn build`

### Expected behavior

I expect the site to build

### System Info

```shell
System:
    OS: macOS 12.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 2.28 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v16.14.2/bin/yarn
    npm: 8.7.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 103.0.5060.134
    Safari: 15.6
```
```


### Additional context

_No response_

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by CodyBontecou** [comment]
I just want to note, that although the replication repo has .split methods, I've attempted to build the app after deleting all .split uses and the build continued to fail.

**Comment by brc-dd** [comment]
I just deleted your config file (and all undefined components from md), it builds fine. You might wanna recheck your config file.

**Comment by brc-dd** [comment]
Your inline gtag script is causing certain issues, remove that, it'll build. However there's a lot of stuff wrong with your themeConfig.

**Comment by brc-dd** [comment]
It's syntax is wrong. It should be like this:

```js
    [
      'script',
      {},
      "window.dataLayer = window.dataLayer || [];\nfunction gtag(){dataLayer.push(arguments);}\ngtag('js', new Date());\ngtag('config', 'G-3NM0E524EK');"
    ]
```

You've passed the code part in an array.

**Comment by CodyBontecou** [comment]
Yup, this helped a ton. Thank you.
