### ISSUE TITLE
Unable to use element-plus with vitepress: works in dev mode, but fails to build

### ISSUE THREAD

**Issue by akil-rails** [vuejs/vitepress#1164]
### Describe the bug

docs:build fails element-plus, when used with unplugin-vue-components and ssr: false

```
    Components({
      dirs: ['components'],
      include: [/\.vue$/, /\.md$/],
      resolvers: [ElementPlusResolver({ ssr: false })]
    })

```

While changing to ssr:true gets the build to succeed, with this CSS isn't loaded. 

### Reproduction

1. Close the repo https://github.com/akil-rails/vitepress-with-element-plus
2. pnpm docs:build

Build fails with the following error: 

```
> vitepress build docs

vitepress v1.0.0-alpha.4
⠸ building client + server bundles...warnings when minifying css:
▲ [WARNING] "@charset" must be the first rule in the file

    <stdin>:3820:0:
      3820 │ @charset "UTF-8";:root{--el-color-white:#ffffff;--el-color-black...
           ╵ ~~~~~~~~

  This rule cannot come before a "@charset" rule

    <stdin>:1:0:
      1 │ @font-face {
        ╵ ^


✓ building client + server bundles...
⠋ rendering pages...Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/akhileshkataria/Code/spikes/vitepress-with-element-plus/node_modules/.pnpm/element-plus@2.2.13_vue@3.2.37/node_modules/element-plus/es/index.mjs not supported.
Instead change the require of /Users/akhileshkataria/Code/spikes/vitepress-with-element-plus/node_modules/.pnpm/element-plus@2.2.13_vue@3.2.37/node_modules/element-plus/es/index.mjs to a dynamic import() which is available in all CommonJS modules.
    at Module.<anonymous> (/Users/akhileshkataria/Code/spikes/vitepress-with-element-plus/docs/.vitepress/.temp/index.md.js:3:10)
    at /Users/akhileshkataria/Code/spikes/vitepress-with-element-plus/docs/.vitepress/.temp/app.js:4045:50
    at async loadPage (/Users/akhileshkataria/Code/spikes/vitepress-with-element-plus/docs/.vitepress/.temp/app.js:216:16) {
  code: 'ERR_REQUIRE_ESM'
}
✖ rendering pages...
build error:
 Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/akhileshkataria/Code/spikes/vitepress-with-element-plus/node_modules/.pnpm/element-plus@2.2.13_vue@3.2.37/node_modules/element-plus/es/index.mjs not supported.
Instead change the require of /Users/akhileshkataria/Code/spikes/vitepress-with-element-plus/node_modules/.pnpm/element-plus@2.2.13_vue@3.2.37/node_modules/element-plus/es/index.mjs to a dynamic import() which is available in all CommonJS modules.
    at Module.<anonymous> (/Users/akhileshkataria/Code/spikes/vitepress-with-element-plus/docs/.vitepress/.temp/index.md.js:3:10)
    at async Promise.all (index 0)
    at async renderPage (file:///Users/akhileshkataria/Code/spikes/vitepress-with-element-plus/node_modules/.pnpm/vitepress@1.0.0-alpha.4/node_modules/vitepress/dist/node/serve-05342c3d.js:39555:28)
    at async build (file:///Users/akhileshkataria/Code/spikes/vitepress-with-element-plus/node_modules/.pnpm/vitepress@1.0.0-alpha.4/node_modules/vitepress/dist/node/serve-05342c3d.js:39853:9) {
  code: 'ERR_REQUIRE_ESM'

```

### Expected behavior

The build should succeed.

### System Info

```shell
System:
    OS: macOS 11.6.7
    CPU: (8) x64 Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz
    Memory: 510.54 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.15.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 103.0.5060.53
    Safari: 15.5
  npmPackages:
    vitepress: 1.0.0-alpha.4 => 1.0.0-alpha.4
```

### Additional context

element-plus has been discussed earlier:  https://github.com/vuejs/vitepress/issues/603

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
It looks like we can't avoid `ssr.noExternal` here. Other frameworks like Astro are also recommending this to avoid css import issues. Let's close this then. For people who are seeing this later please refer the linked discussion for details.

**Comment by akil-rails** [comment]
This has stopped working with the new versions of vitepress; a reproducible sample is [here](https://github.com/akil-rails/vitepress-with-element-plus)
