### ISSUE TITLE
image error

### ISSUE THREAD

**Issue by jw-star** [vuejs/vitepress#1269]
### Describe the bug

The test environment is working properly ，But switching to the formal environment reported an error 。

### Reproduction

```
<img src='image/clash_and_2.png' width="80%" />
```

### Expected behavior

The production environment can be used normally 

### System Info

```shell
2022-09-01T11:51:43.601874Z	Cloning repository...
2022-09-01T11:51:44.916742Z	From https://github.com/jw-star/blogVite
2022-09-01T11:51:44.917329Z	 * branch            cb67994ae09fa09bc762047c0fd711c2bb2e406a -> FETCH_HEAD
2022-09-01T11:51:44.917534Z	
2022-09-01T11:51:44.972264Z	HEAD is now at cb67994 update
2022-09-01T11:51:44.97283Z	
2022-09-01T11:51:45.118925Z	
2022-09-01T11:51:45.146471Z	Success: Finished cloning repository files
2022-09-01T11:51:45.767236Z	Installing dependencies
2022-09-01T11:51:45.778538Z	Python version set to 2.7
2022-09-01T11:51:49.064491Z	Downloading and installing node v16.17.0...
2022-09-01T11:51:49.460702Z	Downloading https://nodejs.org/dist/v16.17.0/node-v16.17.0-linux-x64.tar.xz...
2022-09-01T11:51:49.854904Z	Computing checksum with sha256sum
2022-09-01T11:51:49.986322Z	Checksums matched!
2022-09-01T11:51:54.367543Z	Now using node v16.17.0 (npm v8.15.0)
2022-09-01T11:51:54.768415Z	Started restoring cached build plugins
2022-09-01T11:51:54.782008Z	Finished restoring cached build plugins
2022-09-01T11:51:55.296601Z	Attempting ruby version 2.7.1, read from environment
2022-09-01T11:51:58.915623Z	Using ruby version 2.7.1
2022-09-01T11:51:59.27759Z	Using PHP version 5.6
2022-09-01T11:51:59.445112Z	5.2 is already installed.
2022-09-01T11:51:59.472159Z	Using Swift version 5.2
2022-09-01T11:51:59.472698Z	Started restoring cached node modules
2022-09-01T11:51:59.488478Z	Finished restoring cached node modules
2022-09-01T11:51:59.496315Z	Started restoring cached yarn cache
2022-09-01T11:51:59.510805Z	Finished restoring cached yarn cache
2022-09-01T11:51:59.531157Z	Installing yarn at version 1.22.4
2022-09-01T11:51:59.549166Z	[37mInstalling Yarn![0m
2022-09-01T11:51:59.549467Z	[36m> Downloading tarball...[0m
2022-09-01T11:51:59.591937Z	
2022-09-01T11:51:59.592274Z	[1/2]: https://yarnpkg.com/downloads/1.22.4/yarn-v1.22.4.tar.gz --> /tmp/yarn.tar.gz.sKRQT0bQoY
2022-09-01T11:51:59.59303Z	  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2022-09-01T11:51:59.59347Z	                                 Dload  Upload   Total   Spent    Left  Speed
2022-09-01T11:51:59.835355Z	
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    79  100    79    0     0    325      0 --:--:-- --:--:-- --:--:--   325
2022-09-01T11:51:59.920814Z	
100    92  100    92    0     0    280      0 --:--:-- --:--:-- --:--:--   280
2022-09-01T11:52:00.090412Z	
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
2022-09-01T11:52:00.429175Z	
100 1215k  100 1215k    0     0  1453k      0 --:--:-- --:--:-- --:--:-- 1453k
2022-09-01T11:52:00.429504Z	
2022-09-01T11:52:00.429697Z	[2/2]: https://yarnpkg.com/downloads/1.22.4/yarn-v1.22.4.tar.gz.asc --> /tmp/yarn.tar.gz.sKRQT0bQoY.asc
2022-09-01T11:52:00.475534Z	
100    83  100    83    0     0   1830      0 --:--:-- --:--:-- --:--:--  1830
2022-09-01T11:52:00.478975Z	
100    96  100    96    0     0   1964      0 --:--:-- --:--:-- --:--:--  1964
2022-09-01T11:52:00.502963Z	
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
2022-09-01T11:52:00.603245Z	
100  1028  100  1028    0     0   5940      0 --:--:-- --:--:-- --:--:--  5940
2022-09-01T11:52:00.655666Z	[36m> Verifying integrity...[0m
2022-09-01T11:52:00.701676Z	gpg: Signature made Mon 09 Mar 2020 03:52:13 PM UTC using RSA key ID 69475BAA
2022-09-01T11:52:00.707781Z	gpg: Good signature from "Yarn Packaging <yarn@dan.cx>"
2022-09-01T11:52:00.710364Z	gpg: Note: This key has expired!
2022-09-01T11:52:00.710627Z	Primary key fingerprint: 72EC F46A 56B4 AD39 C907  BBB7 1646 B01B 86E5 0310
2022-09-01T11:52:00.710823Z	     Subkey fingerprint: 6D98 490C 6F1A CDDD 448E  4595 4F77 6793 6947 5BAA
2022-09-01T11:52:00.711502Z	[32m> GPG signature looks good[0m
2022-09-01T11:52:00.711709Z	[36m> Extracting to ~/.yarn...[0m
2022-09-01T11:52:00.805956Z	[36m> Adding to $PATH...[0m
2022-09-01T11:52:00.831595Z	[36m> We've added the following to your /opt/buildhome/.bashrc
2022-09-01T11:52:00.831928Z	> If this isn't the profile of your current shell then please add the following to your correct profile:
2022-09-01T11:52:00.832135Z	   
2022-09-01T11:52:00.832275Z	export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
2022-09-01T11:52:00.833097Z	[0m
2022-09-01T11:52:01.234033Z	[32m> Successfully installed Yarn 1.22.4! Please open another terminal where the `yarn` command will now be available.[0m
2022-09-01T11:52:01.640283Z	Installing NPM modules using Yarn version 1.22.4
2022-09-01T11:52:02.151234Z	npm WARN config tmp This setting is no longer used.  npm stores temporary files in a special
2022-09-01T11:52:02.151538Z	npm WARN config location in the cache, and they are managed by
2022-09-01T11:52:02.151694Z	npm WARN config     [`cacache`](http://npm.im/cacache).
2022-09-01T11:52:02.405549Z	yarn install v1.22.4
2022-09-01T11:52:02.455105Z	[1/4] Resolving packages...
2022-09-01T11:52:02.517167Z	[2/4] Fetching packages...
2022-09-01T11:52:06.091753Z	info fsevents@2.3.2: The platform "linux" is incompatible with this module.
2022-09-01T11:52:06.092054Z	info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
2022-09-01T11:52:06.092538Z	info @esbuild/linux-loong64@0.14.54: The CPU architecture "x64" is incompatible with this module.
2022-09-01T11:52:06.092888Z	info "@esbuild/linux-loong64@0.14.54" is an optional dependency and failed compatibility check. Excluding it from installation.
2022-09-01T11:52:06.093255Z	info esbuild-android-64@0.14.54: The platform "linux" is incompatible with this module.
2022-09-01T11:52:06.093542Z	info "esbuild-android-64@0.14.54" is an optional dependency and failed compatibility check. Excluding it from installation.
2022-09-01T11:52:06.093789Z	info esbuild-android-arm64@0.14.54: The platform "linux" is incompatible with this module.
2022-09-01T11:52:06.093937Z	info "esbuild-android-arm64@0.14.54" is an optional dependency and failed compatibility check. Excluding it from installation.
2022-09-01T11:52:06.094288Z	info esbuild-android-arm64@0.14.54: The CPU architecture "x64" is incompatible with this module.
2022-09-01T11:52:06.094534Z	info esbuild-darwin-64@0.14.54: The platform "linux" is incompatible with this module.
2022-09-01T11:52:06.09478Z	info "esbuild-darwin-64@0.14.54" is an optional dependency and failed compatibility check. Excluding it from installation.
2022-09-01T11:52:06.095017Z	info esbuild-darwin-arm64@0.14.54: The platform "linux" is incompatible with this module.
2022-09-01T11:52:06.095264Z	info "esbuild-darwin-arm64@0.14.54" is an optional dependency and failed compatibility check. Excluding it from installation.
2022-09-01T11:52:06.09547Z	info esbuild-darwin-arm64@0.14.54: The CPU architecture "x64" is incompatible with this module.
2022-09-01T11:52:06.095804Z	info esbuild-freebsd-64@0.14.54: The platform "linux" is incompatible with this module.
2022-09-01T11:52:06.096089Z	info "esbuild-freebsd-64@0.14.54" is an optional dependency and failed compatibility check. Excluding it from installation.
2022-09-01T11:52:06.096465Z	info esbuild-freebsd-arm64@0.14.54: The platform "linux" is incompatible with this module.
2022-09-01T11:52:06.096826Z	info "esbuild-freebsd-arm64@0.14.54" is an optional dependency and failed compatibility check. Excluding it from installation.
2022-09-01T11:52:06.097102Z	info esbuild-freebsd-arm64@0.14.54: The CPU architecture "x64" is incompatible with this module.
2022-09-01T11:52:06.097351Z	info esbuild-linux-32@0.14.54: The CPU architecture "x64" is incompatible with this module.
2022-09-01T11:52:06.097514Z	info "esbuild-linux-32@0.14.54" is an optional dependency and failed compatibility check. Excluding it from installation.
2022-09-01T11:52:06.097866Z	info esbuild-linux-arm@0.14.54: The CPU architecture "x64" is incompatible with this module.
2022-09-01T11:52:06.098604Z	info "esbuild-linux-arm@0.14.54" is an optional dependency and failed compatibility check. Excluding it from installation.
2022-09-01T11:52:06.098765Z	info esbuild-linux-arm64@0.14.54: The CPU architecture "x64" is incompatible with this module.
2022-09-01T11:52:06.098886Z	info "esbuild-linux-arm64@0.14.54" is an optional dependency and failed compatibility check. Excluding it from installation.
2022-09-01T11:52:06.099083Z	info esbuild-linux-mips64le@0.14.54: The CPU architecture "x64" is incompatible with this module.
2022-09-01T11:52:06.099287Z	info "esbuild-linux-mips64le@0.14.54" is an optional dependency and failed compatibility check. Excluding it from installation.
2022-09-01T11:52:06.099484Z	info esbuild-linux-ppc64le@0.14.54: The CPU architecture "x64" is incompatible with this module.
2022-09-01T11:52:06.099624Z	info "esbuild-linux-ppc64le@0.14.54" is an optional dependency and failed compatibility check. Excluding it from installation.
2022-09-01T11:52:06.099749Z	info esbuild-linux-riscv64@0.14.54: The CPU architecture "x64" is incompatible with this module.
2022-09-01T11:52:06.099857Z	info "esbuild-linux-riscv64@0.14.54" is an optional dependency and failed compatibility check. Excluding it from installation.
2022-09-01T11:52:06.099962Z	info esbuild-linux-s390x@0.14.54: The CPU architecture "x64" is incompatible with this module.
2022-09-01T11:52:06.100077Z	info "esbuild-linux-s390x@0.14.54" is an optional dependency and failed compatibility check. Excluding it from installation.
2022-09-01T11:52:06.100206Z	info esbuild-netbsd-64@0.14.54: The platform "linux" is incompatible with this module.
2022-09-01T11:52:06.100379Z	info "esbuild-netbsd-64@0.14.54" is an optional dependency and failed compatibility check. Excluding it from installation.
2022-09-01T11:52:06.100492Z	info esbuild-openbsd-64@0.14.54: The platform "linux" is incompatible with this module.
2022-09-01T11:52:06.100597Z	info "esbuild-openbsd-64@0.14.54" is an optional dependency and failed compatibility check. Excluding it from installation.
2022-09-01T11:52:06.100726Z	info esbuild-sunos-64@0.14.54: The platform "linux" is incompatible with this module.
2022-09-01T11:52:06.100882Z	info "esbuild-sunos-64@0.14.54" is an optional dependency and failed compatibility check. Excluding it from installation.
2022-09-01T11:52:06.100997Z	info esbuild-windows-32@0.14.54: The platform "linux" is incompatible with this module.
2022-09-01T11:52:06.101102Z	info "esbuild-windows-32@0.14.54" is an optional dependency and failed compatibility check. Excluding it from installation.
2022-09-01T11:52:06.101239Z	info esbuild-windows-32@0.14.54: The CPU architecture "x64" is incompatible with this module.
2022-09-01T11:52:06.101347Z	info esbuild-windows-64@0.14.54: The platform "linux" is incompatible with this module.
2022-09-01T11:52:06.101488Z	info "esbuild-windows-64@0.14.54" is an optional dependency and failed compatibility check. Excluding it from installation.
2022-09-01T11:52:06.101602Z	info esbuild-windows-arm64@0.14.54: The platform "linux" is incompatible with this module.
2022-09-01T11:52:06.101712Z	info "esbuild-windows-arm64@0.14.54" is an optional dependency and failed compatibility check. Excluding it from installation.
2022-09-01T11:52:06.101823Z	info esbuild-windows-arm64@0.14.54: The CPU architecture "x64" is incompatible with this module.
2022-09-01T11:52:06.102003Z	[3/4] Linking dependencies...
2022-09-01T11:52:06.102289Z	warning "vitepress > @docsearch/js > @docsearch/react > @algolia/autocomplete-preset-algolia@1.7.1" has unmet peer dependency "@algolia/client-search@^4.9.1".
2022-09-01T11:52:06.966624Z	[4/4] Building fresh packages...
2022-09-01T11:52:07.226393Z	Done in 4.83s.
2022-09-01T11:52:07.249299Z	NPM modules installed using Yarn
2022-09-01T11:52:07.548071Z	Installing Hugo 0.54.0
2022-09-01T11:52:08.363957Z	Hugo Static Site Generator v0.54.0-B1A82C61A/extended linux/amd64 BuildDate: 2019-02-01T10:04:38Z
2022-09-01T11:52:08.368529Z	Started restoring cached go cache
2022-09-01T11:52:08.388169Z	Finished restoring cached go cache
2022-09-01T11:52:08.538254Z	go version go1.14.4 linux/amd64
2022-09-01T11:52:08.55281Z	go version go1.14.4 linux/amd64
2022-09-01T11:52:08.555654Z	Installing missing commands
2022-09-01T11:52:08.556064Z	Verify run directory
2022-09-01T11:52:08.556413Z	Executing user command: yarn docs:build
2022-09-01T11:52:08.802839Z	yarn run v1.22.4
2022-09-01T11:52:08.836197Z	$ vitepress build docs
2022-09-01T11:52:09.225294Z	vitepress v1.0.0-alpha.13
2022-09-01T11:52:09.284531Z	- building client + server bundles...
2022-09-01T11:52:10.50159Z	[vite]: Rollup failed to resolve import "image/clash_and_1.png" from "docs/clash_android.md".
2022-09-01T11:52:10.50204Z	This is most likely unintended because it can break your application at runtime.
2022-09-01T11:52:10.502355Z	If you do want to externalize this module explicitly add it to
2022-09-01T11:52:10.502632Z	`build.rollupOptions.external`
2022-09-01T11:52:10.502846Z	[31m✖[0m building client + server bundles...
2022-09-01T11:52:10.5073Z	build error:
2022-09-01T11:52:10.507491Z	 Error: [vite]: Rollup failed to resolve import "image/clash_and_1.png" from "docs/clash_android.md".
2022-09-01T11:52:10.507623Z	This is most likely unintended because it can break your application at runtime.
2022-09-01T11:52:10.50777Z	If you do want to externalize this module explicitly add it to
2022-09-01T11:52:10.507889Z	`build.rollupOptions.external`
2022-09-01T11:52:10.508001Z	    at onRollupWarning (file:///opt/buildhome/repo/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:43721:19)
2022-09-01T11:52:10.508111Z	    at onwarn (file:///opt/buildhome/repo/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:43520:13)
2022-09-01T11:52:10.508259Z	    at Object.onwarn (file:///opt/buildhome/repo/node_modules/rollup/dist/es/shared/rollup.js:23178:13)
2022-09-01T11:52:10.508374Z	    at ModuleLoader.handleResolveId (file:///opt/buildhome/repo/node_modules/rollup/dist/es/shared/rollup.js:22335:26)
2022-09-01T11:52:10.508505Z	    at file:///opt/buildhome/repo/node_modules/rollup/dist/es/shared/rollup.js:22296:26 {
2022-09-01T11:52:10.508627Z	  watchFiles: [
2022-09-01T11:52:10.508751Z	    '/opt/buildhome/repo/node_modules/vitepress/dist/client/app/index.js',
2022-09-01T11:52:10.508863Z	    '/opt/buildhome/repo/docs/clash_android.md',
2022-09-01T11:52:10.50897Z	    '/opt/buildhome/repo/docs/clash_windows.md',
2022-09-01T11:52:10.509076Z	    '/opt/buildhome/repo/docs/index.md',
2022-09-01T11:52:10.509213Z	    '/opt/buildhome/repo/docs/quantumultX.md',
2022-09-01T11:52:10.509326Z	    '/opt/buildhome/repo/docs/shadowrocket.md',
2022-09-01T11:52:10.509439Z	    '/opt/buildhome/repo/docs/v2rayN.md',
2022-09-01T11:52:10.509543Z	    '/opt/buildhome/repo/docs/v2rayNG.md',
2022-09-01T11:52:10.509649Z	    '/opt/buildhome/repo/node_modules/vitepress/dist/client/app/utils.js',
2022-09-01T11:52:10.509764Z	    '/opt/buildhome/repo/node_modules/vitepress/dist/client/app/router.js',
2022-09-01T11:52:10.509878Z	    '/opt/buildhome/repo/node_modules/vitepress/dist/client/app/data.js',
2022-09-01T11:52:10.51005Z	    '/opt/buildhome/repo/node_modules/vitepress/dist/client/app/composables/head.js',
2022-09-01T11:52:10.510182Z	    '/opt/buildhome/repo/node_modules/vitepress/dist/client/app/composables/preFetch.js',
2022-09-01T11:52:10.510293Z	    '/opt/buildhome/repo/node_modules/vitepress/dist/client/app/components/Content.js',
2022-09-01T11:52:10.510405Z	    '/opt/buildhome/repo/node_modules/vitepress/dist/client/app/components/ClientOnly.js',
2022-09-01T11:52:10.510518Z	    '/opt/buildhome/repo/node_modules/vitepress/dist/client/app/composables/copyCode.js',
2022-09-01T11:52:10.510623Z	    '/opt/buildhome/repo/node_modules/vue/dist/vue.runtime.esm-bundler.js',
2022-09-01T11:52:10.510745Z	    '/opt/buildhome/repo/node_modules/vitepress/dist/client/theme-default/index.js',
2022-09-01T11:52:10.510855Z	    '\x00vite/preload-helper',
2022-09-01T11:52:10.510961Z	    '/opt/buildhome/repo/node_modules/vitepress/dist/client/app/devtools.js',
2022-09-01T11:52:10.511066Z	    '\x00plugin-vue:export-helper'
2022-09-01T11:52:10.51119Z	  ]
2022-09-01T11:52:10.511309Z	}
2022-09-01T11:52:10.537562Z	error Command failed with exit code 1.
2022-09-01T11:52:10.537864Z	info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2022-09-01T11:52:10.552831Z	Failed: build command exited with code: 1
2022-09-01T11:52:11.334822Z	Failed: an internal error occurred
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Where is your `image/clash_and_2.png` stored?

**Comment by jw-star** [comment]
> Where is your `image/clash_and_2.png` stored? If its in public directory your path should be `/image/clash_and_2.png`.

![Uploading Screenshot_20220902_011140.jpg…]()

**Comment by jw-star** [comment]
![Uploading Screenshot_20220902_011140.jpg…]()
P

**Comment by jw-star** [comment]
![Uploading Screenshot_20220902_011140.jpg…]()

**Comment by jw-star** [comment]
thanks,it is worked
