### ISSUE TITLE
build error:  Error [SyntaxError]: Error parsing JavaScript expression: Unexpected token, expected "," (1:4)

### ISSUE THREAD

**Issue by gyhyfj** [vuejs/vitepress#1330]
### Describe the bug

Cannot build if there is md file in  `./docs` , with special content. 

### Reproduction

When there's  such one md file in `./docs` :
```markdown
1. 内联样式 style 属性不接收字符串，要使用 `style={{key:value}}`
``` 
Then I run `yarn docs:build`, command will fail with exit code 1.

The following is the error info in terminal:
```
vitepress v1.0.0-alpha.13
⠦ building client + server bundles...[vite:vue] Error parsing JavaScript expression: Unexpected token, expected "," (1:4)
file: D:/GitRepo/gyhyfj/docs/react/ABC.md:2:43
✖ building client + server bundles...
build error:
 Error [SyntaxError]: Error parsing JavaScript expression: Unexpected token, expected "," (1:4)
    at createCompilerError (D:\GitRepo\gyhyfj\node_modules\.pnpm\@vue+compiler-core@3.2.39\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:18:19)       
    at processExpression (D:\GitRepo\gyhyfj\node_modules\.pnpm\@vue+compiler-core@3.2.39\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:3423:25)       
    at Array.transformExpression (D:\GitRepo\gyhyfj\node_modules\.pnpm\@vue+compiler-core@3.2.39\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:3256:24)
...
...
...
 ELIFECYCLE  Command failed with exit code 1.
```

If I delete this md files or delete this line, everything would be OK.
This problem can be reproducted whether on my PC or on Vercel

### Expected behavior

Build command should work well as I don't delete this line in the md file.

### System Info

```shell
System:
  OS: Windows 10 10.0.19044
  CPU: (8) x64 Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
  Memory: 2.58 GB / 7.92 GB
Binaries:
  Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
  Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
  npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
Browsers:
  Edge: Spartan (44.19041.1266.0), Chromium (105.0.1343.33)
  Internet Explorer: 11.0.19041.1566
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
https://github.com/vuejs/vitepress/discussions/480#discussioncomment-2225141
