### ISSUE TITLE
Ambiguous error in build process/temp files deleted on failed build

### ISSUE THREAD

**Issue by hardingalexh** [vuejs/vitepress#1424]
### Describe the bug

I've implemented a vitepress site for a component library used internally. Running `npm run docs:dev` works as intended and the documentation site is functional. When I attempt to build the docs site, I get an ambiguous error that has no line references other than line references to a temp file that is deleted by the same process, so I have no way to diagnose what this error is. I'm sure it's a simple fix, but without saving that temp file or finding a better stack trace, I don't feel like I have direction to find where to start.

```bash
❯ npm run docs:build 

> @rtidatascience/harness-vue-bootstrap@1.0.0 docs:build
> vitepress build docs

vitepress v1.0.0-alpha.17
⠋ building client + server bundles..."compileScript" is imported from external module "vue/compiler-sfc" but never used in "docs/.vitepress/harness-pages/examplePage.js".
⠼ building client + server bundles...
(!) Some chunks are larger than 500 KiB after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/guide/en/#outputmanualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
✓ building client + server bundles...
✖ rendering pages...
build error:
 TypeError: Cannot read properties of undefined (reading 'filter')
    at _sfc_ssrRender$1 (file:///Users/alexharding/Projects/harness-vue-starter-template/dev-packages/harness-vue-bootstrap/docs/.vitepress/.temp/app.js:5710:164)
    at renderComponentSubTree (/Users/alexharding/Projects/harness-vue-starter-template/dev-packages/harness-vue-bootstrap/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:251:17)
    at renderComponentVNode (/Users/alexharding/Projects/harness-vue-starter-template/dev-packages/harness-vue-bootstrap/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:185:16)
    at ssrRenderComponent (/Users/alexharding/Projects/harness-vue-starter-template/dev-packages/harness-vue-bootstrap/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:609:12)
    at _sfc_ssrRender (file:///Users/alexharding/Projects/harness-vue-starter-template/dev-packages/harness-vue-bootstrap/docs/.vitepress/.temp/components_filters_multiselectListbox.md.js:9:9)
    at renderComponentSubTree (/Users/alexharding/Projects/harness-vue-starter-template/dev-packages/harness-vue-bootstrap/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:251:17)
    at renderComponentVNode (/Users/alexharding/Projects/harness-vue-starter-template/dev-packages/harness-vue-bootstrap/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:185:16)
    at renderVNode (/Users/alexharding/Projects/harness-vue-starter-template/dev-packages/harness-vue-bootstrap/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:296:22)
    at renderVNodeChildren (/Users/alexharding/Projects/harness-vue-starter-template/dev-packages/harness-vue-bootstrap/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:311:9)
    at renderElementVNode (/Users/alexharding/Projects/harness-vue-starter-template/dev-packages/harness-vue-bootstrap/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:362:17)
```

### Reproduction

Clone the repository [harness-vue-bootstrap](https://github.com/RTIInternational/harness-vue-bootstrap)
`npm install`
`npm run docs:build`

### Expected behavior

An option to save temporary files on failed build.

### System Info

```shell
System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 353.69 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Firefox: 105.0.1
    Safari: 15.6.1
```
```


### Additional context

_No response_

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Set DEBUG env variable to True. It will preserve your temp files then. You can also use debug scopes (https://www.npmjs.com/package/debug).

**Comment by hardingalexh** [comment]
Awesome, that did maintain the temp files which gives me a starting point. Appreciate the fast help!
