### ISSUE TITLE
容错率太低了， 以下文档也会进行报错。

### ISSUE THREAD

**Issue by jerry-f** [vuejs/vitepress#1470]
### Describe the bug

在 xx.md 文件中输入以下文档会报错：
## 测试文档

> 　　　<n>y = 密钥在 n 年后过期
> 　　密钥的有效期限是？(0)

11
22

33

### Reproduction

输入以上内容，编译错误

### Expected behavior

能够正常的编译， 

### System Info

```shell
17:38:38 [vite] Internal server error: Element is missing end tag.
  Plugin: vite:vue
  File: D:/pro/doc/my-docs/docs/l-note/GPG入门教程.md
  6  |  
  7  |  
  8  |  11
     |    ^
  9  |  22
  10 |  
      at createCompilerError (D:\pro\doc\my-docs\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:19:19)
      at emitError (D:\pro\doc\my-docs\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:1602:29)
      at parseElement (D:\pro\doc\my-docs\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:1154:9)
      at parseChildren (D:\pro\doc\my-docs\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:937:28)
      at parseElement (D:\pro\doc\my-docs\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:1133:22)
      at parseChildren (D:\pro\doc\my-docs\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:937:28)
      at parseElement (D:\pro\doc\my-docs\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:1133:22)
      at parseChildren (D:\pro\doc\my-docs\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:937:28)
      at parseElement (D:\pro\doc\my-docs\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:1133:22)
      at parseChildren (D:\pro\doc\my-docs\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:937:28)
```

### Additional context

![image](https://user-images.githubusercontent.com/30689170/195308666-eebd045b-0b5e-4a0a-b0ad-dec9635e3148.png)

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by jerry-f** [comment]
其他的一些 markdown 查看器是不会报错的， 比如使用 docsify 都能够正常的显示。 其实就是一个简单的markdown 即使 markdown 语法有问题，也不应该报错。编译不通过， 建议如果哪里有问题， 给一个 waring 警告，或者 error 警告， 内容还是要显示出来

**Comment by brc-dd** [comment]
There is clearly an error as you've something like `<n> ....`. Any CommonMark compliant markdown parser will recognize this as an element tag, which is never closed. You need to wrap that in backticks `` ` ``.

**Comment by webpon** [comment]
+1

**Comment by webpon** [comment]
> 

most editor can preview right ok?

**Comment by webpon** [comment]
> There is clearly an error as you've something like `<n> ....`. Any CommonMark compliant markdown parser will recognize this as an element tag, which is never closed. You need to wrap that in backticks `` ` ``.
> 
> 这里显然有一个错误，因为您有类似 < n > ... ... 的东西。任何符合 CommonMark 的 Markdown 解析器都会将其识别为一个永远不会关闭的元素标记。你需要把它包起来。

This bug is just one of them. Can't you be tolerant of grammar? I'm really impressed

**Comment by webpon** [comment]
![image](https://user-images.githubusercontent.com/50807258/212562585-015c3ba9-3bb6-40a6-ab75-23149d3686f9.png)
I'm really bored
