### ISSUE TITLE
When using vitepress to package and build, it is found that "build error:  Error: Whitespace was expected."

### ISSUE THREAD

**Issue by CrazyMrYan** [vuejs/vitepress#1526]
### Describe the bug

When using vitepress to package and build, it is found that "build error:

Error: Whitespace was expected."

### Reproduction

1. Create a new md file
2. The written content contains<script>content
3. Build

### Expected behavior

Successful Build Project

### System Info

```shell
System:
    OS: Linux 3.10 CentOS Linux 7 (Core)
    CPU: (1) x64 AMD EPYC 7K62 48-Core Processor
    Memory: 328.55 MB / 990.87 MB
    Container: Yes
    Shell: 4.2.46 - /bin/bash
  Binaries:
    Node: 16.16.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.14.0 - /usr/bin/npm
  npmPackages:
    vitepress: ^0.7.2 => 0.7.2
```

### Additional context

building client bundle...
Language does not exist: npm
Language does not exist: code
Language does not exist: <script
build error:
 Error: Whitespace was expected.
    at error (/www/wwwroot/server/blog/node_modules/rollup/dist/shared/rollup.js:5252:30)
    at throwPluginError (/www/wwwroot/server/blog/node_modules/rollup/dist/shared/rollup.js:17916:12)
    at Object.error (/www/wwwroot/server/blog/node_modules/rollup/dist/shared/rollup.js:18523:24)
    at Object.error (/www/wwwroot/server/blog/node_modules/rollup/dist/shared/rollup.js:18085:38)
    at /www/wwwroot/server/blog/node_modules/rollup-plugin-vue/dist/index.js:211:52
    at Array.forEach (<anonymous>)
    at Object.transform (/www/wwwroot/server/blog/node_modules/rollup-plugin-vue/dist/index.js:211:28)
    at /www/wwwroot/server/blog/node_modules/rollup/dist/shared/rollup.js:18724:25 {
  id: '/www/wwwroot/server/blog/docs/9777e974-d9f8-468f-9859-eb078bcf5b8d.md',
  plugin: 'vue',
  pluginCode: '15',
  frame: '',
  parserError: SyntaxError: Whitespace was expected.
      at createCompilerError (/www/wwwroot/server/blog/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:16:19)
      at emitError (/www/wwwroot/server/blog/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:1187:29)
      at parseAttributes (/www/wwwroot/server/blog/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:941:13)
      at parseTag (/www/wwwroot/server/blog/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:857:17)
      at parseElement (/www/wwwroot/server/blog/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:807:21)
      at parseChildren (/www/wwwroot/server/blog/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:650:28)
      at parseElement (/www/wwwroot/server/blog/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:816:22)
      at parseChildren (/www/wwwroot/server/blog/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:650:28)
      at parseElement (/www/wwwroot/server/blog/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:816:22)
      at parseChildren (/www/wwwroot/server/blog/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:650:28) {
    code: 15,
    loc: { start: [Object], end: [Object], source: '' }
  },
  loc: {
    file: '/www/wwwroot/server/blog/docs/9777e974-d9f8-468f-9859-eb078bcf5b8d.md',
    line: 110,
    column: 35
  },
  hook: 'transform',
  code: 'PLUGIN_ERROR',

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Can you show your code?

**Comment by CrazyMrYan** [comment]
> 你能显示你的代码吗？

Of course, this is my markdown file

[9777e974-d9f8-468f-9859 -eb078bcf5b8d.md](https://github.com/vuejs/vitepress/files/9844126/9777e974-d9f8-468f-9859.-eb078bcf5b8d.md)

**Comment by brc-dd** [comment]
Near line 171, you've forgot to wrap the content in ` ``` `. Change that, it'll work fine.

![image](https://user-images.githubusercontent.com/40380293/197335460-cfffb71c-1aab-4cd4-98de-61ebaf7eb830.png)

**Comment by CrazyMrYan** [comment]
Wow~Thank you very much. I love you!
