### ISSUE TITLE
Element is missing end tag

### ISSUE THREAD

**Issue by scopor** [vuejs/vitepress#1590]
### Describe the bug

error detail:  https://github.com/scopor/wiki/actions/runs/3417036686/jobs/5687761775

I miss the error in update a markdown file， file：https://raw.githubusercontent.com/scopor/wiki/main/docs/reading/css.md

Run yarn docs:build
  yarn docs:build
  shell: /usr/bin/bash -e {0}
yarn run v1.[2](https://github.com/scopor/wiki/actions/runs/3417036686/jobs/5687761775#step:6:2)2.19
$ vitepress build docs
vitepress v1.0.0-alpha.17
- building client + server bundles...
[vite:vue] Element is missing end tag.
file: /home/runner/work/wiki/wiki/docs/reading/css.md:208:110
✖ building client + server bundles...
build error:
 Error [SyntaxError]: Element is missing end tag.
    at createCompilerError (/home/runner/work/wiki/wiki/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:18:19)
    at emitError (/home/runner/work/wiki/wiki/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:157[3](https://github.com/scopor/wiki/actions/runs/3417036686/jobs/5687761775#step:6:3):29)
    at parseElement (/home/runner/work/wiki/wiki/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:11[4](https://github.com/scopor/wiki/actions/runs/3417036686/jobs/5687761775#step:6:5)8:9)
    at parseChildren (/home/runner/work/wiki/wiki/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:932:28)
    at parseElement (/home/runner/work/wiki/wiki/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:112[7](https://github.com/scopor/wiki/actions/runs/3417036686/jobs/5687761775#step:6:8):22)
    at parseChildren (/home/runner/work/wiki/wiki/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:932:2[8](https://github.com/scopor/wiki/actions/runs/3417036686/jobs/5687761775#step:6:9))
    at parseElement (/home/runner/work/wiki/wiki/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:1127:22)
    at parseChildren (/home/runner/work/wiki/wiki/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:[9](https://github.com/scopor/wiki/actions/runs/3417036686/jobs/5687761775#step:6:10)32:28)
    at parseElement (/home/runner/work/wiki/wiki/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:1127:22)
    at parseChildren (/home/runner/work/wiki/wiki/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:932:28) {
  id: '/home/runner/work/wiki/wiki/docs/reading/css.md',
  plugin: 'vite:vue',
  loc: {
    file: '/home/runner/work/wiki/wiki/docs/reading/css.md',
    line: 208,
    column: 1[10](https://github.com/scopor/wiki/actions/runs/3417036686/jobs/5687761775#step:6:11)
  },

### Reproduction

1、modify file
2、trigger github actions：  yarn docs:build

### Expected behavior

yarn docs:build

### System Info

github actions

```shell
vitepress v1.0.0-alpha.17
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by laddish** [comment]
maybe try alter this to `<p></p>`?
![image](https://user-images.githubusercontent.com/49431692/200505616-232e1df9-7289-4d7c-b188-711ae0ad6c3e.png)

**Comment by laddish** [comment]
![image](https://user-images.githubusercontent.com/49431692/200506472-0c363b15-0ad1-4f48-a8d0-72d8218b8998.png)
oh alter this to `<html></html>`

**Comment by scopor** [comment]
> ![image](https://user-images.githubusercontent.com/49431692/200506472-0c363b15-0ad1-4f48-a8d0-72d8218b8998.png) oh alter this to `<html></html>`

OK，Thanks。
