### ISSUE TITLE
build error: vitepress data not properly injected in app

### ISSUE THREAD

**Issue by lianguooo** [vuejs/vitepress#1598]
### Describe the bug

I followed the base tutorial but had a error in `yarn docs:build` step.

【error info】
vitepress v1.0.0-draft.8
✓ building client + server bundles...
- rendering pages...Error: vitepress data not properly injected in app
    at useData (D:\develop\nodejs\vitepress\docs\.vitepress\.temp\app.js:160:11)
    at setup (D:\develop\nodejs\vitepress\docs\.vitepress\.temp\app.js:3641:22)
    at callWithErrorHandling (D:\develop\nodejs\vitepress\.yarn\cache\@vue-runtime-core-npm-3.2.33-5266e9dcdb-8eaba9a5d9.zip\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:119:22)
    at setupStatefulComponent (D:\develop\nodejs\vitepress\.yarn\cache\@vue-runtime-core-npm-3.2.33-5266e9dcdb-8eaba9a5d9.zip\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:5738:29)
    at setupComponent (D:\develop\nodejs\vitepress\.yarn\cache\@vue-runtime-core-npm-3.2.33-5266e9dcdb-8eaba9a5d9.zip\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:5719:11)
    at renderComponentVNode (D:\develop\nodejs\vitepress\.yarn\__virtual__\@vue-server-renderer-virtual-7f8bff4d3b\0\cache\@vue-server-renderer-npm-3.2.33-023ce834d6-effc448e52.zip\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:195:17)
    at Module.<anonymous> (D:\develop\nodejs\vitepress\.yarn\__virtual__\@vue-server-renderer-virtual-7f8bff4d3b\0\cache\@vue-server-renderer-npm-3.2.33-023ce834d6-effc448e52.zip\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:459:30)
    at Generator.next (<anonymous>)
    at D:\develop\nodejs\vitepress\.yarn\__virtual__\@vue-server-renderer-virtual-7f8bff4d3b\0\cache\@vue-server-renderer-npm-3.2.33-023ce834d6-effc448e52.zip\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:30:71
    at new Promise (<anonymous>)
[Vue warn]: Component VitePressApp  is missing template or render function.
✓ rendering pages...
build complete in 4.23s.

### Reproduction

package.json
{
  "name": "vitepress",
  "packageManager": "yarn@3.2.4",
  "devDependencies": {
    "vitepress": "^1.0.0-alpha.28",
    "vue": "^3.2.44"
  },
  "scripts": {
    "docs:dev": "vitepress dev docs",
    "docs:build": "vitepress build docs",
    "docs:serve": "vitepress serve docs"
  }
}

### Expected behavior

build success

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 AMD Ryzen 5 5600U with Radeon Graphics
    Memory: 21.97 GB / 35.84 GB
  Binaries:
    Node: 16.18.0 - D:\Program Files\nodejs\node.EXE
    Yarn: 3.2.4 - D:\Program Files\nodejs\yarn.CMD
    npm: 8.19.2 - D:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.71)
    Internet Explorer: 11.0.19041.1566
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
In your logs it is showing "vitepress v1.0.0-draft.8". But in your package.json it's alpha.28. Can you try removing the lock file and re running yarn install?

**Comment by brc-dd** [comment]
closing due to inactivity
