### ISSUE TITLE
Can't build vitepress when I use npm package

### ISSUE THREAD

**Issue by songwuk** [vuejs/vitepress#1638]
### Describe the bug

I am writing the package of  `controllable-animate` and preparing write doc for this package 

when I run npm run docs:dev it works just fine
but when I run npm run docs:build it failed
and shows an error message:
```sh
✓ building client + server bundles...
build error:
 ReferenceError: document is not defined
    at file:///Users/songwufan/Desktop/newPro/controllable-animate/docs/main/.vitepress/.temp/app.js:4380:3
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async build (file:///Users/songwufan/Desktop/newPro/controllable-animate/node_modules/.pnpm/vitepress@1.0.0-alpha.29_tbpndr44ulefs3hehwpi2mkf2y/node_modules/vitepress/dist/node/serve-fcdc8868.js:42002:24)
```
reproduce  steps: 
First: I try to use `docuement`  in vue directive like this: 
```ts
if (typeof window !== undefined) {
  root = document.documentElement || document.body
}
```
Second:  I use this package in my code ：main/.vitepress/theme/index.ts
```ts
import {
  vcontrollableanimate,
} from 'controllable-animate'
export default {
  ...DefaultTheme,
  enhanceApp({ app }) {
    // app.Plugin
    app.directive('controllable-animate', vcontrollableanimate)
  },
}
```

### Reproduction

none

### Expected behavior

It should work in dev and build mode.

### System Info

```shell
System:
    OS: macOS 12.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Memory: 103.34 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.19.0 - ~/.nvm/versions/node/v14.19.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.14.16 - ~/.nvm/versions/node/v14.19.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 107.0.5304.110
    Chrome Canary: 110.0.5434.0
    Firefox: 97.0.2
    Firefox Developer Edition: 106.0
    Safari: 15.6.1
  npmPackages:
    vitepress: 1.0.0-alpha.29 => 1.0.0-alpha.29
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
It should be `typeof window !== 'undefined'`
