### ISSUE TITLE
docs:build failed TypeError: document.getElementsByTagName is not a function

### ISSUE THREAD

**Issue by towerhe** [vuejs/vitepress#1669]
### Describe the bug

I'm trying to provide a wangeditor component to my vue 3 app. wangeditor uses prism to highlight codes.

In prism-core.js, it has codes as follows: 

```js
currentScript: function () {
      if (typeof document === 'undefined') {
	      return null;
      }
      if ('currentScript' in document && 1 < 2 /* hack to trip TS' flow analysis */) {
	      return /** @type {any} */ (document.currentScript);
      }
      
      // IE11 workaround
      // we'll get the src of the current script by parsing IE11's error stack trace
      // this will not work for inline scripts
      
      try {
	      throw new Error();
      } catch (err) {
	      // Get file src url from stack. Specifically works with the format of stack traces in IE.
	      // A stack will look like this:
	      //
	      // Error
	      //    at _.util.currentScript (http://localhost/components/prism-core.js:119:5)
	      //    at Global code (http://localhost/components/prism-core.js:606:1)
      
	      var src = (/at [^(\r\n]*\((.*):[^:]+:[^:]+\)$/i.exec(err.stack) || [])[1];
	      if (src) {
		      var scripts = document.getElementsByTagName('script');
		      for (var i in scripts) {
			      if (scripts[i].src == src) {
				      return scripts[i];
			      }
		      }
	      }
	      return null;
      }
}
```

prism-core.js is packaged to the release index.js of wangeditor.

By using `vitepress dev .` it works. But when I try to run `vitepress build .`. It broken.

```
✓ building client + server bundles...
- rendering pages...
TypeError: document.getElementsByTagName is not a function
    at Object.currentScript (file:///Users/towerhe/Repository/codes/yicen/jaguar/jaguar-vui/packages/tdesign-docs/.vitepress/.temp/vui-tdesign.bcf20abb.js:32887:30)
```

### Reproduction

...

### Expected behavior

vitepress build . passed

### System Info

```shell
System:
    OS: macOS 13.0.1
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 1.35 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.0 - ~/.asdf/installs/nodejs/16.18.0/bin/node
    Yarn: 1.22.19 - ~/.asdf/installs/nodejs/16.18.0/bin/yarn
    npm: 8.19.2 - ~/.asdf/installs/nodejs/16.18.0/bin/npm
  Browsers:
    Firefox: 101.0.1
    Safari: 16.1
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by az031120103** [comment]
遇到同样的问题

**Comment by tolking** [comment]
Maybe you should wrap your component with [ClientOnly](https://vitepress.vuejs.org/guide/api#clientonly)

**Comment by LiZhaoYangClub** [comment]
有解决的吗

**Comment by brc-dd** [comment]
Those APIs are not there in Node.js. That's why it throws error during SSR. You can either use ClientOnly or use dynamic imports inside onMounted hook. Read https://vitepress.dev/guide/ssr-compat#ssr-compatibility
