### ISSUE TITLE
Uncaught SyntaxError: Unexpected identifier 'project' (at client:1:39) index.js:1 Uncaught SyntaxError: Unexpected identifier 'project' (at index.js:1:288)

### ISSUE THREAD

**Issue by chenjieya** [vuejs/vitepress#1699]
### Describe the bug

我刚刚发现了这个vitepress，但是我按照官网的步骤一步一步的执行，当我启动项目的时候发现控制台报错了

Uncaught SyntaxError: Unexpected identifier 'project' (at client:1:39)
index.js:1 Uncaught SyntaxError: Unexpected identifier 'project' (at index.js:1:288)

### Reproduction

1.mkdir vitepress-starter && cd vitepress-starter
2.yarn init
3.yarn add --dev vitepress vue
4.mkdir docs && echo '# Hello VitePress' > docs/index.md
5.配置脚本启动项目
6.控制台出现错误（Uncaught SyntaxError: Unexpected identifier 'project' (at client:1:39)
index.js:1 Uncaught SyntaxError: Unexpected identifier 'project' (at index.js:1:288)）

### Expected behavior

不报错

### System Info

```shell
System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1 Pro
    Memory: 64.11 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Safari: 15.6.1
  npmPackages:
    vitepress: ^1.0.0-alpha.31 => 1.0.0-alpha.31
```

### Additional context

![image](https://user-images.githubusercontent.com/79642899/208058458-a758b447-7294-41ce-8a00-f38018783055.png)

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
I am not able to reproduce this 👀  Can someone else confirm / elaborate on how to reproduce this?

**Comment by chenjieya** [comment]
> 

Thank you for your reply. I'm studying some carefully. It may be caused by my operation mistakes

**Comment by brc-dd** [comment]
Closing due to inactivity. If this is still happening with you, feel free to open this, better if you can provide a repo to reproduce. Thanks!
