### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by Tyh2001** [vuejs/vitepress#1716]
### Describe the bug

build error

```shell

vitepress v1.0.0-alpha.32
⠹ building client + server bundles...[vite:esbuild] Transform failed with 1 error:
D:/项目-我的/fighting-design/node_modules/.pnpm/vitepress@1.0.0-alpha.32_tbpndr44ulefs3hehwpi2mkf2y/node_modules/vitepress/dist/client/theme-default/components/VPFooter.vue?vue&type=script&setup=true&lang.ts:1:8: ERROR: Expected ">" but found "setup"
file: D:/项目-我的/fighting-design/node_modules/.pnpm/vitepress@1.0.0-alpha.32_tbpndr44ulefs3hehwpi2mkf2y/node_modules/vitepress/dist/client/theme-default/components/VPFooter.vue?vue&type=script&setup=true&lang.ts:1:8

Expected ">" but found "setup"
1  |  <script setup lang="ts">
   |          ^
2  |  import { useData } from 'vitepress'
3  |  import { useSidebar } from '../composables/sidebar.js'

✖ building client + server bundles...
build error:
 Error: Transform failed with 1 error:
D:/项目-我的/fighting-design/node_modules/.pnpm/vitepress@1.0.0-alpha.32_tbpndr44ulefs3hehwpi2mkf2y/node_modules/vitepress/dist/client/theme-default/components/VPFooter.vue?vue&type=script&setup=true&lang.ts:1:8: ERROR: Expected ">" but found "setup"
    at failureErrorWithLog (D:\项目-我的\fighting-design\node_modules\.pnpm\esbuild@0.16.9\node_modules\esbuild\lib\main.js:1594:15)
    at D:\项目-我的\fighting-design\node_modules\.pnpm\esbuild@0.16.9\node_modules\esbuild\lib\main.js:831:29
    at responseCallbacks.<computed> (D:\项目-我的\fighting-design\node_modules\.pnpm\esbuild@0.16.9\node_modules\esbuild\lib\main.js:697:9)
    at handleIncomingPacket (D:\项目-我的\fighting-design\node_modules\.pnpm\esbuild@0.16.9\node_modules\esbuild\lib\main.js:752:9)
    at Socket.readFromStdout (D:\项目-我的\fighting-design\node_modules\.pnpm\esbuild@0.16.9\node_modules\esbuild\lib\main.js:673:7)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: [Object],
      notes: [],
      pluginName: '',
      text: 'Expected ">" but found "setup"'
    }
  ],
  warnings: [],
  frame: '\n' +
    '\x1B[33mExpected ">" but found "setup"\x1B[39m\n' +
    '1  |  <script setup lang="ts">\n' +
    '   |          ^\n' +
    "2  |  import { useData } from 'vitepress'\n" +
    "3  |  import { useSidebar } from '../composables/sidebar.js'\n",
  loc: {
    column: 8,
    file: 'D:/项目-我的/fighting-design/node_modules/.pnpm/vitepress@1.0.0-alpha.32_tbpndr44ulefs3hehwpi2mkf2y/node_modules/vitepress/dist/client/theme-default/components/VPFooter.vue?vue&type=script&setup=true&lang.ts',
    length: 5,
    line: 1,
    lineText: '<script setup lang="ts">',
    namespace: '',
    suggestion: '>'
  },
  code: 'PLUGIN_ERROR',
  plugin: 'vite:esbuild',
  hook: 'transform',
  id: 'D:/项目-我的/fighting-design/node_modules/.pnpm/vitepress@1.0.0-alpha.32_tbpndr44ulefs3hehwpi2mkf2y/node_modules/vitepress/dist/client/theme-default/components/VPFooter.vue?vue&type=script&setup=true&lang.ts',
  watchFiles: [
    'D:/项目-我的/fighting-design/node_modules/.pnpm/vitepress@1.0.0-alpha.32_tbpndr44ulefs3hehwpi2mkf2y/node_modules/vitepress/dist/client/app/index.js',
    'D:/项目-我的/fighting-design/docs/README.md',
    'D:/项目-我的/fighting-design/docs/components/alert.md',
    'D:/项目-我的/fighting-design/docs/components/avatar.md',
    'D:/项目-我的/fighting-design/docs/components/back-top.md',
    'D:/项目-我的/fighting-design/docs/components/badge.md',
    'D:/项目-我的/fighting-design/docs/components/breadcrumb.md',
    'D:/项目-我的/fighting-design/docs/components/button.md',
    'D:/项目-我的/fighting-design/docs/components/calendar.md',
    'D:/项目-我的/fighting-design/docs/components/card.md',
    'D:/项目-我的/fighting-design/docs/components/checkbox.md',
    'D:/项目-我的/fighting-design/docs/components/close-btn.md',
    'D:/项目-我的/fighting-design/docs/components/collapse-animation.md',
    'D:/项目-我的/fighting-design/docs/components/color.md',
    'D:/项目-我的/fighting-design/docs/components/date-picker.md',
    'D:/项目-我的/fighting-design/docs/components/dialog.md',
    'D:/项目-我的/fighting-design/docs/components/divider.md',
    'D:/项目-我的/fighting-design/docs/components/drawer.md',
    'D:/项目-我的/fighting-design/docs/components/dropdown.md',
    'D:/项目-我的/fighting-design/docs/components/empty.md',
    'D:/项目-我的/fighting-design/docs/components/expand-card.md',
    'D:/项目-我的/fighting-design/docs/components/fighting-global.md',
    'D:/项目-我的/fighting-design/docs/components/form-1.md',
    'D:/项目-我的/fighting-design/docs/components/form.md',
    'D:/项目-我的/fighting-design/docs/components/image-preview.md',
    'D:/项目-我的/fighting-design/docs/components/image.md',
    'D:/项目-我的/fighting-design/docs/components/input-number.md',
    'D:/项目-我的/fighting-design/docs/components/input.md',
    'D:/项目-我的/fighting-design/docs/components/interface.md',
    'D:/项目-我的/fighting-design/docs/components/layout.md',
    'D:/项目-我的/fighting-design/docs/components/link.md',
    'D:/项目-我的/fighting-design/docs/components/list.md',
    'D:/项目-我的/fighting-design/docs/components/loading-bar.md',
    'D:/项目-我的/fighting-design/docs/components/loading.md',
    'D:/项目-我的/fighting-design/docs/components/menu.md',
    'D:/项目-我的/fighting-design/docs/components/message.md',
    'D:/项目-我的/fighting-design/docs/components/notification.md',
    'D:/项目-我的/fighting-design/docs/components/page-header.md',
    'D:/项目-我的/fighting-design/docs/components/pagination.md',
    'D:/项目-我的/fighting-design/docs/components/popup.md',
    'D:/项目-我的/fighting-design/docs/components/progress.md',
    'D:/项目-我的/fighting-design/docs/components/radio.md',
    'D:/项目-我的/fighting-design/docs/components/rate.md',
    'D:/项目-我的/fighting-design/docs/components/ripple.md',
    'D:/项目-我的/fighting-design/docs/components/select.md',
    'D:/项目-我的/fighting-design/docs/components/skeleton.md',
    'D:/项目-我的/fighting-design/docs/components/slider.md',
    'D:/项目-我的/fighting-design/docs/components/space.md',
    'D:/项目-我的/fighting-design/docs/components/sticky-card.md',
    'D:/项目-我的/fighting-design/docs/components/svg-icon.md',
    'D:/项目-我的/fighting-design/docs/components/swap.md',
    'D:/项目-我的/fighting-design/docs/components/switch.md',
    'D:/项目-我的/fighting-design/docs/components/table.md',
    'D:/项目-我的/fighting-design/docs/components/tabs.md',
    'D:/项目-我的/fighting-design/docs/components/tag.md',
    'D:/项目-我的/fighting-design/docs/components/text.md',
    'D:/项目-我的/fighting-design/docs/components/textarea.md',
    'D:/项目-我的/fighting-design/docs/components/time-picker.md',
    'D:/项目-我的/fighting-design/docs/components/toolbar.md',
    'D:/项目-我的/fighting-design/docs/components/tooltip.md',
    'D:/项目-我的/fighting-design/docs/components/tree.md',
    'D:/项目-我的/fighting-design/docs/components/trigger.md',
    'D:/项目-我的/fighting-design/docs/components/up-load.md',
    'D:/项目-我的/fighting-design/docs/components/watermark.md',
    'D:/项目-我的/fighting-design/docs/docs/changelog.md',
    'D:/项目-我的/fighting-design/docs/docs/contributing.md',
    'D:/项目-我的/fighting-design/docs/docs/import.md',
    'D:/项目-我的/fighting-design/docs/docs/install.md',
    'D:/项目-我的/fighting-design/docs/docs/introduce.md',
    'D:/项目-我的/fighting-design/docs/docs/join.md',
    'D:/项目-我的/fighting-design/docs/docs/milepost.md',
    'D:/项目-我的/fighting-design/docs/index.md',
    'D:/项目-我的/fighting-design/docs/theme/start.md',
    'D:/项目-我的/fighting-design/node_modules/.pnpm/vitepress@1.0.0-alpha.32_tbpndr44ulefs3hehwpi2mkf2y/node_modules/vitepress/dist/client/app/utils.js',
    'D:/项目-我的/fighting-design/node_modules/.pnpm/vitepress@1.0.0-alpha.32_tbpndr44ulefs3hehwpi2mkf2y/node_modules/vitepress/dist/client/app/router.js',
    'D:/项目-我的/fighting-design/node_modules/.pnpm/vitepress@1.0.0-alpha.32_tbpndr44ulefs3hehwpi2mkf2y/node_modules/vitepress/dist/client/app/data.js',
    'D:/项目-我的/fighting-design/node_modules/.pnpm/vitepress@1.0.0-alpha.32_tbpndr44ulefs3hehwpi2mkf2y/node_modules/vitepress/dist/client/app/composables/head.js',
    'D:/项目-我的/fighting-design/node_modules/.pnpm/vitepress@1.0.0-alpha.32_tbpndr44ulefs3hehwpi2mkf2y/node_modules/vitepress/dist/client/app/composables/preFetch.js',
    'D:/项目-我的/fighting-design/node_modules/.pnpm/vitepress@1.0.0-alpha.32_tbpndr44ulefs3hehwpi2mkf2y/node_modules/vitepress/dist/client/app/components/Content.js',
    'D:/项目-我的/fighting-design/node_modules/.pnpm/vitepress@1.0.0-alpha.32_tbpndr44ulefs3hehwpi2mkf2y/node_modules/vitepress/dist/client/app/components/ClientOnly.js',
    'D:/项目-我的/fighting-design/node_modules/.pnpm/vitepress@1.0.0-alpha.32_tbpndr44ulefs3hehwpi2mkf2y/node_modules/vitepress/dist/client/app/composables/copyCode.js',
    'D:/项目-我的/fighting-design/node_modules/.pnpm/vitepress@1.0.0-alpha.32_tbpndr44ulefs3hehwpi2mkf2y/node_modules/vitepress/dist/client/app/composables/codeGroups.js',
    'D:/项目-我的/fighting-design/node_modules/.pnpm/vitepress@1.0.0-alpha.32_tbpndr44ulefs3hehwpi2mkf2y/node_modules/vitepress/dist/client/app/devtools.js',
    'D:/项目-我的/fighting-design/node_modules/.pnpm/vue@3.2.45/node_modules/vue/dist/vue.runtime.esm-bundler.js',        
    '\x00vite/preload-helper',
    'D:/项目-我的/fighting-design/docs/.vitepress/theme/index.ts',
    '\x00plugin-vue:export-helper',
    'D:/项目-我的/fighting-design/docs/components/page-header.md?vue&type=script&lang.ts',
    'D:/项目-我的/fighting-design/docs/components/list.md?vue&type=script&lang.ts',
    'D:/项目-我的/fighting-design/docs/components/divider.md?vue&type=script&lang.ts',
    'D:/项目-我的/fighting-design/docs/components/link.md?vue&type=script&lang.ts',
    'D:/项目-我的/fighting-design/node_modules/.pnpm/vitepress@1.0.0-alpha.32_tbpndr44ulefs3hehwpi2mkf2y/node_modules/vitepress/dist/client/shared.js',
    '/@siteData',
    'D:/项目-我的/fighting-design/docs/components/empty.md?vue&type=script&lang.ts',
    'D:/项目-我的/fighting-design/docs/components/form-1.md?vue&type=script&setup=true&lang.ts',
    'D:/项目-我的/fighting-design/docs/components/dropdown.md?vue&type=script&lang.ts',
    'D:/项目-我的/fighting-design/docs/components/fighting-global.md?vue&type=script&lang.ts',
    'D:/项目-我的/fighting-design/node_modules/.pnpm/vitepress@1.0.0-alpha.32_tbpndr44ulefs3hehwpi2mkf2y/node_modules/vitepress/dist/client/index.js',
    'D:\\项目-我的\\fighting-design\\node_modules\\.pnpm\\@vue+runtime-dom@3.2.45\\node_modules\\@vue\\runtime-dom\\package.json',
    'D:/项目-我的/fighting-design/node_modules/.pnpm/@vue+runtime-dom@3.2.45/node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js',
    ... 709 more items
  ]
}
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
```

### Reproduction

pnpm build 

### Expected behavior

success

### System Info

```shell
windows 11
"vitepress": "1.0.0-alpha.32"
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by Tyh2001** [comment]
@brc-dd
