### ISSUE TITLE
Build doesn't support symbolic links

### ISSUE THREAD

**Issue by lukeromanowicz** [vuejs/vitepress#184]
**Describe the bug**
In dev mode symbolic links work just fine but building process fails with following errors:
```
$ vitepress build docs
vitepress v0.9.2
vite v1.0.0-rc.13
✓ building client + server bundles...
✖ rendering pages...
build error:
 TypeError: Cannot read property 'imports' of undefined
    at resolvePageImports (/home/lromanowicz/projects/vitepress-issues/node_modules/vitepress/dist/node/build/render.js:74:68)
    at Object.renderPage (/home/lromanowicz/projects/vitepress-issues/node_modules/vitepress/dist/node/build/render.js:35:12)
    at async Object.build (/home/lromanowicz/projects/vitepress-issues/node_modules/vitepress/dist/node/build/build.js:29:17)
error Command failed with exit code 1.
```

**To Reproduce**
* add a directory with docs through a symbolic link

https://github.com/lukeromanowicz/vitepress-issues/tree/issue/building-not-supporting-symbolic-links

**Expected behavior**
Building supports symbolic links just like dev mode does.

**System Info**
- vitepress version: 0.9.2
- vite version: 1.0.0-rc.13 
- Node version: 14LTS
- OS version: Ubuntu 20

**Comment by bowencool** [comment]
It seems that there is still this problem
```
▶ yarn build:docs
yarn run v1.22.10
$ vitepress build docs
vitepress v0.15.6
vite v2.4.1
✓ building client + server bundles...
⠋ rendering pages...
✖ rendering pages...
build error:
 TypeError: Cannot read property 'imports' of undefined
    at resolvePageImports (/Users/zhaobowen/mk/fe-infra/element++/node_modules/vitepress/dist/node/build/render.js:81:22)
    at Object.renderPage (/Users/zhaobowen/mk/fe-infra/element++/node_modules/vitepress/dist/node/build/render.js:35:12)
    at async Object.build (/Users/zhaobowen/mk/fe-infra/element++/node_modules/vitepress/dist/node/build/build.js:29:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
