### ISSUE TITLE
windows is not defined

### ISSUE THREAD

**Issue by jarryxy** [vuejs/vitepress#1870]
### Reproduction

```sh
yarn docs:build
yarn run v1.22.19
$ vitepress build docs
vitepress v1.0.0-alpha.40
⠼ building client + server bundles...The language 'text' is not loaded, falling back to 'txt' for syntax highlighting.
✓ building client + server bundles...
⠋ rendering pages...ReferenceError: window is not defined
    at Proxy.created (file:///Users/jiaxiaoyu/Desktop/vueWorkspace/cwUI-docs/docs/.vitepress/.temp/app.js:4189:22)
    at callWithErrorHandling (/Users/jiaxiaoyu/Desktop/vu
```

### Expected behavior

```sh
yarn docs:build
yarn run v1.22.19
$ vitepress build docs
vitepress v1.0.0-alpha.40
⠼ building client + server bundles...The language 'text' is not loaded, falling back to 'txt' for syntax highlighting.
✓ building client + server bundles...
⠋ rendering pages...ReferenceError: window is not defined
    at Proxy.created (file:///Users/jiaxiaoyu/Desktop/vueWorkspace/cwUI-docs/docs/.vitepress/.temp/app.js:4189:22)
    at callWithErrorHandling (/Users/jiaxiaoyu/Desktop/vu
```

### System Info

```shell
yarn docs:build
yarn run v1.22.19
$ vitepress build docs
vitepress v1.0.0-alpha.40
⠼ building client + server bundles...The language 'text' is not loaded, falling back to 'txt' for syntax highlighting.
✓ building client + server bundles...
⠋ rendering pages...ReferenceError: window is not defined
    at Proxy.created (file:///Users/jiaxiaoyu/Desktop/vueWorkspace/cwUI-docs/docs/.vitepress/.temp/app.js:4189:22)
    at callWithErrorHandling (/Users/jiaxiaoyu/Desktop/vu
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by jarryxy** [comment]
https://vitepress.vuejs.org/guide/using-vue
请确保在beforeMount或mounted钩子中访问浏览器/DOM API。
