### ISSUE TITLE
embed *.mov format video via vitpress

### ISSUE THREAD

**Issue by rookie-hhm** [vuejs/vitepress#1968]
### Describe the bug

when I embed *.mov format video in vitepress，it work fine with command `npm run docs:dev`,but I get an error when I run `npm run docs:build`(**Whether the resource is placed in the Pulbic directory or relative path**)

vitepress version: `v1.0.0-alpha.47`

In relative path case:
code:
```js
<video controls autoplay="autoplay">
<source src="./images/ora.mov">
</video>
```
error message: 
```js
building client + server bundles...[vite:build-import-analysis] Parse error @:1:59
file: /Users/rookie/Desktop/classes/blog/docs/node/images/ora.mov:1:58
1: ftypqt  qt wide��mdat���0]!Kq�q,��)�S%�@��b�b���
                                                             ^
2: R��?O�����B/h�����
                     ��K���GJ�ے�H.�����
3: p<*xJ���܏B��'��{��[����Щ�h��^#%��]d�h�����3k��������'���}����*�[���� T�{y�H���>@�:����e-��E��T�븈��@
                              �9E�|7�F�$,B[]8�r��m��D���T��k�.�G���F<��(���b���<��b+]ԧΡ#�fC�V�?rsER;jD��5����П��4���� y��J���
                                                     ѕ�Q2���]p�����(�jD�H\ݗ��!?O�B���B��d����WAH�/V^�̇�
                              �`�F��#Kw;�c�Epיp�k����)~)B
                                                         ;8苮LKV���d(0�66oe�V
     �{/�|��<��DVr_9��Z%���ff@�H)=�$��;�bbu��*zW4��6�M��H��J�D��"
                                                                 �L�
                                                                    @�0��g���t��PO��r)��y��b�������.��4R�}���� {B�,��Q�Rt�V���Y��E[��S-
                                                               _�˥�B?z��+�XI�R  �^D���4Z)dÀ<��:����s[���w'øh�k�V[8�-�������y�

✖ building client + server bundles...
build error:
Error: Parse error @:1:59
    at parse$e (file:///Users/rookie/Desktop/classes/blog/node_modules/_vite@4.1.3@vite/dist/node/chunks/dep-ae3fae1b.js:14787:355)
    at Object.transform (file:///Users/rookie/Desktop/classes/blog/node_modules/_vite@4.1.3@vite/dist/node/chunks/dep-ae3fae1b.js:43531:27)
```

In public path case:
code:
```js
<video controls autoplay="autoplay">
<source src="/images/ora.mov">
</video>
```
error message:
```js
⠏ building client + server bundles...[vite]: Rollup failed to resolve import "/images/ora.mov" from "/Users/rookie/Desktop/classes/blog/docs/node/ora.md".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
✖ building client + server bundles...
build error:
Error: [vite]: Rollup failed to resolve import "/images/ora.mov" from "/Users/rookie/Desktop/classes/blog/docs/node/ora.md".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at onRollupWarning (file:///Users/rookie/Desktop/classes/blog/node_modules/_vite@4.1.3@vite/dist/node/chunks/dep-ae3fae1b.js:44781:19)
    at onwarn (file:///Users/rookie/Desktop/classes/blog/node_modules/_vite@4.1.3@vite/dist/node/chunks/dep-ae3fae1b.js:44551:13)
    at Object.onwarn (file:///Users/rookie/Desktop/classes/blog/node_modules/_rollup@3.17.2@rollup/dist/es/shared/node-entry.js:24922:13)
    at ModuleLoader.handleInvalidResolvedId (file:///Users/rookie/Desktop/classes/blog/node_modules/_rollup@3.17.2@rollup/dist/es/shared/node-entry.js:23605:26)
    at file:///Users/rookie/Desktop/classes/blog/node_modules/_rollup@3.17.2@rollup/dist/es/shared/node-entry.js:23565:26
```

### Reproduction

1. clone repository
```bash
git clone https://github.com/rookie-hhm/rookie-blog.git
```
2. enter project and checkout branch `test-mov`
```bash
cd rookie-blog && git checkout test-mov
```
3. install dependency & build
```bash
npm install && npm run docs:build
```

### Expected behavior

Both development and production environments can be packaged successfully

### System Info

```shell
System:
    OS: macOS 12.5.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 916.77 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.19.0/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Safari: 15.6.1
  npmPackages:
    vitepress: ^1.0.0-alpha.47 => 1.0.0-alpha.47
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by MarkusKeck** [comment]
Works fine on my system. I was able to build without any errors.

![image](https://user-images.githubusercontent.com/19492739/220397467-765f15d4-2fed-462b-9fa6-f05ce202823d.png)

**Comment by MarkusKeck** [comment]
It works if  use the `.mp4` format instead of `.mov`
Maybe a workaround for now.

**Comment by brc-dd** [comment]
For the meantime, if you want to keep the mov format, then probably do something like:

```html
<video controls autoplay="autoplay">
  <source :src="oraMov">
</video>

<script setup>
import oraMov from './images/ora.mov?url'
</script>
```

Haven't tested but it should work. Probably seems like an upstream issue with vite.

**Comment by MarkusKeck** [comment]
`.mov` files are not in the default list of asset types
https://github.com/vitejs/vite/blob/e87ae41/packages/vite/src/node/constants.ts#L58

create the file `/docs/vite.config.ts` and define it, after that It works

```ts
import { defineConfig } from 'vite'

export default defineConfig({
    assetsInclude: ['**/*.mov']
})
```

**Comment by rookie-hhm** [comment]
> 



> It works if use the `.mp4` format instead of `.mov` Maybe a workaround for now.

Yeah, that's one way

**Comment by rookie-hhm** [comment]
> ```ts
> import { defineConfig } from 'vite'
> 
> export default defineConfig({
>     assetsInclude: ['**/*.mov']
> })
> ```

thanks, it works for me！

**Comment by rookie-hhm** [comment]
> For the meantime, if you want to keep the mov format, then maybe do something like:
> 
> ```
> <video controls autoplay="autoplay">
>   <source :src="oraMov">
> </video>
> 
> <script setup>
> import oraMov from './images/ora.mov?url'
> </script>
> ```
> 
> Haven't tested but it should work. Probably seems like an upstream issue with vite.

Thanks, that solves my problem

**Comment by MarkusKeck** [comment]
@rookie-hhm perfect, if you have no further problems regarding this topic would you mind closing this issue?
