### ISSUE TITLE
Build error 打包报错

### ISSUE THREAD

**Issue by Tyh2001** [vuejs/vitepress#1971]
### Describe the bug

这是一个概率性的问题，并不是每次打包都会报错，报错的概率比较低，但是仍然存在，我有尝试更新 vitepress 和 vue 的最新版本，和代码的写法。但是都没有得到有效的解决

### Reproduction

具体问题出现在 [fighting-design](https://github.com/FightingDesign/fighting-design) 项目上

```json
"node": ">= 16"
```

```shell
# 安装依赖
pnpm i

# 启动文档
pnpm dev:docs

# 打包文档
pnpm build:docs
```

概率性问题，多打包几次就会出现，比较随机

### Expected behavior

打包成功

### System Info

```shell
windows 11
```

### Additional context

我尝试打包了将近20次的测试，共得到了下面三种报错方式：

## 错误代码 1

```shell
PS D:\项目-我的\fighting-design> pnpm build:docs

> fighting-design@ build:docs D:\项目-我的\fighting-design
> pnpm run -C docs build


> docs@ build D:\项目-我的\fighting-design\docs
> vitepress build


  vitepress v1.0.0-alpha.47

⠴ building client + server bundles...[vite:esbuild] Transform failed with 1 error:
D:/项目-我的/fighting-design/node_modules/.pnpm/vitepress@1.0.0-alpha.47_2r467mdhb7mblpaox4bg7fatdi/node_modules/vitepress/dist/client/theme-default/components/VPTeamMembersItem.vue?vue&type=script&setup=true&lang.ts:1:8: ERROR: Expected ">" but found "setup"
file: D:/项目-我的/fighting-design/node_modules/.pnpm/vitepress@1.0.0-alpha.47_2r467mdhb7mblpaox4bg7fatdi/node_modules/vitepress/dist/client/theme-default/components/VPTeamMembersItem.vue?vue&type=script&setup=true&lang.ts:1:8

Expected ">" but found "setup"
1  |  <script setup lang="ts">
   |          ^
2  |  import type { DefaultTheme } from 'vitepress/theme'
3  |  import VPIconHeart from './icons/VPIconHeart.vue'

✖ building client + server bundles...
build error:
Error: Transform failed with 1 error:
D:/项目-我的/fighting-design/node_modules/.pnpm/vitepress@1.0.0-alpha.47_2r467mdhb7mblpaox4bg7fatdi/node_modules/vitepress/dist/client/theme-default/components/VPTeamMembersItem.vue?vue&type=script&setup=true&lang.ts:1:8: ERROR: Expected ">" but found "setup"
    at failureErrorWithLog (D:\项目-我的\fighting-design\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:1604:15)
    at D:\项目-我的\fighting-design\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:837:29
    at responseCallbacks.<computed> (D:\项目-我的\fighting-design\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:701:9)
    at handleIncomingPacket (D:\项目-我的\fighting-design\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:756:9)
    at Socket.readFromStdout (D:\项目-我的\fighting-design\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:677:7)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
PS D:\项目-我的\fighting-design>
```

## 错误代码 2

```shell
PS D:\项目-我的\fighting-design> pnpm build:docs

> fighting-design@ build:docs D:\项目-我的\fighting-design
> pnpm run -C docs build


> docs@ build D:\项目-我的\fighting-design\docs     
> vitepress build


  vitepress v1.0.0-alpha.47

⠦ building client + server bundles...[vite:esbuild] Transform failed with 1 error:
D:/项目-我的/fighting-design/node_modules/.pnpm/vitepress@1.0.0-alpha.47_2r467mdhb7mblpaox4bg7fatdi/node_modules/vitepress/dist/client/theme-default/components/VPSponsors.vue?vue&type=script&setup=true&lang.ts:1:8: ERROR: Expected ">" but found "setup"
file: D:/项目-我的/fighting-design/node_modules/.pnpm/vitepress@1.0.0-alpha.47_2r467mdhb7mblpaox4bg7fatdi/node_modules/vitepress/dist/client/theme-default/components/VPSponsors.vue?vue&type=script&setup=true&lang.ts:1:8

Expected ">" but found "setup"
1  |  <script setup lang="ts">
   |          ^
2  |  import type { GridSize } from '../composables/sponsor-grid.js'
3  |  import type { Sponsor } from './VPSponsorsGrid.vue'

✖ building client + server bundles...
build error:
Error: Transform failed with 1 error:
D:/项目-我的/fighting-design/node_modules/.pnpm/vitepress@1.0.0-alpha.47_2r467mdhb7mblpaox4bg7fatdi/node_modules/vitepress/dist/client/theme-default/components/VP    at addChunk (node:internal/streams/readable:315:12)    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23) ELIFECYCLE  Command failed with exit code 1. ELIFECYCLE  Command failed with exit code 1.
PS D:\项目-我的\fighting-design>
```

## 错误代码 3

```shell
PS D:\项目-我的\fighting-design> pnpm build:docs

> fighting-design@ build:docs D:\项目-我的\fighting-design
> pnpm run -C docs build


> docs@ build D:\项目-我的\fighting-design\docs      
> vitepress build


  vitepress v1.0.0-alpha.47

⠙ building client + server bundles...[vite:esbuild] Transform failed with 1 error:
D:/项目-我的/fighting-design/docs/.vitepress/theme/components/vp-home.vue?vue&type=script&setup=true&name=VpHome&lang.ts:1:8: ERROR: Expected ">" but found "lang"
file: D:/项目-我的/fighting-design/docs/.vitepress/theme/components/vp-home.vue?vue&type=script&setup=true&name=VpHome&lang.ts:1:8

Expected ">" but found "lang"
1  |  <script lang="ts" setup name="VpHome">
   |          ^
2  |    import { watch, ref } from 'vue'
3  |    import { contributors } from '../../json/contributors.json'

✖ building client + server bundles...
build error:
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
 ELIFECYCLE  Command failed with exit code 1. ELIFECYCLE  Command failed with exit code 1.PS D:\项目-我的\fighting-design>
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by Tyh2001** [comment]
@brc-dd

**Comment by MarkusKeck** [comment]
@Tyh2001 Could you please try if the build still fails if you completely remove `vitest` from your project?

**Comment by Tyh2001** [comment]
> @Tyh2001 Could you please try if the build still fails if you completely remove `vitest` from your project?

Let me try

**Comment by Tyh2001** [comment]
> @Tyh2001 Could you please try if the build still fails if you completely remove `vitest` from your project?

zh-CN：
问题依然存在，和 vitest 应该没有关系吧？为什么要移除 vitest 呢？方法从何而来？

en-US：
The problem still exists. Should it have nothing to do with vitest? Why remove vitest? Where does the method come from?

@MarkusKeck

**Comment by brc-dd** [comment]
Just to be clear, this happens randomly? Like without touching the code even a bit? Happened anytime on the CI?

**Comment by theniceangel** [comment]
> Just to be clear, this happens randomly? Like without touching the code even a bit? Happened anytime on the CI?

The reason is LRU size is too small in `@vue/compiler-sfc`,
<img width="724" alt="image" src="https://user-images.githubusercontent.com/25956811/235358570-f319935f-6604-47ec-b2c3-520ac19cf649.png">
<img width="412" alt="image" src="https://user-images.githubusercontent.com/25956811/235358679-3dc03efe-adf8-4cc8-925a-8e573d9703b0.png">

Vitepress build will bundle a module for twice, one is `ssr: false`, the other is `ssr:true`, if `LRU` size is too small, we will get different descriptor for the same module.
<img width="987" alt="image" src="https://user-images.githubusercontent.com/25956811/235359602-41108408-f49f-47c2-b3a2-d31d0a7e2b2a.png">


 which caused get wrong cache from `ssrCache` and `clientCache` in `@vitejs/plugin-vue`
<img width="776" alt="image" src="https://user-images.githubusercontent.com/25956811/235359749-be148f40-9f60-46b7-955a-e26995c4835c.png">

**Comment by theniceangel** [comment]
@Tyh2001 @brc-dd yyx has exposed a option for this problem, It can be closed now

**Comment by Tyh2001** [comment]
不是很理解错误原因😂

> @Tyh2001 @brc-ddyyx已经暴露了这个问题的选项，现在可以关闭了

**Comment by brc-dd** [comment]
> yyx has exposed a option for this problem, It can be closed now

Don't we need changes in the vite plugin too? It's still unclear to me what exactly is the fix for the vitepress users? Do we need to just call `parseCache.max = 10000`?

**Comment by theniceangel** [comment]
> -ddyyx已经暴露了这个问题的选项，现在可以关闭了

Yeah, we can provide an option in `config.ts` to control the cache size used by '@vue/compiler-sfc', but at least, the user currently can fix the issue by themselves.

**Comment by zhr5422** [comment]
how this problem solved on earth？

**Comment by Tyh2001** [comment]
> how this problem solved on earth？

Give it a try to update the latest version
