### ISSUE TITLE
Dev server stops when there are errors in the config file

### ISSUE THREAD

**Issue by sitek94** [vuejs/vitepress#2041]
### Describe the bug

Development server stops working each time when you save the config file with a JavaScript error. 

For example, if I save the following file, the development server stops and I need to restart it.

![Screenshot 2023-03-06 at 20 17 42](https://user-images.githubusercontent.com/58401630/223208625-0349a73c-2350-4542-b0ce-1ed6cd52e242.png)

```
[ERROR] Expected "]" but found ":"

    www/.vitepress/config.ts:7:9:
      7 │     hello: ''
        │          ^
        ╵          ]

failed to load config from /Users/maciek/code/vitepress-demo/www/.vitepress/config.ts

failed to restart server. error:
Error: Build failed with 1 error:
www/.vitepress/config.ts:7:9: ERROR: Expected "]" but found ":"
    at failureErrorWithLog (/Users/maciek/code/vitepress-demo/node_modules/.pnpm/esbuild@0.16.17/node_modules/esbuild/lib/main.js:1604:15)
    at /Users/maciek/code/vitepress-demo/node_modules/.pnpm/esbuild@0.16.17/node_modules/esbuild/lib/main.js:1056:28
    at runOnEndCallbacks (/Users/maciek/code/vitepress-demo/node_modules/.pnpm/esbuild@0.16.17/node_modules/esbuild/lib/main.js:1476:61)
    at buildResponseToResult (/Users/maciek/code/vitepress-demo/node_modules/.pnpm/esbuild@0.16.17/node_modules/esbuild/lib/main.js:1054:7)
    at /Users/maciek/code/vitepress-demo/node_modules/.pnpm/esbuild@0.16.17/node_modules/esbuild/lib/main.js:1166:14
    at responseCallbacks.<computed> (/Users/maciek/code/vitepress-demo/node_modules/.pnpm/esbuild@0.16.17/node_modules/esbuild/lib/main.js:701:9)
    at handleIncomingPacket (/Users/maciek/code/vitepress-demo/node_modules/.pnpm/esbuild@0.16.17/node_modules/esbuild/lib/main.js:756:9)
    at Socket.readFromStdout (/Users/maciek/code/vitepress-demo/node_modules/.pnpm/esbuild@0.16.17/node_modules/esbuild/lib/main.js:677:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
```

### Reproduction

https://stackblitz.com/edit/vite-zsaqar?file=docs%2F.vitepress%2Fconfig.ts

1. Start development server `npm run docs:dev`
2. Paste the following code to `.vitepress/config.ts`
    ```ts
    import {defineConfig} from 'vitepress'
    
    export default defineConfig({
      title: 'My website',
      description: `My website description`,
      items: [
        hello: ''
      ],
    })
    ```
3. Save the file
4. Dev server should stop working, and you should see an error in the console

### Expected behavior

- development server shouldn't stop working
- latest valid config should be used
- maybe there should be an error overlay

### System Info

```shell
System:
  OS: macOS 13.2.1
  CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Memory: 198.12 MB / 32.00 GB
  Shell: 5.8.1 - /bin/zsh
Binaries:
  Node: 18.12.0 - ~/.nvm/versions/node/v18.12.0/bin/node
  Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.0/bin/yarn
  npm: 8.19.2 - ~/.nvm/versions/node/v18.12.0/bin/npm
Browsers:
  Brave Browser: 107.1.45.116
  Chrome: 110.0.5481.177
  Firefox: 110.0
  Safari: 16.3
npmPackages:
  vitepress: 1.0.0-alpha.49 => 1.0.0-alpha.49
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by sitek94** [comment]
Thank you @yyx990803! 

Btw. let me just say that this project is amazing and the design that we get out of the box is absolutely gorgeous!
