### ISSUE TITLE
[plugin:vite:import-analysis] Failed to resolve import

### ISSUE THREAD

**Issue by nroyliu** [vuejs/vitepress#2213]
### Describe the bug

When I initialize a new project and access it, it returns

[plugin:vite:import-analysis] Failed to resolve import "@vue/composition-api/dist/vue-composition-api.mjs" from "../node_modules/vue-demi/lib/index.mjs?v=2157b86a". Does the file exist?

### Reproduction

vitepress v1.0.0-alpha.65

┌   Welcome to VitePress! 
│
◇  Where should VitePress initialize the config?
│  ./docs
│
◇  Site title:
│  My Awesome Project
│
◇  Site description:
│  A VitePress Site
│
◇  Theme:
│  Default Theme
│
◇  Use TypeScript for config and theme files?
│  Yes
│
◇  Add VitePress npm scripts to package.json?
│  Yes
│
└  Done! Now run npm run docs:dev and start writing.

npm run docs:dev

> docs:dev
> vitepress dev docs

failed to start server. error:
Error: Failed to resolve vue/compiler-sfc.
@vitejs/plugin-vue requires vue (>=3.2.25) to be present in the dependency tree.
    at resolveCompiler (file:///Users/nroy/node_modules/@vitejs/plugin-vue/dist/index.mjs:12:11)
    at Context.buildStart (file:///Users/nroy/node_modules/@vitejs/plugin-vue/dist/index.mjs:2667:46)
    at hookParallel (file:///Users/nroy/node_modules/vite/dist/node/chunks/dep-79892de8.js:42977:47)
    at Object.buildStart (file:///Users/nroy/node_modules/vite/dist/node/chunks/dep-79892de8.js:43291:19)
    at file:///Users/nroy/node_modules/vite/dist/node/chunks/dep-79892de8.js:63012:29
    at initServer (file:///Users/nroy/node_modules/vite/dist/node/chunks/dep-79892de8.js:63019:11)
    at Server.httpServer.listen (file:///Users/nroy/node_modules/vite/dist/node/chunks/dep-79892de8.js:63027:23)
    at file:///Users/nroy/node_modules/vite/dist/node/chunks/dep-79892de8.js:53058:20
    at new Promise (<anonymous>)
    at httpServerStart (file:///Users/nroy/node_modules/vite/dist/node/chunks/dep-79892de8.js:53040:12)

im install new vue

> vitepress dev docs

  vitepress v1.0.0-alpha.65

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose

Failed to resolve import "@vue/composition-api/dist/vue-composition-api.mjs" from "../node_modules/vue-demi/lib/index.mjs?v=2157b86a". Does the file exist?
Failed to resolve import "@vue/composition-api/dist/vue-composition-api.mjs" from "../node_modules/vue-demi/lib/index.mjs?v=2157b86a". Does the file exist? (x2)
11:29:14 [vitepress] Internal server error: Failed to resolve import "@vue/composition-api/dist/vue-composition-api.mjs" from "../node_modules/vue-demi/lib/index.mjs?v=2157b86a". Does the file exist?
  Plugin: vite:import-analysis
  File: /Users/nroy/node_modules/vue-demi/lib/index.mjs?v=2157b86a:2:32
  1  |  import Vue from 'vue'
  2  |  import VueCompositionAPI from '@vue/composition-api/dist/vue-composition-api.mjs'
     |                                 ^
  3  |  
  4  |  function install(_vue) {
      at formatError (file:///Users/nroy/node_modules/vite/dist/node/chunks/dep-79892de8.js:43113:46)
      at TransformContext.error (file:///Users/nroy/node_modules/vite/dist/node/chunks/dep-79892de8.js:43109:19)
      at normalizeUrl (file:///Users/nroy/node_modules/vite/dist/node/chunks/dep-79892de8.js:41378:33)
      at async TransformContext.transform (file:///Users/nroy/node_modules/vite/dist/node/chunks/dep-79892de8.js:41512:47)
      at async Object.transform (file:///Users/nroy/node_modules/vite/dist/node/chunks/dep-79892de8.js:43387:30)
      at async loadAndTransform (file:///Users/nroy/node_modules/vite/dist/node/chunks/dep-79892de8.js:41105:29)

### Expected behavior

Unable to access normally

### System Info

```shell
System:
    OS: macOS 12.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 244.26 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 112.0.5615.49
    Safari: 15.6
```

### Additional context

<img width="1051" alt="image" src="https://user-images.githubusercontent.com/33707417/231934722-5d1521f4-52a2-471f-b74d-085d4a91eb5f.png">

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [x] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Not able to reproduce this. What's inside your `Frontend` directory in that screenshot? Does it has an old version of vue installed?

**Comment by nroyliu** [comment]
> Not able to reproduce this. What's inside your `Frontend` directory in that screenshot? Does it has an old version of vue installed?

Frontend is the directory where my terminal executes commands

**Comment by brc-dd** [comment]
There seems to be some issue with your setup. If `Frontend` is where you've installed vitepress, why is there a `node_modules` in your home directory (`/Users/nroy/`)? IG you've accidentally installed something at your home and that's causing vite to fail. Remove any package.json, lockfile or node_modules from  `/Users/nroy/`, it should work fine then.
