### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by YangguangZhou** [vuejs/vitepress#2227]
### Describe the bug

In some cases, even if the page has content, the 404 error is displayed.
This often happens when you open a page using a link.
![Screenshot_20230416-125428](https://user-images.githubusercontent.com/61733195/232270089-9e3c164f-a05f-4416-96c7-58fb9b8727c2.png)

### Reproduction

Use the link to open the page

### Expected behavior

Display content
But it says 404, sometimes there's something underneath it, sometimes there's nothing at all.

### System Info

```shell
Not yet available
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Share your code. There are hydration issues (you'll see errors on devtools' console).

**Comment by YangguangZhou** [comment]
```
framework.5dd80646.js:1  RangeError: Incorrect locale information provided
    at Date.toLocaleString (<anonymous>)
    at theme.a7bd2fed.js:7:37362
    at We (framework.5dd80646.js:1:12691)
    at xe (framework.5dd80646.js:1:12769)
    at Gn.c [as fn] (framework.5dd80646.js:1:18112)
    at Gn.run (framework.5dd80646.js:1:4049)
    at mn (framework.5dd80646.js:1:18751)
    at Po (framework.5dd80646.js:1:17616)
    at theme.a7bd2fed.js:7:37339
    at framework.5dd80646.js:1:24330
bo @ framework.5dd80646.js:1
$t @ framework.5dd80646.js:1
We @ framework.5dd80646.js:1
xe @ framework.5dd80646.js:1
c @ framework.5dd80646.js:1
run @ framework.5dd80646.js:1
mn @ framework.5dd80646.js:1
Po @ framework.5dd80646.js:1
(anonymous) @ theme.a7bd2fed.js:7
(anonymous) @ framework.5dd80646.js:1
We @ framework.5dd80646.js:1
xe @ framework.5dd80646.js:1
t.__weh.t.__weh @ framework.5dd80646.js:1
nn @ framework.5dd80646.js:1
d @ framework.5dd80646.js:1
mount @ framework.5dd80646.js:1
Kc.t.mount @ framework.5dd80646.js:1
(anonymous) @ app.9043b327.js:1
framework.5dd80646.js:1  Hydration completed but contains mismatches.
d @ framework.5dd80646.js:1
mount @ framework.5dd80646.js:1
Kc.t.mount @ framework.5dd80646.js:1
(anonymous) @ app.9043b327.js:1
um.jerryz.com.cn/umami.js:1 
        
        
        Failed to load resource: the server responded with a status of 503 ()
apks:1 
        
        
        Failed to load resource: the server responded with a status of 404 ()
(index):1957  crbug/1173575, non-JS module files deprecated.
(anonymous) @ (index):1957
```

**Comment by YangguangZhou** [comment]
@brc-dd

**Comment by brc-dd** [comment]
Seems like you've specified invalid `lang` in your config. Shouldn't happen now though, we are no longer using `toLocaleString`.
