### ISSUE TITLE
[localSearch] Build in `GitLab ci-cd` fails.

### ISSUE THREAD

**Issue by mllull** [vuejs/vitepress#2250]
### Describe the bug

As the title says, the build from a `GitLab ci/cd` job is failing when implementing the new *local search* feature.

Here is the failure log:

```
$ vitepress build docs
  vitepress v1.0.0-alpha.71
- building client + server bundles...
[vitepress:local-search] Could not load /@localSearchIndex (imported by node_modules/vitepress/dist/client/theme-default/components/VPLocalSearchBox.vue?vue&type=script&setup=true&lang.ts): section.titles.at is not a function
✖ building client + server bundles...
build error:
TypeError: Could not load /@localSearchIndex (imported by node_modules/vitepress/dist/client/theme-default/components/VPLocalSearchBox.vue?vue&type=script&setup=true&lang.ts): section.titles.at is not a function
    at file:///home/gitlab-runner/builds/wV6hzoRZ/0/xxxxxxxxxxxxxxxxxx/node_modules/vitepress/dist/node/serve-8eb4e7c6.js:36767:35
    at Array.map (<anonymous>)
    at file:///home/gitlab-runner/builds/wV6hzoRZ/0/xxxxxxxxxxxxxxxxxx/node_modules/vitepress/dist/node/serve-8eb4e7c6.js:36764:23
    at async Promise.all (index 0)
    at async indexAllFiles (file:///home/gitlab-runner/builds/wV6hzoRZ/0/xxxxxxxxxxxxxxxxxx/node_modules/vitepress/dist/node/serve-8eb4e7c6.js:36751:5)
    at async scanForBuild (file:///home/gitlab-runner/builds/wV6hzoRZ/0/xxxxxxxxxxxxxxxxxx/node_modules/vitepress/dist/node/serve-8eb4e7c6.js:36781:5)
    at async Object.load (file:///home/gitlab-runner/builds/wV6hzoRZ/0/xxxxxxxxxxxxxxxxxx/node_modules/vitepress/dist/node/serve-8eb4e7c6.js:36809:11)
    at async PluginDriver.hookFirstAndGetPlugin (file:///home/gitlab-runner/builds/wV6hzoRZ/0/xxxxxxxxxxxxxxxxxx/node_modules/rollup/dist/es/shared/node-entry.js:24249:28)
    at async file:///home/gitlab-runner/builds/wV6hzoRZ/0/xxxxxxxxxxxxxxxxxx/node_modules/rollup/dist/es/shared/node-entry.js:23530:75
    at async Queue.work (file:///home/gitlab-runner/builds/wV6hzoRZ/0/xxxxxxxxxxxxxxxxxx/node_modules/rollup/dist/es/shared/node-entry.js:24459:32)
error Command failed with exit code 1.
```
It seems that the error is in this line:

https://github.com/vuejs/vitepress/blob/e37e5cb45a6c3507b906b9955897ce4e84adf500/src/node/plugins/localSearchPlugin.ts#L126

Maybe a problem related of generated docpages title?

### Reproduction

- Upload Vitepress docs to a Gitlab
- Install all dependecies with `yarn install`.
- Execute a CI/CD of `yarn docs:build`.

### Expected behavior

Docs build as expected like in my own system (Yes, in my local machine all build's as expected, no error thrown).

### System Info

```shell
- Gitlab version: `v13.0.14`
- Yarn version: `v1.22.18`

(Sorry, I don't have ssh access to this machine to get more info).
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
can you check the node.js version being used there? You're probably using some version older than v16.8.0

**Comment by mllull** [comment]
@brc-dd ouch! yes, we use `v14.19.1` :sweat: 

Okay, I will try to build docs on my machine and then deploy it.

Thanks man! :)
