### ISSUE TITLE
Vitepress cannot build custom elements (web components)

### ISSUE THREAD

**Issue by aleksey-hoffman** [vuejs/vitepress#2367]
### Describe the bug

If docs contain a custom element (web component), the `npm run docs:build` command throws error:

```sh
> test-docs@1.0.0 docs:build
> vitepress build docs

  vitepress v1.0.0-alpha.75

✓ building client + server bundles...
✖ rendering pages...
build error:
ReferenceError: customElements is not defined
    at T (file:///C:/test/test-docs/docs/.vitepress/.temp/app.js:4297:3)
    at Object.enhanceApp (file:///C:/test/test-docs/docs/.vitepress/.temp/app.js:4307:5)
    at createApp (file:///C:/test/test-docs/docs/.vitepress/.temp/app.js:4576:17)
    at render (file:///C:/test/test-docs/docs/.vitepress/.temp/app.js:4616:33)
    at renderPage (file:///C:/test/test-docs/node_modules/vitepress/dist/node/serve-998e6cdd.js:41231:25)
    at file:///C:/test/test-docs/node_modules/vitepress/dist/node/serve-998e6cdd.js:41768:21
    at Array.map (<anonymous>)
    at build (file:///C:/test/test-docs/node_modules/vitepress/dist/node/serve-998e6cdd.js:41767:94)
```

### Reproduction

1. Create a custom element `Test.ce.vue` with Vue 3.2 `defineCustomElement` function.
2. Define it in its `index.js` file

```
import { defineCustomElement } from "vue";
import TestComponent from './TestComponent.ce.vue'

const TestComponentCE = defineCustomElement(TestComponent)

export function defineTestComponentCE() {
  if (!customElements.get('test-component')) {
    customElements.define('test-component', TestComponentCE);
  }
}

export { TestComponentCE }
```

3. Use the custom element on a Vitepress page

`docs/.vitepress/theme/index.ts`
```js
// https://vitepress.dev/guide/custom-theme
import { h } from 'vue'
import Theme from 'vitepress/theme'
import './style.css'x
import {defineTestComponentCE} from 'test-ui';

export default {
  ...Theme,
  Layout: () => {
    return h(Theme.Layout, null, {
      // https://vitepress.dev/guide/extending-default-theme#layout-slots
    })
  },
  enhanceApp({ app, router, siteData }) {
    defineTestComponentCE()
  }
}
```

`some md page`
```
<test-component></test-component>
```

### Expected behavior

Custom elements to work in Vitepress

### System Info

```sh
System:
    OS: Windows 10 10.0.22621
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1702.0), Chromium (113.0.1774.35)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vitepress: ^1.0.0-alpha.75 => 1.0.0-alpha.75
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by Ttou** [comment]
same issue

```sh
> vitepress build docs

  vitepress v1.0.0-beta.1

✓ building client + server bundles...
⠙ rendering pages...ReferenceError: customElements is not defined
```

**Comment by brc-dd** [comment]
You need to wrap that with `if (!import.meta.env.SSR) { ... }` or `if (inBrowser) { ... }`

**Comment by aleksey-hoffman** [comment]
@brc-dd thanks for the info!
