### ISSUE TITLE
Build fails because a requested module is a CommonJS module, even though it's not (kinda)

### ISSUE THREAD

**Issue by simonwep** [vuejs/vitepress#2411]
### Describe the bug

For some reason vitepress's module resolution doesn't pick up re-exported things in esm modules. This may affect more than just the dependency I'm having problems with, but in this case it's @popperjs/core aka. [floating ui](https://github.com/floating-ui/floating-ui) - when importing their constant `placements` `vitepress build` throws the following error:

```
vitepress v1.0.0-beta.1

✓ building client + server bundles...
⠋ rendering pages...(node:238582) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
file:///xxx/.vitepress/.temp/markdown-examples.md.js:3
import { createPopper, placements } from "@popperjs/core";
                       ^^^^^^^^^^
SyntaxError: Named export 'placements' not found. The requested module '@popperjs/core' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@popperjs/core';
const { createPopper, placements } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadPage (file:///xxx/.vitepress/.temp/Content.2e4fdb81.js:210:18)
    at async Object.go (file:///xxx/.vitepress/.temp/Content.2e4fdb81.js:202:5)
    at async render (file:///xxx/.vitepress/.temp/app.js:4561:3)
    at async renderPage (file:///xxx/node_modules/vitepress/dist/node/serve-d5608de4.js:41246:19)
    at async Promise.all (index 3)
    at async build (file:///xxx/node_modules/vitepress/dist/node/serve-d5608de4.js:41781:7)
✖ rendering pages...
build error:
file:///xxx/.vitepress/.temp/markdown-examples.md.js:3
import { createPopper, placements } from "@popperjs/core";
                       ^^^^^^^^^^
SyntaxError: Named export 'placements' not found. The requested module '@popperjs/core' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@popperjs/core';
const { createPopper, placements } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadPage (file:///xxx/.vitepress/.temp/Content.2e4fdb81.js:210:18)
    at async Object.go (file:///xxx/.vitepress/.temp/Content.2e4fdb81.js:202:5)
    at async render (file:///xxx/.vitepress/.temp/app.js:4561:3)
    at async renderPage (file:///xxx/node_modules/vitepress/dist/node/serve-d5608de4.js:41246:19)
    at async Promise.all (index 3)
    at async build (file:///xxx/node_modules/vitepress/dist/node/serve-d5608de4.js:41781:7)

Process finished with exit code 1
```

The dependency is not marked as "native" esm module (via `"type": "module"` in the `package.json`) but provides both cjs, esm and umd bundles. 

The import path looks like the following: `@popperjs/core  -> @popperjs/core/dist/esm/index.js -> @popperjs/core/dist/esm/enums.js `, you can check it out in the `node_modules` folder.

### Reproduction

Reproduced [here](https://stackblitz.com/edit/vite-k6uusu?file=package.json,docs%2Fexample.md), in actuality this is a dependency of another dependency, where it wasn't possible to import it if `"type": "module"` wasn't specified in the `package.json`. So it seems like there is a problem with esm modules that support esm, but don't have `"type": "module"` set in their `package.json`.

### Expected behavior

It should import the constant correctly.

### System Info

```sh
System:
    OS: Linux 5.19 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 4.73 GB / 31.22 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    npm: 9.6.6 - /usr/local/bin/npm
  Browsers:
    Chrome: 113.0.5672.126
  npmPackages:
    vitepress: ^1.0.0-beta.1 => 1.0.0-beta.1
```

### Additional context

Maybe related to #1232 and [#10822](https://github.com/nuxt/nuxt/discussions/10822)

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Add this to your config:

```ts
  vite: {
    ssr: {
      noExternal: ['@popperjs/core']
    }
  }
```
