### ISSUE TITLE
[plugin:vite:vue] Element is missing end tag.

### ISSUE THREAD

**Issue by xingkongdiyiren** [vuejs/vitepress#2460]
### Describe the bug

36 | class Notepad<K,V>{
37 | private K key ;
38 | private V value ;
| ^
39 | public K getKey(){
40 | return this.key ;
at createCompilerError (D:\vscodeproject\myblog\node_modules@vue\compiler-core\dist\compiler-core.cjs.js:18:17)
at emitError (D:\vscodeproject\myblog\node_modules@vue\compiler-core\dist\compiler-core.cjs.js:1487:5)
at parseElement (D:\vscodeproject\myblog\node_modules@vue\compiler-core\dist\compiler-core.cjs.js:1031:5)
at parseChildren (D:\vscodeproject\myblog\node_modules@vue\compiler-core\dist\compiler-core.cjs.js:844:18)
at parseElement (D:\vscodeproject\myblog\node_modules@vue\compiler-core\dist\compiler-core.cjs.js:1008:20)
at parseChildren (D:\vscodeproject\myblog\node_modules@vue\compiler-core\dist\compiler-core.cjs.js:844:18)
at parseElement (D:\vscodeproject\myblog\node_modules@vue\compiler-core\dist\compiler-core.cjs.js:1008:20)
at parseChildren (D:\vscodeproject\myblog\node_modules@vue\compiler-core\dist\compiler-core.cjs.js:844:18)
at parseElement (D:\vscodeproject\myblog\node_modules@vue\compiler-core\dist\compiler-core.cjs.js:1008:20)
at parseChildren (D:\vscodeproject\myblog\node_modules@vue\compiler-core\dist\compiler-core.cjs.js:844:18
Click outside or fix the code to dismiss.
You can also disable this overlay by setting server.hmr.overlay to false in vite.config.js.

### Reproduction

Question: 1, why would he scan the code in my code block, shouldn't he filter himself, I use markdown syntax, specifically for java

2, I also found a very strange problem, why he does not support the external link to visit, is my picture is not local, is the website he can not visit

3, if you have a good solution, please give me a solution, thank you

### Expected behavior

Question: 1, why would he scan the code in my code block, shouldn't he filter himself, I use markdown syntax, specifically for java

2, I also found a very strange problem, why he does not support the external link to visit, is my picture is not local, is the website he can not visit

3, if you have a good solution, please give me a solution, thank you

### System Info

```sh
Question: 1, why would he scan the code in my code block, shouldn't he filter himself, I use markdown syntax, specifically for java

2, I also found a very strange problem, why he does not support the external link to visit, is my picture is not local, is the website he can not visit

3, if you have a good solution, please give me a solution, thank you
```

### Additional context

Question: 1, why would he scan the code in my code block, shouldn't he filter himself, I use markdown syntax, specifically for java

2, I also found a very strange problem, why he does not support the external link to visit, is my picture is not local, is the website he can not visit

3, if you have a good solution, please give me a solution, thank you

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by DreierF** [comment]
The reproduction section in the issue template is there for a reason. Please try to build a repository/Stackblitz link etc. with a minimal setup to reproduce the error or at least share the markdown that produces the error.

**Comment by onlypai** [comment]
Did you solve it？

**Comment by brc-dd** [comment]
You have some malformed markdown content. Please fill out the issue form completely instead of just copy pasting the same thing in all sections.
