### ISSUE TITLE
Document is Not defined while building

### ISSUE THREAD

**Issue by arunkaruppasamy** [vuejs/vitepress#2633]
### Describe the bug

Actuall I am using one pakage in vue component and I am importing my vue component in vitepress then when I am trying to build I am getting this error 

(!) Some chunks are larger than 500 kBs after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
✓ building client + server bundles...
⠙ rendering pages...ReferenceError: document is not defined
    at enableDismissTrigger (C:\ArunSk\aswin\node_modules\bootstrap\dist\js\bootstrap.js:826:21)
    at C:\ArunSk\aswin\node_modules\bootstrap\dist\js\bootstrap.js:908:3
    at C:\ArunSk\aswin\node_modules\bootstrap\dist\js\bootstrap.js:7:83
    at Object.<anonymous> (C:\ArunSk\aswin\node_modules\bootstrap\dist\js\bootstrap.js:10:3)    
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:190:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
✖ rendering pages...
build error:
ReferenceError: document is not defined
    at enableDismissTrigger (C:\ArunSk\aswin\node_modules\bootstrap\dist\js\bootstrap.js:826:21)
    at C:\ArunSk\aswin\node_modules\bootstrap\dist\js\bootstrap.js:908:3
    at C:\ArunSk\aswin\node_modules\bootstrap\dist\js\bootstrap.js:7:83
    at Object.<anonymous> (C:\ArunSk\aswin\node_modules\bootstrap\dist\js\bootstrap.js:10:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:190:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
PS C:\ArunSk\aswin>

if I comment that package and try to build it's building fine and I have added config.ts also 

import { UserConfig } from 'vite';

const config: UserConfig = {
  // Other Vite configuration options...
  build: {
    rollupOptions: {
      external: /^bootstrap($|\/)/,
    },
    ssr: false,
  },
};

export default config;

my package.json

{
  "scripts": {
    "docs:dev": "vitepress dev docs",
    "docs:build": "vitepress build docs",
    "docs:preview": "vitepress preview docs"
  },
  "peerDependencies": {
    "markdown-it-container": "^3.0.0",
    "vitepress": "*",
    "vue": "^3.2.0"
  },
  "devDependencies": {
    "@types/markdown-it": "^12.2.3",
    "@types/markdown-it-container": "^2.0.5",
    "@types/node": "^18.16.3",
    "lint-staged": "^13.2.2",
    "vue": "^3.2.38"
  },
  "dependencies": {
    "bootstrap": "^5.2.0",
    "fire-stars": "^0.0.1",
    "markdown-it": "^13.0.1",
    "markdown-it-container": "^3.0.0",
    "sass": "^1.63.6",
    "vitepress": "*",
    "vue": "^3.2.0"
  }
}

### Reproduction

Actuall I am using one pakage in vue component and I am importing my vue component in vitepress then when I am trying to build I am getting this error 

(!) Some chunks are larger than 500 kBs after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
✓ building client + server bundles...
⠙ rendering pages...ReferenceError: document is not defined
    at enableDismissTrigger (C:\ArunSk\aswin\node_modules\bootstrap\dist\js\bootstrap.js:826:21)
    at C:\ArunSk\aswin\node_modules\bootstrap\dist\js\bootstrap.js:908:3
    at C:\ArunSk\aswin\node_modules\bootstrap\dist\js\bootstrap.js:7:83
    at Object.<anonymous> (C:\ArunSk\aswin\node_modules\bootstrap\dist\js\bootstrap.js:10:3)    
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:190:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
✖ rendering pages...
build error:
ReferenceError: document is not defined
    at enableDismissTrigger (C:\ArunSk\aswin\node_modules\bootstrap\dist\js\bootstrap.js:826:21)
    at C:\ArunSk\aswin\node_modules\bootstrap\dist\js\bootstrap.js:908:3
    at C:\ArunSk\aswin\node_modules\bootstrap\dist\js\bootstrap.js:7:83
    at Object.<anonymous> (C:\ArunSk\aswin\node_modules\bootstrap\dist\js\bootstrap.js:10:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:190:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
PS C:\ArunSk\aswin>

if I comment that package and try to build it's building fine and I have added config.ts also 

import { UserConfig } from 'vite';

const config: UserConfig = {
  // Other Vite configuration options...
  build: {
    rollupOptions: {
      external: /^bootstrap($|\/)/,
    },
    ssr: false,
  },
};

export default config;

my package.json

{
  "scripts": {
    "docs:dev": "vitepress dev docs",
    "docs:build": "vitepress build docs",
    "docs:preview": "vitepress preview docs"
  },
  "peerDependencies": {
    "markdown-it-container": "^3.0.0",
    "vitepress": "*",
    "vue": "^3.2.0"
  },
  "devDependencies": {
    "@types/markdown-it": "^12.2.3",
    "@types/markdown-it-container": "^2.0.5",
    "@types/node": "^18.16.3",
    "lint-staged": "^13.2.2",
    "vue": "^3.2.38"
  },
  "dependencies": {
    "bootstrap": "^5.2.0",
    "fire-stars": "^0.0.1",
    "markdown-it": "^13.0.1",
    "markdown-it-container": "^3.0.0",
    "sass": "^1.63.6",
    "vitepress": "*",
    "vue": "^3.2.0"
  }
}

### Expected behavior

Build Succesful

### System Info

```sh
{
  "scripts": {
    "docs:dev": "vitepress dev docs",
    "docs:build": "vitepress build docs",
    "docs:preview": "vitepress preview docs"
  },
  "peerDependencies": {
    "markdown-it-container": "^3.0.0",
    "vitepress": "*",
    "vue": "^3.2.0"
  },
  "devDependencies": {
    "@types/markdown-it": "^12.2.3",
    "@types/markdown-it-container": "^2.0.5",
    "@types/node": "^18.16.3",
    "lint-staged": "^13.2.2",
    "vue": "^3.2.38"
  },
  "dependencies": {
    "bootstrap": "^5.2.0",
    "fire-stars": "^0.0.1",
    "markdown-it": "^13.0.1",
    "markdown-it-container": "^3.0.0",
    "sass": "^1.63.6",
    "vitepress": "*",
    "vue": "^3.2.0"
  }
}
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
https://vitepress.dev/guide/ssr-compat#ssr-compatibility

**Comment by arunkaruppasamy** [comment]
Hi @brc-dd ,
So Do I have to add that in my vue component
Where I have to point

**Comment by brc-dd** [comment]
Wrap your vue component with ClientOnly or import that package dynamically in an onMounted hook.

**Comment by arunkaruppasamy** [comment]
it's Building fine now, 
Thank you 😃 👍

**Comment by arunkaruppasamy** [comment]
// vite.config.ts
import { defineConfig } from 'vite';
import { UserConfig } from 'vite';

const config: UserConfig = {
  build: {
    rollupOptions: {
      external: ['fire-stars'], // Add external module
      output: {
        globals: {
          'fire-stars': 'fireStars', // Provide global variable name for the external module
        },
      },
    },
  },
};

export default defineConfig(config);


so is it posiible with vite config ts file ?
