### ISSUE TITLE
Can't resolve relative link in public directory from dynamic route's index.md

### ISSUE THREAD

**Issue by Pandapip1** [vuejs/vitepress#2647]
### Describe the bug

I have a dynamic route with an index.md (not sure if the index.md part is relevant, but I'm including it anyway), and a bunch of static assets in the public directory. When I try to make a relative link/image like so:

```
![test](./img/test.png)
```

it produces a build error.

### Reproduction

I have the following layout:

```
.vitepress
     config.json
src
    [test]
        index.md
        index.paths.js
    public
        1
            img
                test.png
```

What is effectively `src/1/index.md` ends up containing the following markdown:

```
![test](./img/test.png)
```

Resulting in the following build error:

```
Could not resolve "./img/test.png" from "src/1/index.md"
file: C:/Users/<me>/source/repos/<repo>/src/1/index.md
✖ building client + server bundles...
build error:
RollupError: Could not resolve "./img/test.png" from "src/1/index.md"
    at error (file:///C:/Users/<me>/source/repos/<repo>/node_modules/rollup/dist/es/shared/node-entry.js:2245:30)
    at ModuleLoader.handleInvalidResolvedId (file:///C:/Users/<me>/source/repos/<repo>/node_modules/rollup/dist/es/shared/node-entry.js:24654:24)
    at file:///C:/Users/<me>/source/repos/<repo>/node_modules/rollup/dist/es/shared/node-entry.js:24616:26
```

### Expected behavior

It builds with no errors.

### System Info

```sh
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 5700U with Radeon Graphics
    Memory: 1.06 GB / 9.85 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.8.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.5.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22621.1992.0), Chromium (114.0.1823.82)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vitepress: ^1.0.0-beta.5 => 1.0.0-beta.5
```
```


### Additional context

_No response_

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by Pandapip1** [comment]
Never mind, this was me being an idiot and not understanding how the public directory worked.
