### ISSUE TITLE
Could not load /@localSearchIndex

### ISSUE THREAD

**Issue by dudedigital** [vuejs/vitepress#2687]
After adding search `provider: 'local'` to my config, it ran without issue locally. When I tried to deploy it, it failed during build. Perhaps this is a permission issue and/or a note/tip the documentation is missing?
```
> vitepress build docs

  vitepress v1.0.0-beta.6

- building client + server bundles...
[vitepress:local-search] Could not load /@localSearchIndex (imported by node_modules/vitepress/dist/client/theme-default/components/VPLocalSearchBox.vue?vue&type=script&setup=true&lang.ts): section.titles.at is not a function
✖ building client + server bundles...
build error:
TypeError: Could not load /@localSearchIndex (imported by node_modules/vitepress/dist/client/theme-default/components/VPLocalSearchBox.vue?vue&type=script&setup=true&lang.ts): section.titles.at is not a function
    at file:///home/forge/[removed]/node_modules/vitepress/dist/node/serve-98a6c925.js:36912:35
    at Array.map (<anonymous>)
    at file:///home/forge/[removed]/node_modules/vitepress/dist/node/serve-98a6c925.js:36909:23
    at Array.map (<anonymous>)
    at indexAllFiles (file:///home/forge/[removed]/node_modules/vitepress/dist/node/serve-98a6c925.js:36897:53)
    at scanForBuild (file:///home/forge/[removed]/node_modules/vitepress/dist/node/serve-98a6c925.js:36926:11)
    at Object.load (file:///home/forge/[removed]/node_modules/vitepress/dist/node/serve-98a6c925.js:36955:17)
    at file:///home/forge/[removed]/node_modules/rollup/dist/es/shared/node-entry.js:25336:40
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async PluginDriver.hookFirstAndGetPlugin (file:///home/forge/[removed]/node_modules/rollup/dist/es/shared/node-entry.js:25236:28)
```

**Comment by brc-dd** [comment]
Update your node version to v16 or above.
