### ISSUE TITLE
[plugin:vite:vue] Element is missing end tag.

### ISSUE THREAD

**Issue by onlypai** [vuejs/vitepress#2707]
### Describe the bug

[plugin:vite:vue] Element is missing end tag.
C:/..../vitepress/docs/react/index.md:4684:30
4682|  import { makeAutoObservable } from "mobx"
4683|  
4684|  function createDoubler(value) {
   |                                                     ^
4685|    return makeAutoObservable({
4686|      value,
    at createCompilerError (C:\...\vitepress\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:18:17)
    at emitError (C:\...\vitepress\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:1487:5)
    at parseElement (C:\...\vitepress\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:1031:5)
    at parseChildren (C:\...\vitepress\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:844:18)
    at parseElement (C:\...\vitepress\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:1008:20)
    at parseChildren (C:\...\vitepress\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:844:18)
    at parseElement (C:\...\vitepress\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:1008:20)
    at parseChildren (C:\...\vitepress\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:844:18)
    at parseElement (C:\...\vitepress\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:1008:20)
    at parseChildren (C:\...\vitepress\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:844:18
Click outside, press Esc key, or fix the code to dismiss.
You can also disable this overlay by setting server.hmr.overlay to false in vite.config.js.

### Reproduction

title: react
link: /react/index

After connecting the md file with link, click to jump to the page corresponding to the md file, and the error occurs. Is the md file written non-standard?

### Expected behavior

How can I fix this problem？

### System Info

```sh
browsers
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Can you share a reproducible example using https://vitepress.new

**Comment by onlypai** [comment]
![image](https://github.com/vuejs/vitepress/assets/68647050/e4e55e69-ff4b-4424-a902-ccfd761dec51)

**Comment by onlypai** [comment]
An error message is displayed when you jump to the page corresponding to the md file

**Comment by brc-dd** [comment]
Can you share the link as well? Can't tell what's wrong by just that screenshot.

**Comment by onlypai** [comment]
https://stackblitz.com/edit/vite-mtdapu?file=docs%2Findex.md

I'm sorry I haven't used stackblitz before！

**Comment by onlypai** [comment]
![image](https://github.com/vuejs/vitepress/assets/68647050/a7f45c58-f6c1-4fba-905a-0c7213871386)

There seems to be a problem here，But the location of the error was wrong，It's my fault！
