### ISSUE TITLE
[ERROR] "vitepress" resolved to an ESM file.

### ISSUE THREAD

**Issue by Peque** [vuejs/vitepress#2754]
### Describe the bug

Running `npm run docs:build` results in an error when using latest (`-rc.2`) packaged version:

```
$ npm run docs:build

> docs:build
> vitepress build docs


  vitepress v1.0.0-rc.3

✘ [ERROR] "vitepress" resolved to an ESM file. ESM file cannot be loaded by `require`. See http://vitejs.dev/guide/troubleshooting.html#this-package-is-esm-only for more details. [plugin externalize-deps]

    node_modules/esbuild/lib/main.js:1373:27:
      1373 │         let result = await callback({
           ╵                            ^

    at file:///tmp/vpress/node_modules/vite/dist/node/chunks/dep-df561101.js:66190:35
    at requestCallbacks.on-resolve (/tmp/vpress/node_modules/esbuild/lib/main.js:1373:28)
    at handleRequest (/tmp/vpress/node_modules/esbuild/lib/main.js:729:19)
    at handleIncomingPacket (/tmp/vpress/node_modules/esbuild/lib/main.js:755:7)
    at Socket.readFromStdout (/tmp/vpress/node_modules/esbuild/lib/main.js:679:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)

  This error came from the "onResolve" callback registered here:

    node_modules/esbuild/lib/main.js:1292:20:
      1292 │       let promise = setup({
           ╵                     ^

    at setup (file:///tmp/vpress/node_modules/vite/dist/node/chunks/dep-df561101.js:66158:27)
    at handlePlugins (/tmp/vpress/node_modules/esbuild/lib/main.js:1292:21)
    at buildOrContextImpl (/tmp/vpress/node_modules/esbuild/lib/main.js:978:5)
    at Object.buildOrContext (/tmp/vpress/node_modules/esbuild/lib/main.js:786:5)
    at /tmp/vpress/node_modules/esbuild/lib/main.js:2177:15
    at new Promise (<anonymous>)
    at Object.build (/tmp/vpress/node_modules/esbuild/lib/main.js:2176:25)
    at build (/tmp/vpress/node_modules/esbuild/lib/main.js:2025:51)
    at bundleConfigFile (file:///tmp/vpress/node_modules/vite/dist/node/chunks/dep-df561101.js:66109:26)

  The plugin "externalize-deps" was triggered by this import

    docs/.vitepress/config.ts:1:278:
      1 │ ...import_meta_url = "file:///tmp/vpress/docs/.vitepress/config.ts";import { defineConfig } from 'vitepress'
        ╵                                                                                                  ~~~~~~~~~~~

failed to load config from /tmp/vpress/docs/.vitepress/config.ts
build error:
Error: Build failed with 1 error:
node_modules/esbuild/lib/main.js:1373:27: ERROR: [plugin: externalize-deps] "vitepress" resolved to an ESM file. ESM file cannot be loaded by `require`. See http://vitejs.dev/guide/troubleshooting.html#this-package-is-esm-only for more details.
    at failureErrorWithLog (/tmp/vpress/node_modules/esbuild/lib/main.js:1649:15)
    at /tmp/vpress/node_modules/esbuild/lib/main.js:1058:25
    at runOnEndCallbacks (/tmp/vpress/node_modules/esbuild/lib/main.js:1484:45)
    at buildResponseToResult (/tmp/vpress/node_modules/esbuild/lib/main.js:1056:7)
    at /tmp/vpress/node_modules/esbuild/lib/main.js:1085:16
    at responseCallbacks.<computed> (/tmp/vpress/node_modules/esbuild/lib/main.js:703:9)
    at handleIncomingPacket (/tmp/vpress/node_modules/esbuild/lib/main.js:762:9)
    at Socket.readFromStdout (/tmp/vpress/node_modules/esbuild/lib/main.js:679:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
```

### Reproduction

```
mkdir vpress
cd vpress
npm install -D vitepress
npx vitepress init
#│  ./docs
#│  My Awesome Project
#│  A VitePress Site
#│  Default Theme
#│  Yes
#│  Yes
npm run docs:build
```

### Expected behavior

Build runs successfully.

### System Info

```sh
System:
    OS: Linux 6.4 Fedora Linux 38.20230806.0 (Silverblue)
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz
    Memory: 8.91 GB / 15.25 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
  npmPackages:
    vitepress: ^1.0.0-rc.3 => 1.0.0-rc.3
```
```


### Additional context

_No response_

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
The resolution mentioned there or at http://vitejs.dev/guide/troubleshooting.html#this-package-is-esm-only  will work for you.

<img width="766" alt="image" src="https://github.com/vuejs/vitepress/assets/40380293/727af9bb-5b46-48f5-a223-8b4955ed9108">

I'll update the init command to prompt if user wants to add `"type": "module"` to their package.json or have the files as `.mjs`/`.mts`.
