### ISSUE TITLE
build error: TypeError: Intl.Segmenter is not a constructor

### ISSUE THREAD

**Issue by MonkeySheeps** [vuejs/vitepress#2793]
### Describe the bug

Execute command npm run docs:build and throw an exception: build error:
TypeError: Intl.Segmenter is not a constructor

### Reproduction

1. yarn init
2. yarn add --dev vitepress
3. package.json add  scripts  "docs:dev": "vitepress dev docs", "docs:build": "vitepress build docs", "docs:serve": "vitepress serve docs"
4. add .vitepress/config.js 
5. add docs/index.md
6. yarn docs:build

### Expected behavior

yarn docs:build 

### System Info

```sh
build error:
TypeError: Intl.Segmenter is not a constructor
    at stringWidth (file:///E:/Study/test/node_modules/vitepress/dist/node/serve-3dd2c315.js:47581:37)
    at Ora.#updateLineCount (file:///E:/Study/test/node_modules/vitepress/dist/node/serve-3dd2c315.js:48445:45)  
    at Ora.set text [as text] (file:///E:/Study/test/node_modules/vitepress/dist/node/serve-3dd2c315.js:48388:24)
    at new Ora (file:///E:/Study/test/node_modules/vitepress/dist/node/serve-3dd2c315.js:48307:13)
    at ora (file:///E:/Study/test/node_modules/vitepress/dist/node/serve-3dd2c315.js:48625:9)
    at task (file:///E:/Study/test/node_modules/vitepress/dist/node/serve-3dd2c315.js:48631:19)
    at bundle (file:///E:/Study/test/node_modules/vitepress/dist/node/serve-3dd2c315.js:48764:9)
    at build (file:///E:/Study/test/node_modules/vitepress/dist/node/serve-3dd2c315.js:52843:65)
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by kiaking** [comment]
Please provide reproduction repo. We have no idea what did you put in `index.md` or `config.js` 🤔
