### ISSUE TITLE
md plugin is imported using require and it seems that import cannot be used.

### ISSUE THREAD

**Issue by you-hengh** [vuejs/vitepress#2805]
### Describe the bug

I added two markdown plugins to my Vitepress, which are [markdown-it-footnote](https://github.com/markdown-it/markdown-it-footnote) and [markdown-it-task-checkbox](https://github.com/linsir/markdown-it-task-checkbox).

The imported code is located at `docs/.vitepress/config.ts`.

```ts
import { defineConfig } from 'vitepress'
import nav from '../nav'
import sidebar from '../sidebar'
const footnote = require('markdown-it-footnote')
const taskLists = require('markdown-it-task-checkbox')
```

However, it was working normally in vitepress 1.0.0 beta5, but in vitepress 1.0.0-rc.4, `pnpm dev` is no longer working properly.

I have checked the documentation for these two plugins, but neither of them has informed me how to use 'import' to import. It seems that importing with 'import' is not supported?

I don't know how to solve this problem, and I hope to get some help. Thank you very much!

### Reproduction

null

### Expected behavior

I hope Vitepress can run normally.

### System Info

```sh
System:
    OS: macOS 13.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 7.17 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/Library/pnpm/node
    npm: 9.5.1 - ~/Library/pnpm/npm
    pnpm: 8.6.3 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 115.0.5790.170
    Safari: 16.6
  npmPackages:
    vitepress: 1.0.0-rc.4 => 1.0.0-rc.4
```

### Additional context

```bash
myblog_vitepress on  main [!] is 📦 2.0.7 via ⬢ v18.16.0 
➜ pm dev

> vitepress@2.0.7 dev /Users/bddxg/Documents/coding/web/myblog_vitepress
> vitepress dev docs --open

✘ [ERROR] "vitepress" resolved to an ESM file. ESM file cannot be loaded by `require`. See http://vitejs.dev/guide/troubleshooting.html#this-package-is-esm-only for more details. [plugin externalize-deps]

    node_modules/.pnpm/esbuild@0.18.11/node_modules/esbuild/lib/main.js:1363:27:
      1363 │         let result = await callback({
           ╵                            ^

    at file:///Users/bddxg/Documents/coding/web/myblog_vitepress/node_modules/.pnpm/vite@4.4.9_@types+node@18.15.11/node_modules/vite/dist/node/chunks/dep-df561101.js:66190:35
    at requestCallbacks.on-resolve (/Users/bddxg/Documents/coding/web/myblog_vitepress/node_modules/.pnpm/esbuild@0.18.11/node_modules/esbuild/lib/main.js:1363:28)
    at handleRequest (/Users/bddxg/Documents/coding/web/myblog_vitepress/node_modules/.pnpm/esbuild@0.18.11/node_modules/esbuild/lib/main.js:726:19)
    at handleIncomingPacket (/Users/bddxg/Documents/coding/web/myblog_vitepress/node_modules/.pnpm/esbuild@0.18.11/node_modules/esbuild/lib/main.js:748:7)
    at Socket.readFromStdout (/Users/bddxg/Documents/coding/web/myblog_vitepress/node_modules/.pnpm/esbuild@0.18.11/node_modules/esbuild/lib/main.js:676:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)

  This error came from the "onResolve" callback registered here:

    node_modules/.pnpm/esbuild@0.18.11/node_modules/esbuild/lib/main.js:1282:20:
      1282 │       let promise = setup({
           ╵                     ^

    at setup (file:///Users/bddxg/Documents/coding/web/myblog_vitepress/node_modules/.pnpm/vite@4.4.9_@types+node@18.15.11/node_modules/vite/dist/node/chunks/dep-df561101.js:66158:27)
    at handlePlugins (/Users/bddxg/Documents/coding/web/myblog_vitepress/node_modules/.pnpm/esbuild@0.18.11/node_modules/esbuild/lib/main.js:1282:21)
    at buildOrContextImpl (/Users/bddxg/Documents/coding/web/myblog_vitepress/node_modules/.pnpm/esbuild@0.18.11/node_modules/esbuild/lib/main.js:971:5)
    at Object.buildOrContext (/Users/bddxg/Documents/coding/web/myblog_vitepress/node_modules/.pnpm/esbuild@0.18.11/node_modules/esbuild/lib/main.js:779:5)
    at /Users/bddxg/Documents/coding/web/myblog_vitepress/node_modules/.pnpm/esbuild@0.18.11/node_modules/esbuild/lib/main.js:2166:15
    at new Promise (<anonymous>)
    at Object.build (/Users/bddxg/Documents/coding/web/myblog_vitepress/node_modules/.pnpm/esbuild@0.18.11/node_modules/esbuild/lib/main.js:2165:25)
    at build (/Users/bddxg/Documents/coding/web/myblog_vitepress/node_modules/.pnpm/esbuild@0.18.11/node_modules/esbuild/lib/main.js:2014:51)
    at bundleConfigFile (file:///Users/bddxg/Documents/coding/web/myblog_vitepress/node_modules/.pnpm/vite@4.4.9_@types+node@18.15.11/node_modules/vite/dist/node/chunks/dep-df561101.js:66109:26)

  The plugin "externalize-deps" was triggered by this import

    docs/.vitepress/config.ts:1:395:
      1 │ ...Users/bddxg/Documents/coding/web/myblog_vitepress/docs/.vitepress/config.ts";import { defineConfig } from 'vitepress'
        ╵                                                                                                              ~~~~~~~~~~~

failed to load config from /Users/bddxg/Documents/coding/web/myblog_vitepress/docs/.vitepress/config.ts
failed to start server. error:
Error: Build failed with 1 error:
node_modules/.pnpm/esbuild@0.18.11/node_modules/esbuild/lib/main.js:1363:27: ERROR: [plugin: externalize-deps] "vitepress" resolved to an ESM file. ESM file cannot be loaded by `require`. See http://vitejs.dev/guide/troubleshooting.html#this-package-is-esm-only for more details.
    at failureErrorWithLog (/Users/bddxg/Documents/coding/web/myblog_vitepress/node_modules/.pnpm/esbuild@0.18.11/node_modules/esbuild/lib/main.js:1639:15)
    at /Users/bddxg/Documents/coding/web/myblog_vitepress/node_modules/.pnpm/esbuild@0.18.11/node_modules/esbuild/lib/main.js:1051:25
    at runOnEndCallbacks (/Users/bddxg/Documents/coding/web/myblog_vitepress/node_modules/.pnpm/esbuild@0.18.11/node_modules/esbuild/lib/main.js:1474:45)
    at buildResponseToResult (/Users/bddxg/Documents/coding/web/myblog_vitepress/node_modules/.pnpm/esbuild@0.18.11/node_modules/esbuild/lib/main.js:1049:7)
    at /Users/bddxg/Documents/coding/web/myblog_vitepress/node_modules/.pnpm/esbuild@0.18.11/node_modules/esbuild/lib/main.js:1078:16
    at responseCallbacks.<computed> (/Users/bddxg/Documents/coding/web/myblog_vitepress/node_modules/.pnpm/esbuild@0.18.11/node_modules/esbuild/lib/main.js:700:9)
    at handleIncomingPacket (/Users/bddxg/Documents/coding/web/myblog_vitepress/node_modules/.pnpm/esbuild@0.18.11/node_modules/esbuild/lib/main.js:755:9)
    at Socket.readFromStdout (/Users/bddxg/Documents/coding/web/myblog_vitepress/node_modules/.pnpm/esbuild@0.18.11/node_modules/esbuild/lib/main.js:676:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
 ELIFECYCLE  Command failed with exit code 1.
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
```
import { defineConfig } from 'vitepress'
import * as footnote from 'markdown-it-footnote'
import * as taskLists from 'markdown-it-task-checkbox'
import nav from '../nav'
import sidebar from '../sidebar'


md.use(footnote.default ?? footnote)
md.use(taskLists.default ?? taskLists)
```

Change config file extension to `.mts` or add `"type": "module"` to the nearest package.json to your docs directory.

**Comment by you-hengh** [comment]
我测试过这么写的代码
I have tested the code written in this way.
```
import footnote from 'markdown-it-footnote'
import taskLists from 'markdown-it-task-checkbox'
```

它其实无法正常运行 `pnpm dev` (在代码中看到的`pm`是我对于`pnpm`的简写命令)
It actually cannot run `pnpm dev` properly (the `pm` seen in the code is my shorthand for `pnpm`).

我也尝试了在`package.json`里使用`type:module`, 但仍然没有什么效果,以下是我完整的`config.ts` 配置
I also tried using `type: module` in the `package.json`, but it still doesn't work. Here is my complete `config.ts` configuration.

```ts
import { defineConfig } from 'vitepress'
import * as footnote from 'markdown-it-footnote'
import * as taskLists from 'markdown-it-task-checkbox'
import nav from '../nav'
import sidebar from '../sidebar'

export default defineConfig({
  lang: 'zh-CN',
  title: '冰冻大西瓜的博客',
  titleTemplate: false,
  description: '前端心得/笔记分享.',
  lastUpdated: false,
  appearance: true,
  themeConfig: {
    siteTitle: '冰冻大西瓜的博客',
    logo: 'https://images.bddxg.top/blog/logo.avif',
    outline: 'deep',
    outlineTitle: '文章目录',
    lastUpdatedText: '更新于',
    nav: nav,
    sidebar: Object.assign({}, ...Object.values(sidebar)),
    search: {
      provider: 'local',
      options: {
        locales: {
          root: {
            translations: {
              button: {
                buttonText: '搜索文档',
                buttonAriaLabel: '搜索文档',
              },
              modal: {
                displayDetails: '显示详情',
                noResultsText: '没有找到结果',
                resetButtonTitle: '清除查询条件',
                footer: {
                  selectText: '选择',
                  navigateText: '切换',
                  closeText: '关闭',
                },
              },
            },
          },
        },
      },
    },
    docFooter: {
      prev: '上一页',
      next: '下一页',
    },
    footer: {
      message:
        '<a href="https://www.upyun.com/?utm_source=lianmeng&utm_medium=referral">本网站由<img src="https://images.bddxg.top/blog/%E5%8F%88%E6%8B%8D%E4%BA%91.avif" style="width:4rem; display:inline;vertical-align:text-bottom">提供 CDN 加速/云存储服务</a>',
      copyright: 'Copyright © 2021-至今 <a href="https://beian.miit.gov.cn">陇ICP备2021002743号</a>',
    },
  },
  markdown: {
    lineNumbers: true,

    config: md => {
      md.use(footnote)
      md.use(taskLists, {
        disabled: true,
        divWrap: false,
        divClass: 'checkbox',
        idPrefix: 'cbx_',
        ulClass: 'task-list',
        liClass: 'task-list-item',
      })
      md.renderer.rules.footnote_anchor = function render_footnote_anchor(tokens, idx, options, env, slf) {
        let id = slf.rules.footnote_anchor_name?.(tokens, idx, options, env, slf)
        if (tokens[idx].meta.subId > 0) {
          id += ':' + tokens[idx].meta.subId
        }
        return ' <a href="#fnref' + id + '" class="footnote-backref">👈🏻</a>'
      }
    },
  },
})
```

运行`pnpm dev` 报错
Error occurred when running `pnpm dev`.
```bash
myblog_vitepress on  main [✘!?] is 📦 2.0.7 via ⬢ v18.16.0 
➜ pm dev

> vitepress@2.0.7 dev /Users/bddxg/Documents/coding/web/myblog_vitepress
> vitepress dev docs --open

failed to start server. error:
TypeError: plugin.apply is not a function
    at MarkdownIt$1.use (file:///Users/bddxg/Documents/coding/web/myblog_vitepress/node_modules/.pnpm/vitepress@1.0.0-rc.4_@algolia+client-search@4.17.0_@types+node@18.15.11_search-insights@2.6.0/node_modules/vitepress/dist/node/serve-3dd2c315.js:30180:10)
    at Object.config (file:///Users/bddxg/Documents/coding/web/myblog_vitepress/docs/.vitepress/config.mts.timestamp-1692285613177-41d70f766236b.mjs:319:10)
    at createMarkdownRenderer (file:///Users/bddxg/Documents/coding/web/myblog_vitepress/node_modules/.pnpm/vitepress@1.0.0-rc.4_@algolia+client-search@4.17.0_@types+node@18.15.11_search-insights@2.6.0/node_modules/vitepress/dist/node/serve-3dd2c315.js:35796:13)
    at async localSearchPlugin (file:///Users/bddxg/Documents/coding/web/myblog_vitepress/node_modules/.pnpm/vitepress@1.0.0-rc.4_@algolia+client-search@4.17.0_@types+node@18.15.11_search-insights@2.6.0/node_modules/vitepress/dist/node/serve-3dd2c315.js:36848:14)
    at async createVitePressPlugin (file:///Users/bddxg/Documents/coding/web/myblog_vitepress/node_modules/.pnpm/vitepress@1.0.0-rc.4_@algolia+client-search@4.17.0_@types+node@18.15.11_search-insights@2.6.0/node_modules/vitepress/dist/node/serve-3dd2c315.js:37353:5)
    at async createServer (file:///Users/bddxg/Documents/coding/web/myblog_vitepress/node_modules/.pnpm/vitepress@1.0.0-rc.4_@algolia+client-search@4.17.0_@types+node@18.15.11_search-insights@2.6.0/node_modules/vitepress/dist/node/serve-3dd2c315.js:37370:14)
    at async createDevServer (file:///Users/bddxg/Documents/coding/web/myblog_vitepress/node_modules/.pnpm/vitepress@1.0.0-rc.4_@algolia+client-search@4.17.0_@types+node@18.15.11_search-insights@2.6.0/node_modules/vitepress/dist/node/cli.js:407:20)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by you-hengh** [comment]
我目前退回版本到 1.0.0-beta.7  目前一切正常, 但我仍然希望自己能够使用最新版本

I have currently rolled back to version 1.0.0-beta.7 and everything is working fine, but I still hope to be able to use the latest version.

@brc-dd

**Comment by brc-dd** [comment]
Can you share a reproducible example using stackblitz (https://vitepress.new). For me normal imports are working fine:

https://stackblitz.com/edit/vite-uoacps?file=docs/.vitepress/config.ts,docs/index.md

**Comment by you-hengh** [comment]
> Can you share a reproducible example using stackblitz (https://vitepress.new). For me normal imports are working fine:
> 
> https://stackblitz.com/edit/vite-uoacps?file=docs/.vitepress/config.ts,docs/index.md

Oh, my God, I retried your suggestion, and it worked successfully, but the confusing thing is that the previous operation is the same as today's operation, but the previous operation failed, and today succeeded, perhaps because there was no restart of vscode before? I don't quite understand, but the exciting thing is that the problem seems to have been solved. Thank you very much for your reply!

**Comment by lmssiehdev** [comment]
> Change config file extension to .mts or add "type": "module" to the nearest package.json to your docs directory.

I got the same error following the pnpm install steps from the docs, changing the config .mts and adding type:module solved it, are the docs outdated?

**Comment by brc-dd** [comment]
It's already mentioned on the very first page:

![Screenshot_20230819-102707-351](https://github.com/vuejs/vitepress/assets/40380293/59fc3dc2-8698-4513-8530-3624c8fc7797)

**Comment by lmssiehdev** [comment]
ah nice, any reason why `pnpm dlx vitepress init` doesn't do this by default?

**Comment by brc-dd** [comment]
It already does.

**Comment by lmssiehdev** [comment]
Weird! I remember having the issue after a fresh install and had to fix it manually, I'll see if I can reproduce this.
