### ISSUE TITLE
Unexpected token "export"

### ISSUE THREAD

**Issue by truefusion** [vuejs/vitepress#2821]
### Describe the bug

Running dev server works fine. At compile time, it exits with the error:

```
Unexpected token: "export"
```

### Reproduction

https://github.com/truefusion/skittle

```
yarn docs:build
```

### Expected behavior

To compile without error.

### System Info

```sh
System:
    OS: Linux 6.4 Arch Linux
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i5-13600KF
    Memory: 50.25 GB / 62.63 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.5.0 - /usr/bin/node
    Yarn: 3.5.0 - /usr/bin/yarn
    npm: 9.8.1 - /usr/bin/npm
    pnpm: 7.29.1 - /usr/bin/pnpm
```

### Additional context

$ vitepress build docs

  vitepress v1.0.0-rc.4

- building client + server bundles...
✓ building client + server bundles...
- rendering pages...
(node:1927) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/home/runner/work/skittle/skittle/node_modules/animejs/lib/anime.es.js:1310
export default anime;
^^^^^^

SyntaxError: Unexpected token 'export'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:9[6](https://github.com/truefusion/skittle/actions/runs/5915662580/job/16042130889#step:5:7)0:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
ReferenceError: OffscreenCanvas is not defined
    at new _Renderer2d (file:///home/runner/work/skittle/skittle/docs/.vitepress/.temp/Shape.[7](https://github.com/truefusion/skittle/actions/runs/5915662580/job/16042130889#step:5:8)bf010c6.js:103:37)
    at new Layer (file:///home/runner/work/skittle/skittle/docs/.vitepress/.temp/Shape.7bf010c6.js:4[8](https://github.com/truefusion/skittle/actions/runs/5915662580/job/16042130889#step:5:9)8:37)
    at setup (file:///home/runner/work/skittle/skittle/docs/.vitepress/.temp/Shape.7bf010c6.js:734:1[9](https://github.com/truefusion/skittle/actions/runs/5915662580/job/16042130889#step:5:10))
    at _sfc_main$1.setup (file:///home/runner/work/skittle/skittle/docs/.vitepress/.temp/Shape.7bf0[10](https://github.com/truefusion/skittle/actions/runs/5915662580/job/16042130889#step:5:11)c6.js:804:25)
    at callWithErrorHandling (/home/runner/work/skittle/skittle/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:18:18)
    at setupStatefulComponent (/home/runner/work/skittle/skittle/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5822:25)
    at setupComponent (/home/runner/work/skittle/skittle/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5809:36)
    at renderComponentVNode (/home/runner/work/skittle/skittle/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:354:15)
    at ssrRenderComponent (/home/runner/work/skittle/skittle/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:86:10)
    at file:///home/runner/work/skittle/skittle/docs/.vitepress/.temp/examples_hit-detection.md.js:56:13
ReferenceError: OffscreenCanvas is not defined
    at new _Renderer2d (file:///home/runner/work/skittle/skittle/docs/.vitepress/.temp/Shape.7bf010c6.js:103:37)
    at new Layer (file:///home/runner/work/skittle/skittle/docs/.vitepress/.temp/Shape.7bf010c6.js:488:37)
    at setup (file:///home/runner/work/skittle/skittle/docs/.vitepress/.temp/Shape.7bf010c6.js:734:19)
    at _sfc_main$1.setup (file:///home/runner/work/skittle/skittle/docs/.vitepress/.temp/Shape.7bf010c6.js:804:25)
    at callWithErrorHandling (/home/runner/work/skittle/skittle/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:18:18)
    at setupStatefulComponent (/home/runner/work/skittle/skittle/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5822:25)
    at setupComponent (/home/runner/work/skittle/skittle/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5809:36)
    at renderComponentVNode (/home/runner/work/skittle/skittle/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:354:15)
    at ssrRenderComponent (/home/runner/work/skittle/skittle/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:86:10)
    at file:///home/runner/work/skittle/skittle/docs/.vitepress/.temp/examples_hit-detection.md.js:79:13
TypeError: Cannot read properties of undefined (reading 'timeline')
    at setup (file:///home/runner/work/skittle/skittle/docs/.vitepress/.temp/examples_origin.md.js:12:28)
    at _sfc_main$1.setup (file:///home/runner/work/skittle/skittle/docs/.vitepress/.temp/examples_origin.md.js:149:25)
    at callWithErrorHandling (/home/runner/work/skittle/skittle/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:18:18)
    at setupStatefulComponent (/home/runner/work/skittle/skittle/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5822:25)
    at setupComponent (/home/runner/work/skittle/skittle/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5809:36)
    at renderComponentVNode (/home/runner/work/skittle/skittle/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:354:15)
    at ssrRenderComponent (/home/runner/work/skittle/skittle/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:86:10)
    at file:///home/runner/work/skittle/skittle/docs/.vitepress/.temp/examples_origin.md.js:158:13
    at renderComponentSubTree (/home/runner/work/skittle/skittle/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:423:9)
    at renderComponentVNode (/home/runner/work/skittle/skittle/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:371:12)
✖ rendering pages...
/home/runner/work/skittle/skittle/node_modules/animejs/lib/anime.es.js:1310
export default anime;
^^^^^^

SyntaxError: Unexpected token 'export'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:[11](https://github.com/truefusion/skittle/actions/runs/5915662580/job/16042130889#step:5:12)78:20)
    at Module._compile (node:internal/modules/cjs/loader:[12](https://github.com/truefusion/skittle/actions/runs/5915662580/job/16042130889#step:5:13)20:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:[13](https://github.com/truefusion/skittle/actions/runs/5915662580/job/16042130889#step:5:14)10:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:[16](https://github.com/truefusion/skittle/actions/runs/5915662580/job/16042130889#step:5:17)9:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

Node.js v18.[17](https://github.com/truefusion/skittle/actions/runs/5915662580/job/16042130889#step:5:18).0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Looks like that library is not SSR compatible and has invalid ESM.

Something like this in your config might work for the latter:

```ts
  vite: {
    ssr: {
      noExternal: ['animejs/lib/anime.es.js'],
    }
  }
```

For SSR compatibility, you'd need to import it dynamically inside onMounted.
