### ISSUE TITLE
VPLocalSearch/VPAlgoliaSearch box `⌘` is glitched on Safari on Mac

### ISSUE THREAD

**Issue by pilotmoon** [vuejs/vitepress#2885]
### Describe the bug

When viewed in Safari 16.5 on Mac, the search box has a visual display glitch whereby the ⌘ character appears significatly offset from its correct position. See screenshot.

### Reproduction

1. Clean install vitepress 1.0.0-rc.10 using `npx vitepress init` with all default options.
2. In `.vitepress/config.mts`, add to `themeConfig`:
```
    search: {
      provider: 'local'
    },
```
3. `npm run docs:dev`
4. View site using Safari 16.5 on a macOS Ventura.
5. Observe that the ⌘ character is in the wrong place, as per screenshot attached.

_Alternatively, just visit <https://vitepress.dev> on macOS Safari because it has the bug right now._

### Expected behavior

⌘ character should be inside the search box.

### System Info

```sh
0 verbose cli /Users/nick/.nodenv/versions/18.13.0/bin/node /Users/nick/.nodenv/versions/18.13.0/lib/node_modules/npm/bin/npm-cli.js
1 info using npm@8.19.3
2 info using node@v18.13.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 0ms
5 timing config:load:file:/Users/nick/.nodenv/versions/18.13.0/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 0ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/Users/nick/scratch/vptest/.npmrc Completed in 0ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:/Users/nick/.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/Users/nick/.nodenv/versions/18.13.0/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 5ms
19 timing npm:load:configload Completed in 5ms
20 timing npm:load:mkdirpcache Completed in 1ms
21 timing npm:load:mkdirplogs Completed in 0ms
22 verbose title npm exec envinfo --system --npmPackages vitepress --binaries --browsers
23 verbose argv "exec" "--" "envinfo" "--system" "--npmPackages" "vitepress" "--binaries" "--browsers"
24 timing npm:load:setTitle Completed in 13ms
25 timing config:load:flatten Completed in 1ms
26 timing npm:load:display Completed in 2ms
27 verbose logfile logs-max:10 dir:/Users/nick/.npm/_logs
28 verbose logfile /Users/nick/.npm/_logs/2023-08-30T18_30_20_810Z-debug-0.log
29 timing npm:load:logFile Completed in 2ms
30 timing npm:load:timers Completed in 0ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 23ms
33 silly logfile start cleaning logs, removing 1 files
34 silly logfile done cleaning log files
35 timing arborist:ctor Completed in 0ms
36 timing arborist:ctor Completed in 0ms
37 http fetch GET 200 https://registry.npmjs.org/envinfo 127ms (cache revalidated)
38 timing arborist:ctor Completed in 0ms
39 timing arborist:ctor Completed in 0ms
40 timing command:exec Completed in 211ms
41 verbose stack Error: canceled
41 verbose stack     at exec (/Users/nick/.nodenv/versions/18.13.0/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:230:17)
41 verbose stack     at async module.exports (/Users/nick/.nodenv/versions/18.13.0/lib/node_modules/npm/lib/cli.js:78:5)
42 verbose cwd /Users/nick/scratch/vptest
43 verbose Darwin 22.5.0
44 verbose node v18.13.0
45 verbose npm  v8.19.3
46 error canceled
47 verbose exit 1
48 timing npm Completed in 275ms
49 verbose code 1
50 error A complete log of this run can be found in:
50 error     /Users/nick/.npm/_logs/2023-08-30T18_30_20_810Z-debug-0.log

```

### Additional context

![CleanShot 2023-08-30 at 19 22 59@2x](https://github.com/vuejs/vitepress/assets/17520/292dc33d-5767-4e90-9ca8-4c70d07755a9)

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
The glitch is there for me as well, but not that much though 👀 Also, seems like closing the box is scrolling the site to bottom for some reason 👀

**Comment by brc-dd** [comment]
can you check it again on deployed site if it works fine?

**Comment by brc-dd** [comment]
Something seems be messing it's alignment in your browser. This is the result on my system:

<img width="1181" alt="image" src="https://github.com/vuejs/vitepress/assets/40380293/95b2387e-fe81-41cf-844a-b7ee8be055f1">

(top - arc/chromium, bottom - safari)

**Comment by pilotmoon** [comment]
It's Safari Version 16.5 (18615.2.9.11.4). I tried disabling all extensions, with the same result.

However I notice it only happens at lower zoom levels, see GIF:

![CleanShot 2023-08-31 at 09 45 56](https://github.com/vuejs/vitepress/assets/17520/3c2a4b85-ad4d-44b1-84c0-27a8fd896dbb)

I tried it also on Release 177 (Safari 17.0, WebKit 18617.1.4.3) and it is doing the same there.

**Comment by brc-dd** [comment]
Ok, yeah now I am able to reproduce this on Safari TP (there is weird line too, gradient is also fucked up in dark mode 😖):

<img width="416" alt="image" src="https://github.com/vuejs/vitepress/assets/40380293/6448a87e-2e5e-4948-b357-8b19db8b3e95">

**Comment by bluwy** [comment]
Looks like it's fixed now
