### ISSUE TITLE
the markdown filename with chinese can't build

### ISSUE THREAD

**Issue by Yangjia23** [vuejs/vitepress#293]
**Describe the bug**

the markdown filename with chinese can't build

**To Reproduce**

- create the markdown and the filename with chinese
- then run: `yarn docs:build`
- the result:

```
$ vitepress build docs
vitepress v0.13.2
vite v2.2.3
✓ building client + server bundles...
⠋ rendering pages...Error: Cannot find module './frontend-graph_CSS_1%E3%80%81%E9%A1%B5%E9%9D%A2%E5%B8%83%E5%B1%80%E5%8E%9F%E7%90%86.md.js'
Require stack:
- /Users/yangjay/project/vitepress-blog/node_modules/vitepress/dist/client/app/temp/app.js
- /Users/yangjay/project/vitepress-blog/node_modules/vitepress/dist/node/build/render.js
- /Users/yangjay/project/vitepress-blog/node_modules/vitepress/dist/node/build/build.js
- /Users/yangjay/project/vitepress-blog/node_modules/vitepress/dist/node/index.js
- /Users/yangjay/project/vitepress-blog/node_modules/vitepress/dist/node/cli.js
- /Users/yangjay/project/vitepress-blog/node_modules/vitepress/bin/vitepress.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1020:15)
    at Function.Module._load (internal/modules/cjs/loader.js:890:27)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at /Users/yangjay/project/vitepress-blog/node_modules/vitepress/dist/client/app/temp/app.js:1686:12
    at loadPage (/Users/yangjay/project/vitepress-blog/node_modules/vitepress/dist/client/app/temp/app.js:128:18)
    at Object.go (/Users/yangjay/project/vitepress-blog/node_modules/vitepress/dist/client/app/temp/app.js:121:12)
    at Object.renderPage (/Users/yangjay/project/vitepress-blog/node_modules/vitepress/dist/node/build/render.js:18:12)
    at Object.build (/Users/yangjay/project/vitepress-blog/node_modules/vitepress/dist/node/build/build.js:29:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/yangjay/project/vitepress-blog/node_modules/vitepress/dist/client/app/temp/app.js',
    '/Users/yangjay/project/vitepress-blog/node_modules/vitepress/dist/node/build/render.js',
    '/Users/yangjay/project/vitepress-blog/node_modules/vitepress/dist/node/build/build.js',
    '/Users/yangjay/project/vitepress-blog/node_modules/vitepress/dist/node/index.js',
    '/Users/yangjay/project/vitepress-blog/node_modules/vitepress/dist/node/cli.js',
    '/Users/yangjay/project/vitepress-blog/node_modules/vitepress/bin/vitepress.js'
  ]
}
✖ rendering pages...
build error:
 TypeError: Cannot destructure property 'frontmatter' of 'route.data' as it is null.
```

**Expected behavior**

the markdown filename with chinese can build

**System Info**
- vitepress version: v0.13.2
- vite version: v2.2.3
- Node version: v14.2.0
- OS version: mac 10.15.7 (19H524)

**Additional context**

**Comment by edisonLzy** [comment]
This was happen when i config the outDir in vite.build

**Comment by kiaking** [comment]
Is this still happening?
