### ISSUE TITLE
Can't build when files are missing (ignoreDeadLinks is not working)

### ISSUE THREAD

**Issue by personalsoft-fabianobonin** [vuejs/vitepress#3081]
### Describe the bug

Hi,

I'm currently working on a project where I'd like to proceed with building despite any dead links or missing resources. While I understand that it's best practice to have a documentation without these issues, I believe it's more important to generate a build even with potential inconsistencies.

I enabled the option ```ignoreDeadLinks: true``` but I am not able to build.

It complains about a ```productUnit.png``` file which is missing indeed, but I would like to build anyway.

How can I achieve this?

As a side note, I typically keep my assets such as images, spreadsheets, and PDFs in the same folder as my markdown files.

Regards,

Fabiano

```js
⠼ building client + server bundles...Could not resolve "./productUnit.png" from "src/app/catalog/product/productUnit.md"
file: /opt/zen.erp.docs.engine/src/app/catalog/product/productUnit.md
✖ building client + server bundles...
build error:
RollupError: Could not resolve "./productUnit.png" from "src/app/catalog/product/productUnit.md"
    at error (file:///opt/zen.erp.docs.engine/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
    at ModuleLoader.handleInvalidResolvedId (file:///opt/zen.erp.docs.engine/node_modules/rollup/dist/es/shared/node-entry.js:24860:24)
    at file:///opt/zen.erp.docs.engine/node_modules/rollup/dist/es/shared/node-entry.js:24822:26
```

### Reproduction

Could not reproduce with 

### Expected behavior

To build the docs

### System Info

```Text
vitepress 1.0.0-rc.20
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
This isn't supported currently. ignoreDeadLinks is only for pages not assets.

**Comment by personalsoft-fabianobonin** [comment]
Do you have any insights into how StackBlitz is able to successfully build even when an asset is missing? If they've achieved this, there's likely a method I can implement as well.

The current behavior poses a significant obstacle for various scenarios. I manage a team responsible for generating documentation, and we have an automated build process triggered by a GitHub webhook. If any of my team members accidentally push a page with an invalid asset, it halts the entire documentation build process until someone manually inspects the logs.

Regards,

Fabiano

**Comment by brc-dd** [comment]
> Do you have any insights into how StackBlitz is able to successfully build even when an asset is missing? 

It doesn't. You probably are running the dev command.

<img width="718" alt="image" src="https://github.com/vuejs/vitepress/assets/40380293/be3dadb0-7832-46d5-af57-f65889e78e61">

**Comment by bluwy** [comment]
I think it's easiest to workaround this by adding a stub image or remove the links if it happens. Trying to fix this is tricky because it transform the asset references as imports, which we can't know if it exists until the import tries to resolve from Vite, and trying to setup a fallback is also tricky because at that point we don't know what the original path to preserve is.

Since we haven't got a ton of demand to support this, I'm inclined to leave it as is for now.
