### ISSUE TITLE
RC21 Regression: "TypeError: crypto.getRandomValues is not a function" when deploying on GitHub pages

### ISSUE THREAD

**Issue by Elringus** [vuejs/vitepress#3090]
### Describe the bug

```
> vitepress build docs


  vitepress v1.0.0-rc.21

- building client + server bundles...
[vitepress] crypto.getRandomValues is not a function
file: /home/runner/work/naninovel.github.io/naninovel.github.io/docs/guide/integration-options.md
✖ building client + server bundles...
build error:
TypeError: crypto.getRandomValues is not a function
    at fillPool (file:///home/runner/work/naninovel.github.io/naninovel.github.io/node_modules/vitepress/dist/node/serve-M2jpHott.js:46428:12)
    at nanoid$1 (file:///home/runner/work/naninovel.github.io/naninovel.github.io/node_modules/vitepress/dist/node/serve-M2jpHott.js:46459:3)
    at Object.render (file:///home/runner/work/naninovel.github.io/naninovel.github.io/node_modules/vitepress/dist/node/serve-M2jpHott.js:46557:24)
    at Renderer$1.render (file:///home/runner/work/naninovel.github.io/naninovel.github.io/node_modules/vitepress/dist/node/serve-M2jpHott.js:35102:28)
    at Renderer$1.md.renderer.render (file:///home/runner/work/naninovel.github.io/naninovel.github.io/node_modules/vitepress/dist/node/serve-M2jpHott.js:29332:12)
    at MarkdownIt$1.render (file:///home/runner/work/naninovel.github.io/naninovel.github.io/node_modules/vitepress/dist/node/serve-M2jpHott.js:41569:24)
    at MarkdownIt$1.md.render (file:///home/runner/work/naninovel.github.io/naninovel.github.io/node_modules/vitepress/dist/node/serve-M2jpHott.js:29233:12)
    at MarkdownIt$1.md.render (file:///home/runner/work/naninovel.github.io/naninovel.github.io/node_modules/vitepress/dist/node/serve-M2jpHott.js:29286:22)
    at file:///home/runner/work/naninovel.github.io/naninovel.github.io/node_modules/vitepress/dist/node/serve-M2jpHott.js:47919:21
    at Object.transform (file:///home/runner/work/naninovel.github.io/naninovel.github.io/node_modules/vitepress/dist/node/serve-M2jpHott.js:48579:55)
Error: Process completed with exit code 1.
```

### Reproduction

RC21: https://github.com/Naninovel/naninovel.github.io/actions/runs/6518735005/job/17709400139#step:5:13

### Expected behavior

RC20: https://github.com/Naninovel/naninovel.github.io/actions/runs/6521208861/job/17709573364#step:5:14

### System Info

```Text
-
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by Elringus** [comment]
Looks like this is due to rc21 not working with node 16, which is still used by default when publishing to github pages. It's weird that they're still using 16 and I'm aware that it's possible to use a custom build script with a newer node, but not sure if a single call to `random` is worth breaking compatibility with the default gh pages workflow.

**Comment by simply-none** [comment]
I also encountered this error today, but not yesterday, perhaps because I re-ran npm install

**Comment by brc-dd** [comment]
Fixed in rc.22

But node 16 compatibility was dropped in rc.4 version (refer changelog), and we don't intend on maintaining vitepress for an EOL version of node. 

> which is still used by default when publishing to github pages

No it's not. `actions/setup-node@v3` has no default value for `node-version`. You have probably specified node 16 in your workflow file or something like .nvmrc.

**Comment by Elringus** [comment]
My bad, I'm stupid. Had github deploy workflow script with node 16 specified in it, but forgot about it and instead thought that gh pages has some default deploy flow. Sorry for the noise.
