### ISSUE TITLE
Preprocessor dependency "sass" failed to load: Cannot read properties of undefined (reading 'pop')

### ISSUE THREAD

**Issue by tomiaa12** [vuejs/vitepress#3102]
### Describe the bug

> vitepress@0.0.0 dev
> vitepress dev src

  vitepress v1.0.0-rc.22

  ➜  Local:   http://localhost:5173/
  ➜  press h to show help
Preprocessor dependency "sass" failed to load:
Cannot read properties of undefined (reading 'indexOf')
Preprocessor dependency "sass" failed to load:
Cannot read properties of undefined (reading 'pop')
Preprocessor dependency "sass" failed to load:
Cannot read properties of undefined (reading 'pop') (x2)
09:36:03 [vitepress] Internal server error: Preprocessor dependency "sass" failed to load:
Cannot read properties of undefined (reading 'pop')
  Plugin: vite:css
  File: F:/github/blog/src/style/index.scss
      at Object.<anonymous> (F:\github\blog\node_modules\.pnpm\sass@1.69.3\node_modules\sass\sass.node.js:2:43)
      at Module._compile (node:internal/modules/cjs/loader:1369:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
      at Module.load (node:internal/modules/cjs/loader:1201:32)
      at Module._load (node:internal/modules/cjs/loader:1017:12)
      at Module.require (node:internal/modules/cjs/loader:1229:19)
      at require (node:internal/modules/helpers:177:18)
      at loadPreprocessor (file:///F:/github/blog/node_modules/.pnpm/vite@4.4.11_@types+node@18.18.5_sass@1.69.3/node_modules/vite/dist/node/chunks/dep-2b82a1ce.js:39294:45)
      at scss (file:///F:/github/blog/node_modules/.pnpm/vite@4.4.11_@types+node@18.18.5_sass@1.69.3/node_modules/vite/dist/node/chunks/dep-2b82a1ce.js:39340:20)
      at compileCSSPreprocessors (file:///F:/github/blog/node_modules/.pnpm/vite@4.4.11_@types+node@18.18.5_sass@1.69.3/node_modules/vite/dist/node/chunks/dep-2b82a1ce.js:38765:36)
      at loadPreprocessor (file:///F:/github/blog/node_modules/.pnpm/vite@4.4.11_@types+node@18.18.5_sass@1.69.3/node_modules/vite/dist/node/chunks/dep-2b82a1ce.js:39302:29)
      at scss (file:///F:/github/blog/node_modules/.pnpm/vite@4.4.11_@types+node@18.18.5_sass@1.69.3/node_modules/vite/dist/node/chunks/dep-2b82a1ce.js:39340:20)
      at compileCSSPreprocessors (file:///F:/github/blog/node_modules/.pnpm/vite@4.4.11_@types+node@18.18.5_sass@1.69.3/node_modules/vite/dist/node/chunks/dep-2b82a1ce.js:38765:36)
      at compileCSS (file:///F:/github/blog/node_modules/.pnpm/vite@4.4.11_@types+node@18.18.5_sass@1.69.3/node_modules/vite/dist/node/chunks/dep-2b82a1ce.js:38815:42)
      at async TransformContext.transform (file:///F:/github/blog/node_modules/.pnpm/vite@4.4.11_@types+node@18.18.5_sass@1.69.3/node_modules/vite/dist/node/chunks/dep-2b82a1ce.js:38295:56)
      at async Object.transform (file:///F:/github/blog/node_modules/.pnpm/vite@4.4.11_@types+node@18.18.5_sass@1.69.3/node_modules/vite/dist/node/chunks/dep-2b82a1ce.js:44345:30)
      at async loadAndTransform (file:///F:/github/blog/node_modules/.pnpm/vite@4.4.11_@types+node@18.18.5_sass@1.69.3/node_modules/vite/dist/node/chunks/dep-2b82a1ce.js:55015:29)
      at async viteTransformMiddleware (file:///F:/github/blog/node_modules/.pnpm/vite@4.4.11_@types+node@18.18.5_sass@1.69.3/node_modules/vite/dist/node/chunks/dep-2b82a1ce.js:64417:32)
Preprocessor dependency "sass" failed to load:
Cannot read properties of undefined (reading 'pop')
Preprocessor dependency "sass" failed to load:
Cannot read properties of undefined (reading 'pop') (x2)

### Reproduction

https://github.com/tomiaa12/blog

### Expected behavior

正常打开页面

### System Info

```Text
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-1235U
    Memory: 2.93 GB / 15.64 GB
  Binaries:
    Node: 21.0.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.9.2 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (118.0.2088.46)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vitepress: 1.0.0-rc.22 => 1.0.0-rc.22
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by tomiaa12** [comment]
An error occurs when node21 is used, but node20 works properly

**Comment by brc-dd** [comment]
Seems like a vite bug. Are you able to use sass with a simple vite project on node 21?

**Comment by brc-dd** [comment]
Please track https://github.com/vitejs/vite/issues/14691

**Comment by brc-dd** [comment]
It's an issue with sass - track https://github.com/dart-lang/sdk/issues/53784

**Comment by volnet** [comment]
I found the same problem in https://v2.vuepress.vuejs.org/guide/getting-started.html#%E6%89%8B%E5%8A%A8%E5%AE%89%E8%A3%85
