### ISSUE TITLE
使用 @antv/x6 时，编译报错

### ISSUE THREAD

**Issue by evemike** [vuejs/vitepress#3284]
### Describe the bug

最小复现仓库：[仓库地址](https://github.com/evemike/td-vitepress-x6.git)

错误提示：
ReferenceError: Element is not defined
    at Object.<anonymous> (E:\workspace\workspace-test\github-test\vitepress-x6\node_modules\@antv\x6-common\lib\polyfill\index.js:30:5)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at _require.extensions.<computed> [as .js] (file:///E:/workspace/workspace-test/github-test/vitepress-x6/node_modules/vite/dist/node/chunks/dep-4RECYSE1.js:67481:17)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (E:\workspace\workspace-test\github-test\vitepress-x6\node_modules\@antv\x6-common\lib\index.js:17:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)

### Reproduction

最小复现仓库：[仓库地址](https://github.com/evemike/td-vitepress-x6.git)

执行 （npm run |yarn） docs:build 会报错

### Expected behavior

期望能构建成功

### System Info

```Text
环境：
window11 
node:v18.6.0
yarn:1.22.17
pnpm:8.10.5
vitepress:1.0.0-rc.31
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by wChenonly** [comment]
vitepress uses server-side rendering in node to build your HTML pages. Node doesn't have a window object. 
<img width="942" alt="image" src="https://github.com/vuejs/vitepress/assets/37658262/a224e4b5-455c-414e-bd3e-2331e03e917f">

you can try 
` enhanceApp: async ({ app }) => {
    if (!import.meta.env.SSR) {
      const plugin = (await import('@antv/x6')).default
      app.use(plugin)
    }
  }`
Or use onMounted in the vue file

**Comment by evemike** [comment]
谢谢，我明白了

**Comment by evemike** [comment]
官方文档有解决方案：https://vitejs.cn/vitepress/guide/using-vue.html

解决方法如下：

# hello vitepress
<component v-if="dynamicComponent" :is="dynamicComponent"></component>

`<script setup>
import {onMounted,ref} from "vue"

const dynamicComponent = ref();
onMounted(() => {
  import('./test.vue').then((module) => {
    dynamicComponent.value = module.default
  })
})
</script>
`
