### ISSUE TITLE
Vitepress crashed when rendering some markdown files

### ISSUE THREAD

**Issue by fourdim** [vuejs/vitepress#3323]
### Describe the bug

```
framework.sw6uv5Tp.js:1 DOMException: Failed to execute 'setAttribute' on 'Element': '2' is not a valid attribute name.
    at $a (http://localhost:4173/assets/chunks/framework.sw6uv5Tp.js:1:65528)
    at Ya (http://localhost:4173/assets/chunks/framework.sw6uv5Tp.js:1:67287)
    at B (http://localhost:4173/assets/chunks/framework.sw6uv5Tp.js:1:43411)
    at P (http://localhost:4173/assets/chunks/framework.sw6uv5Tp.js:1:43090)
    at _ (http://localhost:4173/assets/chunks/framework.sw6uv5Tp.js:1:42520)
    at j (http://localhost:4173/assets/chunks/framework.sw6uv5Tp.js:1:43944)
    at B (http://localhost:4173/assets/chunks/framework.sw6uv5Tp.js:1:43271)
    at P (http://localhost:4173/assets/chunks/framework.sw6uv5Tp.js:1:43090)
    at _ (http://localhost:4173/assets/chunks/framework.sw6uv5Tp.js:1:42520)
    at j (http://localhost:4173/assets/chunks/framework.sw6uv5Tp.js:1:43944)
```
![image](https://github.com/vuejs/vitepress/assets/59462000/4ef8718f-aa71-4307-9308-2410d06ab7c8)

### Reproduction

https://stackblitz.com/edit/vite-hw16pn?file=docs%2FInlineEditor.md
Go to the Example page first, and then go to the target page InlineEditor so that it triggers the SPA and then crash.
If you find stackblitz always give you  blank page, it means that vitepress crashed. Simply click Close on the top right corner and open it again.

### Expected behavior

![image](https://github.com/vuejs/vitepress/assets/59462000/167e7a78-8bd7-4c8f-8490-1533e0785672)
This only works when we access this URL directly, i.e. no SPA triggered.

### System Info

```Text
System:
    OS: Linux 6.6 Arch Linux
    CPU: (16) x64 AMD Ryzen 7 7840HS w/ Radeon 780M Graphics
    Memory: 86.62 GB / 90.08 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 18.19.0 - ~/.config/nvm/versions/node/v18.19.0/bin/node
    npm: 10.2.3 - ~/.config/nvm/versions/node/v18.19.0/bin/npm
    pnpm: 8.11.0 - ~/.config/nvm/versions/node/v18.19.0/bin/pnpm
    bun: 1.0.8 - ~/.bun/bin/bun
  Browsers:
    Chromium: 119.0.6045.199
```

### Additional context

The original page is here:
https://blocksuite.io/api/@blocksuite/inline/classes/InlineEditor.html

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by zonemeen** [comment]
You can avoid errors by disabling `markdown-it-attrs`. Ref. https://github.com/vuejs/vitepress/pull/664
