### ISSUE TITLE
build failed with symbolic links

### ISSUE THREAD

**Issue by bowencool** [vuejs/vitepress#335]
### Describe the bug

```
▶ yarn build:docs
yarn run v1.22.10
$ vitepress build docs
vitepress v0.15.6
vite v2.4.1
✓ building client + server bundles...
⠋ rendering pages...
✖ rendering pages...
build error:
 TypeError: Cannot read property 'imports' of undefined
    at resolvePageImports (x/node_modules/vitepress/dist/node/build/render.js:81:22)
    at Object.renderPage (x/node_modules/vitepress/dist/node/build/render.js:35:12)
    at async Object.build (x/node_modules/vitepress/dist/node/build/build.js:29:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

https://github.com/vuejs/vitepress/blob/master/src/node/build/render.ts#L115

### Reproduction

``` bash
cd docs
ln -s ../CHANGELOG.md changelog.md
ln -s ../packages components  
```

### Expected behavior

`build` success same as `dev`

### System Info

```shell
System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 710.10 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 91.0.4472.164
    Edge: 81.0.416.77
    Firefox: 87.0
    Safari: 14.1.1
    Safari Technology Preview: 15.0
  npmPackages:
    vitepress: ^0.15.6 => 0.15.6
```

### Additional context

The following code works fine
```
 return Array.from(new Set([
        ...indexChunk.imports,
        ...indexChunk.dynamicImports,
        ...(pageChunk?.imports|| []),
        ...(pageChunk?.dynamicImports || [])
    ].filter(Boolean)));
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by bowencool** [comment]
vitepress v0.20.1 works
