### ISSUE TITLE
vitepress打包报错

### ISSUE THREAD

**Issue by dj835638078** [vuejs/vitepress#3492]
### Describe the bug

当我使用vitepress打包时，报错：
$ vitepress build docs

  vitepress v1.0.0-rc.40

⠏ building client + server bundles...
(!) Some chunks are larger than 500 kB after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
[commonjs--resolver] Missing "./server-renderer" specifier in "vue" package
✖ building client + server bundles...
build error:
Error: Missing "./server-renderer" specifier in "vue" package
    at e (file:///E:/code/vesyncUI/node_modules/vitepress/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:21914:25)
    at n (file:///E:/code/vesyncUI/node_modules/vitepress/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:21914:627)
    at o (file:///E:/code/vesyncUI/node_modules/vitepress/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:21914:1297)
    at resolveExportsOrImports (file:///E:/code/vesyncUI/node_modules/vitepress/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:29466:20)
    at resolveDeepImport (file:///E:/code/vesyncUI/node_modules/vitepress/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:29485:31)
    at tryNodeResolve (file:///E:/code/vesyncUI/node_modules/vitepress/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:29210:20)
    at Object.resolveId (file:///E:/code/vesyncUI/node_modules/vitepress/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:28978:28)
    at Object.handler (file:///E:/code/vesyncUI/node_modules/vitepress/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:67383:19)
    at file:///E:/code/vesyncUI/node_modules/vitepress/node_modules/rollup/dist/es/shared/node-entry.js:18642:40  
    at async PluginDriver.hookFirstAndGetPlugin (file:///E:/code/vesyncUI/node_modules/vitepress/node_modules/rollup/dist/es/shared/node-entry.js:18542:28)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Reproduction

yarn docs:build

### Expected behavior

打包完成

### System Info

```Text
node: 18.19.0
vitepress：v1.0.0-rc.40
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Like I commented on #3487 - you or any of your dependencies seem to be using vue 2 in vitepress. This won't work.
