### ISSUE TITLE
build error log too less to find the key position

### ISSUE THREAD

**Issue by recrute** [vuejs/vitepress#3705]
### Is your feature request related to a problem? Please describe.

PS E:\src\vitepress> pnpm run docs:dev
  vitepress v1.0.1

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help

  Shortcuts
  press r to restart the server
  press u to show server url
  press o to open in browser
  press c to clear console
  press q to quit
PS E:\src\vitepress> pnpm run docs:build

> @ docs:build E:\src\vitepress
> vitepress build

  vitepress v1.0.1

⠴ building client + server bundles...
The language 'as' is not loaded, falling back to 'txt' for syntax highlighting.
x Build failed in 547ms
✖ building client + server bundles...

The language 'plantuml' is not loaded, falling back to 'txt' for syntax highlighting.

The language 'plantuml' is not loaded, falling back to 'txt' for syntax highlighting. (x2)
build error:
SyntaxError: Element is missing end tag.
    at createCompilerError (E:\src\vitepress\node_modules\.pnpm\@vue+compiler-core@3.4.21\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:1325:17)
    at emitError (E:\src\vitepress\node_modules\.pnpm\@vue+compiler-core@3.4.21\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:2788:5)
    at Object.onclosetag (E:\src\vitepress\node_modules\.pnpm\@vue+compiler-core@3.4.21\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:2182:13)
    at Tokenizer.stateInClosingTagName (E:\src\vitepress\node_modules\.pnpm\@vue+compiler-core@3.4.21\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:749:16)
    at Tokenizer.parse (E:\src\vitepress\node_modules\.pnpm\@vue+compiler-core@3.4.21\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:1107:16)
    at Object.baseParse (E:\src\vitepress\node_modules\.pnpm\@vue+compiler-core@3.4.21\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:2820:13)
    at Object.parse (E:\src\vitepress\node_modules\.pnpm\@vue+compiler-dom@3.4.21\node_modules\@vue\compiler-dom\dist\compiler-dom.cjs.prod.js:633:23)
    at Object.parse$2 [as parse] (E:\src\vitepress\node_modules\.pnpm\@vue+compiler-sfc@3.4.21\node_modules\@vue\compiler-sfc\dist\compiler-sfc.cjs.js:1851:24)
    at createDescriptor (file:///E:/src/vitepress/node_modules/.pnpm/@vitejs+plugin-vue@5.0.4_vite@5.2.6_vue@3.4.21/node_modules/@vitejs/plugin-vue/dist/index.mjs:74:43)
    at transformMain (file:///E:/src/vitepress/node_modules/.pnpm/@vitejs+plugin-vue@5.0.4_vite@5.2.6_vue@3.4.21/node_modules/@vitejs/plugin-vue/dist/index.mjs:2367:34)
 ELIFECYCLE  Command failed with exit code 1.
PS E:\src\vitepress> 

### Describe the solution you'd like

`pnpm run docs:dev`  is success, but `pnpm run docs:build` failed.

end the error output can't to help me find the ref file.

**Comment by brc-dd** [comment]
#2373 should fix this

**Comment by brc-dd** [comment]
fixed by f0debd20f48ab7eb58cfd142147531509d6c0209
