### ISSUE TITLE
dead link errors should show transformed URL

### ISSUE THREAD

**Issue by vincesp** [vuejs/vitepress#3774]
### Describe the bug

**This bug was _not_ present in v1.0.0-rc.24 but is now present in v1.1.0.**

- Create a file with the file extension .crt in the public folder
- Link to that file from a Markdown file

Current behavior:

- During page generation, the file extension .html is added after the file extension .crt
- This results in a dead link
- Fortunately, the dead link checker picks up the dead link and reports it, which results in a failed build. Unfortunately, the error message is misleading. It prints the original file name "/some-root-ca.crt" which would _not_ be a dead link instead of the corrupted file name "/some-root-ca.crt.html" which is the _actual_ dead link.

### Reproduction

https://stackblitz.com/edit/vite-ezwnqb?file=docs%2Fexample.md

- Run `npm run docs:dev`
- Navigate to the Example page
- There are 2 links
  - The link to the txt file will work
  - The link to the crt file is corrupted, points to /some-root-ca.crt.html instead of /some-root-ca.crt
- Run `npm run docs:build`
- The following error will be displayed:
  ```
  (!) Found dead link /some-root-ca.crt in file example.md
  
  If this is expected, you can disable this check via config. Refer: https://vitepress.dev/reference/site-config#ignoredeadlinks
  
  x Build failed in 1.81s
  ✖ building client + server bundles...
  build error:
  Error: [vitepress] 1 dead link(s) found.
      at Object.renderStart (/home/projects/vite-ezwnqb/node_modules/vitepress/dist/node/serve-Csn-CKFx.js:42382:15)
      at eval (/home/projects/vite-ezwnqb/node_modules/rollup/dist/es/shared/node-entry.js:19622:40)
      at async PluginDriver.hookParallel (/home/projects/vite-ezwnqb/node_modules/rollup/dist/es/shared/node-entry.js:19550:9)
      at async Bundle.generate (/home/projects/vite-ezwnqb/node_modules/rollup/dist/es/shared/node-entry.js:17980:13)
      at async eval (/home/projects/vite-ezwnqb/node_modules/rollup/dist/es/shared/node-entry.js:20539:27)
      at async catchUnfinishedHookActions (/home/projects/vite-ezwnqb/node_modules/rollup/dist/es/shared/node-entry.js:19967:16)
  ```
  Note that the link displayed is not a dead link. The error message does not tell that it in fact tries to link to /some-root-ca.crt.html which does not exist.

### Expected behavior

Behavior like in v1.0.0-rc.24:

https://stackblitz.com/edit/vite-5ovzcs?file=package.json

- Link target is not being changed during page generation
- No dead link detected during build

### System Info

```Text
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.3 - /usr/local/bin/pnpm
  npmPackages:
    vitepress: latest => 1.1.0
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
add this to top of your config:

```
process.env.VITE_EXTRA_EXTENSIONS = 'crt' 
```

**Comment by vincesp** [comment]
While downgrading my project to a working version of vitepress, I found out that v1.0.0-rc.39 is the last working version. This bug behavior apparently introduced with 1.0.0-rc.40.

**Comment by vincesp** [comment]
Sorry for the "racing condition." I did not mean to re-open the task, just wanted to document the exact version when the behavior changed.

**Comment by brc-dd** [comment]
Ah, no. You didn't I reopened it because of error message.

**Comment by epogrebnyak** [comment]
Is there a way to know what the dead link at build is? I run `npm run docs:build` and get:

```
✖ building client + server bundles...
build error:
[vitepress] 1 dead link(s) found.
[vitepress] 1 dead link(s) found.
    at Object.renderStart (file:///D:/runnable-python/node_modules/vitepress/dist/node/chunk-Zsoi3j4v.js:45027:15)
    at file:///D:/runnable-python/node_modules/rollup/dist/es/shared/node-entry.js:21844:40      
    at async Promise.all (index 0)
    at async PluginDriver.hookParallel (file:///D:/runnable-python/node_modules/rollup/dist/es/shared/node-entry.js:21772:9)
    at async Bundle.generate (file:///D:/runnable-python/node_modules/rollup/dist/es/shared/node-entry.js:20104:13)
    at async file:///D:/runnable-python/node_modules/rollup/dist/es/shared/node-entry.js:22814:27    at async catchUnfinishedHookActions (file:///D:/runnable-python/node_modules/rollup/dist/es/shared/node-entry.js:22196:16)
```

What page is my dead link at?

**Comment by brc-dd** [comment]
@epogrebnyak Ah, it should show there by default. Is your repo public? Which terminal are you using? Can you try with `CI=true npm run docs:build`?

**Comment by epogrebnyak** [comment]
@brc-dd Thank you for such a quick reply. I'm on powershell  (Windows) and the repo is at https://github.com/epogrebnyak/runnable-python.  Not sure I know how to run `CI=true` :( 
Was hoping there is some flag to show dead links.

**Comment by epogrebnyak** [comment]
> It seems to build fine for me. Are you sure the repo has the latest code?

Just synced now - can you have a look?

**Comment by brc-dd** [comment]
<img width="998" alt="Image" src="https://github.com/user-attachments/assets/d53a844b-d966-4923-b46b-573ae5b58eb4" />

**Comment by epogrebnyak** [comment]
Oh - I thought a dead link is a wrong link config.mjs or in between .md files. It seems an issue with the plugin. The message you provided I do see on my shell, but I was expecting some link to a failing markdown source - that is why I asked. Thank you for looking at the problem, perhaps not replated this issue.

**Comment by brc-dd** [comment]
Yeah so you have a broken link in `index.md`:

<img width="930" alt="Image" src="https://github.com/user-attachments/assets/f97e2c47-45bf-4dfe-aaf8-bece92135680" />

\
If someone visits your site and clicks it, they will be shown a 404 not found page.
