### ISSUE TITLE
build:doc 打包报错：Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by muyaCode** [vuejs/vitepress#3815]
### Describe the bug

打包详情如下：

正在执行任务: pnpm run docs:build 

> program-learn-notes@1.0.0 docs:build D:\Code\[MyProject]\[Docs]\ProgramLearnNotes
> vitepress build docs

  vitepress v1.1.3

x Build failed in 1.71s
✖ building client + server bundles...
node:internal/fs/promises:887
  const result = await binding.lstat(pathModule.toNamespacedPath(path),
                               ^

Error: ENOENT: no such file or directory, lstat
    at lstat (node:internal/fs/promises:887:32)
    at findFile (file:///D:/Code/[MyProject]/[Docs]/ProgramLearnNotes/node_modules/.pnpm/rollup@4.15.0/node_modules/rollup/dist/es/shared/node-entry.js:18226:29)
    at addJsExtensionIfNecessary (file:///D:/Code/[MyProject]/[Docs]/ProgramLearnNotes/node_modules/.pnpm/rollup@4.15.0/node_modules/rollup/dist/es/shared/node-entry.js:18220:20)
    at resolveId (file:///D:/Code/[MyProject]/[Docs]/ProgramLearnNotes/node_modules/.pnpm/rollup@4.15.0/node_modules/rollup/dist/es/shared/node-entry.js:18217:12)
    at async ModuleLoader.resolveId (file:///D:/Code/[MyProject]/[Docs]/ProgramLearnNotes/node_modules/.pnpm/rollup@4.15.0/node_modules/rollup/dist/es/shared/node-entry.js:18595:15)
    at async Object.resolveId (file:///D:/Code/[MyProject]/[Docs]/ProgramLearnNotes/node_modules/.pnpm/vite@5.2.10/node_modules/vite/dist/node/chunks/dep-DkOS1hkm.js:8247:10)
    at async PluginDriver.hookFirstAndGetPlugin (file:///D:/Code/[MyProject]/[Docs]/ProgramLearnNotes/node_modules/.pnpm/rollup@4.15.0/node_modules/rollup/dist/es/shared/node-entry.js:19511:28)
    at async resolveId (file:///D:/Code/[MyProject]/[Docs]/ProgramLearnNotes/node_modules/.pnpm/rollup@4.15.0/node_modules/rollup/dist/es/shared/node-entry.js:18192:26)
    at async ModuleLoader.resolveId (file:///D:/Code/[MyProject]/[Docs]/ProgramLearnNotes/node_modules/.pnpm/rollup@4.15.0/node_modules/rollup/dist/es/shared/node-entry.js:18595:15)
    at async file:///D:/Code/[MyProject]/[Docs]/ProgramLearnNotes/node_modules/.pnpm/rollup@4.15.0/node_modules/rollup/dist/es/shared/node-entry.js:18899:50 {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'lstat'
}

Node.js v20.9.0
 ELIFECYCLE  Command failed with exit code 1.

### Reproduction

打包错误的文档：https://github.com/muyaCode/ProgramLearnNotes

而我本地同级目录下另一个文档，能成功打包：https://github.com/muyaCode/FrontEndLearnNotes

### Expected behavior

能成功打包

### System Info

```Text
系统：Windows 11 家庭中文版
```

### Additional context

![1713625960909](https://github.com/vuejs/vitepress/assets/48587992/77110a5d-5310-40a3-952b-09760f8b4ca4)

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by muyaCode** [comment]
找到问题了：图片目录带有🦀️，读取不到，但是为什么报错不显示详细错误？

**Comment by brc-dd** [comment]
This is fixed in Node 22, which now shows path argument when any fs call fails. Also, the newer versions of vitepress show the file where the bundling failed:

<img width="1215" alt="image" src="https://github.com/vuejs/vitepress/assets/40380293/171bcf31-7146-428b-8d22-679f25813bf8">
