### ISSUE TITLE
yarn vitepress init error

### ISSUE THREAD

**Issue by JoyZ-nineteen** [vuejs/vitepress#3841]
### Describe the bug

node 版本18.12.1
步骤1： yarn add -D vitepres
步骤2：yarn vitepress init
就开始报错

### Reproduction

报错如下：
```
yarn run v1.22.21
warning package.json: No license field
$ D:\MyConfiguration\yi10.zhang\Desktop\dmeo\node_modules\.bin\vitepress init

T  Welcome to VitePress!
node:internal/errors:484
    ErrorCaptureStackTrace(err);
    ^

SystemError [ERR_TTY_INIT_FAILED]: TTY initialization failed: uv_tty_init returned EBADF (bad file descriptor)
    at new SystemError (node:internal/errors:244:5)
    at new NodeError (node:internal/errors:355:7)
    at new WriteStream (node:tty:93:11)
    at TD.prompt (file:///D:/MyConfiguration/yi10.zhang/Desktop/dmeo/node_modules/vitepress/dist/node/serve-CXVdC751.js:47012:863)
    at te (file:///D:/MyConfiguration/yi10.zhang/Desktop/dmeo/node_modules/vitepress/dist/node/serve-CXVdC751.js:47027:7)
    at root (file:///D:/MyConfiguration/yi10.zhang/Desktop/dmeo/node_modules/vitepress/dist/node/serve-CXVdC751.js:49123:19)
    at he (file:///D:/MyConfiguration/yi10.zhang/Desktop/dmeo/node_modules/vitepress/dist/node/serve-CXVdC751.js:47044:95)
    at init (file:///D:/MyConfiguration/yi10.zhang/Desktop/dmeo/node_modules/vitepress/dist/node/serve-CXVdC751.js:49121:25)
    at file:///D:/MyConfiguration/yi10.zhang/Desktop/dmeo/node_modules/vitepress/dist/node/cli.js:429:3
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25) {
  code: 'ERR_TTY_INIT_FAILED',
  info: {
    errno: -4083,
    code: 'EBADF',
    message: 'bad file descriptor',
    syscall: 'uv_tty_init'
  },
  errno: [Getter/Setter],
  syscall: [Getter/Setter]
}

Node.js v18.12.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

### Expected behavior

希望不报错了

### System Info

```Text
node -v => 18.12.1
yarn -v => 1.22.21
"vitepress": "^1.1.4"
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Use some terminal other than git bash.

**Comment by JoyZ-nineteen** [comment]
Thank you very much

**Comment by xiaohulu** [comment]
使用 tauri2 的 shell 插件调用 `npx vitepress init` 也报同样的错误。

https://github.com/tauri-apps/plugins-workspace/issues/2309

**Comment by xiaohulu** [comment]
除了交互方式输入命令行参数，
也可以考虑一次输入所有参数 `vitepress init -root xx -title xx -description xxx -useTs`,
这样就可以避开 clack 引起的错误。
