### ISSUE TITLE
Unknown file extension ".vue" on production build

### ISSUE THREAD

**Issue by slavarazum** [vuejs/vitepress#3898]
### Describe the bug

The issue appears to be related to the integration of the @oku-ui/motion ([Motion component](https://github.com/oku-ui/motion/blob/main/packages/vue/src/components/Motion.vue)) with Vitepress. However, as this is just Vue component, it should be correctly recognized by the Vitepress build. It works perfectly with **npm run docs:dev** mode and throws "Unknown file extension" error on **npm run docs:build**.

### Reproduction

Default template with `Motion` component import.
https://stackblitz.com/edit/vite-kxpk3c?file=docs%2F.vitepress%2Ftheme%2FLayout.vue

```bash
npm run docs:build

vitepress build docs

  vitepress v1.1.4

✓ building client + server bundles...
build error:
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".vue" for /home/projects/vite-kxpk3c/node_modules/@oku-ui/motion/dist/components/Motion.vue
    at __node_internal_captureLargerStackTrace2 (https://vitekxpk3c-okve.w-credentialless-staticblitz.com/builtins.e7ffca03.js:101:5253)
    at new NodeError (https://vitekxpk3c-okve.w-credentialless-staticblitz.com/builtins.e7ffca03.js:101:4067)
    at Object.getFileProtocolModuleFormat [as file:] (https://vitekxpk3c-okve.w-credentialless-staticblitz.com/builtins.e7ffca03.js:150:1473)
    at defaultGetFormat (https://vitekxpk3c-okve.w-credentialless-staticblitz.com/builtins.e7ffca03.js:150:1798)
    at defaultLoad (https://vitekxpk3c-okve.w-credentialless-staticblitz.com/builtins.e7ffca03.js:153:1058)
    at nextLoad (https://vitekxpk3c-okve.w-credentialless-staticblitz.com/builtins.e7ffca03.js:154:1851)
    at ESMLoader.load (https://vitekxpk3c-okve.w-credentialless-staticblitz.com/builtins.e7ffca03.js:154:5069)
    at ESMLoader.<anonymous> (https://vitekxpk3c-okve.w-credentialless-staticblitz.com/builtins.e7ffca03.js:154:4122)
    at new ModuleJob (https://vitekxpk3c-okve.w-credentialless-staticblitz.com/builtins.e7ffca03.js:155:867)
    at #o (https://vitekxpk3c-okve.w-credentialless-staticblitz.com/builtins.e7ffca03.js:154:4043)
    at ESMLoader.getModuleJob (https://vitekxpk3c-okve.w-credentialless-staticblitz.com/builtins.e7ffca03.js:154:3901)
    at async https://vitekxpk3c-okve.w-credentialless-staticblitz.com/builtins.e7ffca03.js:155:1066
[Motion component](https://github.com/oku-ui/motion/blob/main/packages/vue/src/components/Motion.vue)
It seems to related to compatibility of @oku-ui/motion with Vitepress, however it just Vue components which should be correctly recognized by Vitepress build.
```

### Expected behavior

The .vue extension should be recognized in any build mode or more describable error message should be printed in case of another issue reason.

### System Info

```Text
System:
    OS: macOS 14.4.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 32.50 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Yarn: 1.22.22 - /usr/local/bin/yarn
    npm: 10.5.0 - ~/Library/Application Support/Herd/config/nvm/versions/node/v20.12.2/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 124.0.6367.209
    Safari: 17.4.1
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Try adding `'@oku-ui/motion'` to `vite.ssr.noExternal`

**Comment by slavarazum** [comment]
Thank you for the prompt response. Now it is being built successfully.
It’s just not entirely clear how it related to .vue extension or why other dependencies like [@headlessui/vue](https://stackblitz.com/edit/vite-kxpk3c?file=docs%2F.vitepress%2Ftheme%2FSwitch.vue) don't affect SSR.

**Comment by brc-dd** [comment]
It’s not compiled. headlessui ships compiled components as .js files which don’t need to be compiled again and can be consumed by rollup as is.
