### ISSUE TITLE
escapeHtml breaks my build after vitepress@1.2.2 update

### ISSUE THREAD

**Issue by trincadev** [vuejs/vitepress#3916]
### Describe the bug

Hi there, great work.
I got a bug after `vitepress@1.2.2` update:

```
> pnpm i --frozen-lockfile && vitepress build docs

Lockfile is up to date, resolution step is skipped
Already up to date
Done in 1.3s

  vitepress v1.2.2

✓ building client + server bundles...
✖ rendering pages...
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/MYUSERNAME/workspace/cv-static-pages/docs/.vitepress/.temp/Content.CR-jMDP7.js' imported from /Users/MYUSERNAME/workspace/cv-static-pages/docs/.vitepress/.temp/IndexBlogPostsComponent.NZLQHpLQ.js
    at finalizeResolution (node:internal/modules/esm/resolve:265:11)
    at moduleResolve (node:internal/modules/esm/resolve:933:10)
    at defaultResolve (node:internal/modules/esm/resolve:1157:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:390:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:359:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:234:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:87:39)
    at link (node:internal/modules/esm/module_job:86:36) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///Users/MYUSERNAME/workspace/cv-static-pages/docs/.vitepress/.temp/Content.CR-jMDP7.js'
}
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/MYUSERNAME/workspace/cv-static-pages/docs/.vitepress/.temp/Content.CR-jMDP7.js' imported from /Users/MYUSERNAME/workspace/cv-static-pages/docs/.vitepress/.temp/IndexBlogPostsComponent.NZLQHpLQ.js
    at finalizeResolution (node:internal/modules/esm/resolve:265:11)
    at moduleResolve (node:internal/modules/esm/resolve:933:10)
    at defaultResolve (node:internal/modules/esm/resolve:1157:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:390:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:359:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:234:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:87:39)
    at link (node:internal/modules/esm/module_job:86:36) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///Users/MYUSERNAME/workspace/cv-static-pages/docs/.vitepress/.temp/Content.CR-jMDP7.js'
}
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/MYUSERNAME/workspace/cv-static-pages/docs/.vitepress/.temp/Content.CR-jMDP7.js' imported from /Users/MYUSERNAME/workspace/cv-static-pages/docs/.vitepress/.temp/SelectorTagList.DzaOtHmS.js
    at finalizeResolution (node:internal/modules/esm/resolve:265:11)
    at moduleResolve (node:internal/modules/esm/resolve:933:10)
    at defaultResolve (node:internal/modules/esm/resolve:1157:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:390:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:359:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:234:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:87:39)
    at link (node:internal/modules/esm/module_job:86:36) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///Users/MYUSERNAME/workspace/cv-static-pages/docs/.vitepress/.temp/Content.CR-jMDP7.js'
}
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/MYUSERNAME/workspace/cv-static-pages/docs/.vitepress/.temp/leaflet.l0sNRNKZ.js' imported from /Users/MYUSERNAME/workspace/cv-static-pages/docs/.vitepress/.temp/SimpleGallery.1E6T5ZyO.js
    at finalizeResolution (node:internal/modules/esm/resolve:265:11)
    at moduleResolve (node:internal/modules/esm/resolve:933:10)
    at defaultResolve (node:internal/modules/esm/resolve:1157:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:390:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:359:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:234:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:87:39)
    at link (node:internal/modules/esm/module_job:86:36) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///Users/MYUSERNAME/workspace/cv-static-pages/docs/.vitepress/.temp/leaflet.l0sNRNKZ.js'
}
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/MYUSERNAME/workspace/cv-static-pages/docs/.vitepress/.temp/leaflet.l0sNRNKZ.js' imported from /Users/MYUSERNAME/workspace/cv-static-pages/docs/.vitepress/.temp/SimpleGallery.1E6T5ZyO.js
    at finalizeResolution (node:internal/modules/esm/resolve:265:11)
    at moduleResolve (node:internal/modules/esm/resolve:933:10)
    at defaultResolve (node:internal/modules/esm/resolve:1157:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:390:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:359:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:234:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:87:39)
    at link (node:internal/modules/esm/module_job:86:36) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///Users/MYUSERNAME/workspace/cv-static-pages/docs/.vitepress/.temp/leaflet.l0sNRNKZ.js'
}
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/MYUSERNAME/workspace/cv-static-pages/docs/.vitepress/.temp/leaflet.l0sNRNKZ.js' imported from /Users/MYUSERNAME/workspace/cv-static-pages/docs/.vitepress/.temp/SimpleGallery.1E6T5ZyO.js
    at finalizeResolution (node:internal/modules/esm/resolve:265:11)
    at moduleResolve (node:internal/modules/esm/resolve:933:10)
    at defaultResolve (node:internal/modules/esm/resolve:1157:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:390:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:359:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:234:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:87:39)
    at link (node:internal/modules/esm/module_job:86:36) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///Users/MYUSERNAME/workspace/cv-static-pages/docs/.vitepress/.temp/leaflet.l0sNRNKZ.js'
}
build error:
Cannot read properties of undefined (reading 'replace')
TypeError: Cannot read properties of undefined (reading 'replace')
    at escapeHtml$1 (file:///Users/MYUSERNAME/workspace/cv-static-pages/node_modules/.pnpm/vitepress@1.2.2_@algolia+client-search@4.23.3_postcss@8.4.38_search-insights@2.14.0/node_modules/vitepress/dist/node/serve-BwR5EPUJ.js:19945:14)
    at file:///Users/MYUSERNAME/workspace/cv-static-pages/node_modules/.pnpm/vitepress@1.2.2_@algolia+client-search@4.23.3_postcss@8.4.38_search-insights@2.14.0/node_modules/vitepress/dist/node/serve-BwR5EPUJ.js:46689:24
    at Array.map (<anonymous>)
    at renderAttrs (file:///Users/MYUSERNAME/workspace/cv-static-pages/node_modules/.pnpm/vitepress@1.2.2_@algolia+client-search@4.23.3_postcss@8.4.38_search-insights@2.14.0/node_modules/vitepress/dist/node/serve-BwR5EPUJ.js:46687:29)
    at file:///Users/MYUSERNAME/workspace/cv-static-pages/node_modules/.pnpm/vitepress@1.2.2_@algolia+client-search@4.23.3_postcss@8.4.38_search-insights@2.14.0/node_modules/vitepress/dist/node/serve-BwR5EPUJ.js:46671:33
    at Array.map (<anonymous>)
    at renderHead (file:///Users/MYUSERNAME/workspace/cv-static-pages/node_modules/.pnpm/vitepress@1.2.2_@algolia+client-search@4.23.3_postcss@8.4.38_search-insights@2.14.0/node_modules/vitepress/dist/node/serve-BwR5EPUJ.js:46670:10)
    at renderPage (file:///Users/MYUSERNAME/workspace/cv-static-pages/node_modules/.pnpm/vitepress@1.2.2_@algolia+client-search@4.23.3_postcss@8.4.38_search-insights@2.14.0/node_modules/vitepress/dist/node/serve-BwR5EPUJ.js:46625:13)
    at async pMap.concurrency (file:///Users/MYUSERNAME/workspace/cv-static-pages/node_modules/.pnpm/vitepress@1.2.2_@algolia+client-search@4.23.3_postcss@8.4.38_search-insights@2.14.0/node_modules/vitepress/dist/node/serve-BwR5EPUJ.js:46770:11)
    at async file:///Users/MYUSERNAME/workspace/cv-static-pages/node_modules/.pnpm/vitepress@1.2.2_@algolia+client-search@4.23.3_postcss@8.4.38_search-insights@2.14.0/node_modules/vitepress/dist/node/serve-BwR5EPUJ.js:2618:20
 ELIFECYCLE  Command failed with exit code 1.
```

I managed to fix my issue wrapping the `escapeHtml` function in a try-catch like this:
```
export function escapeHtml(str: string): string {
  try {
    return str
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/&(?![\w#]+;)/g, '&amp;')
  } catch (e) {
    console.error("escapeHtml => input str: ", typeof str, str)
    console.error("escapeHtml => e: ", typeof e, e)
    return ""
  }
}
```

Of course the argument input for this function should NEVER be undefined, but in my case I cannot understand what's broke my build. Also, the dist output is fine for me with this workaround.

### Reproduction

I can reproduce this bug only in my local setup and I can't share my repository.

### Expected behavior

a correct build as in vitepress@1.2.1 and earlier.

### System Info

```Text
System:
    OS: macOS 14.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 6.21 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.1 - ~/.nvm/versions/node/v20/bin/node
    npm: 10.8.0 - ~/.nvm/versions/node/v20/bin/npm
    pnpm: 9.1.2 - ~/.nvm/versions/node/v20/bin/pnpm
  Browsers:
    Chrome: 125.0.6422.77
    Safari: 17.5
  npmPackages:
    vitepress: 1.2.2 => 1.2.2 
```

### Additional context

My package.json:

```
{
  "name": "website",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "docs:dev": "vitepress dev docs",
    "docs:build-no-custom-html": "pnpm i --frozen-lockfile && vitepress build docs",
    "docs:build": "pnpm i --frozen-lockfile && vitepress build docs && cp ./presentations/*.html ./docs/.vitepress/dist/",
    "docs:serve": "vitepress serve docs",
    "docs:preview": "vitepress preview docs --port 5173",
    "docs:test": "pnpm playwright test --workers 1"
  },
  "keywords": [],
  "type": "module",
  "dependencies": {
    "@geoman-io/leaflet-geoman-free": "^2.17.0",
    "@vue-leaflet/vue-leaflet": "^0.10.1",
    "core-js": "^3.37.1",
    "feed": "^4.2.2",
    "leaflet": "^1.9.4",
    "leaflet.markercluster": "^1.5.3",
    "photoswipe": "^5.4.3",
    "pinia": "^2.1.7",
    "vitepress": "1.2.2",
    "vue": "^3.4.27"
  },
  "devDependencies": {
    "@playwright/test": "^1.44.1",
    "@tsconfig/recommended": "^1.0.6",
    "@types/geojson": "^7946.0.14",
    "@types/leaflet": "^1.9.12",
    "@types/leaflet.markercluster": "^1.5.4",
    "dotenv": "^16.4.5",
    "playwright": "^1.44.1",
    "playwright-merge-html-reports": "^0.2.8"
  },
  "pnpm": {
    "overrides": {},
    "overrides-example": {
      "postcss@ <8.4.31": "^8.4.31"
    }
  }
}
```

My vite.config.ts
```
import { defineConfig, Plugin } from 'vite'
import _fs from 'fs'
import path from 'path'

const fs = _fs.promises

export default defineConfig({
  clearScreen: false,
  plugins: [
    ...(process.env.NETLIFY ? [] : [copyPiniaPlugin()]),
  ],
  optimizeDeps: {
    exclude: ['vue-demi', '@vueuse/shared', '@vueuse/core', 'pinia'],
  },
})

function copyPiniaPlugin(): Plugin {
  return {
    name: 'copy-pinia',
    async generateBundle() {
      const filePath = path.resolve(__dirname, '../pinia/dist/pinia.mjs')

      // throws if file doesn't exist
      await fs.access(filePath)

      this.emitFile({
        type: 'asset',
        fileName: 'pinia.mjs',
        source: await fs.readFile(filePath, 'utf8'),
      })
    },
  }
}
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Can you try removing head from your vitepress config and building once? Or do you have head specified via frontmatter. One of those must be breaking. If you can share some demo code which breaks it'll be easier to fix the root cause.

**Comment by trincadev** [comment]
Ok, thank you for your quick reply.
I found the issue: since I use vitepress for a multi-language blog, I also translate the `head`. My translation in this case was from an object with a missing key that gave me an undefined property like this:

```
export const META_INFO = {
    en: {
        META_TITLE: 'website title',
        META_DESCRIPTION: 'website description'
    },
    it: {
        META_TITLE: 'titolo del sito web',
        META_DESCRIPTION: 'descrizione del sito web'
    }
}

export const enConfig: LocaleSpecificConfig<DefaultTheme.Config> = {
head: [
   ['meta', { property: 'twitter:url', content: META_INFO_LOCALIZED["META_URL"] }], 
]
```

Obviously I caused this fault, but I didn't find anything about the cause in the documentation (I only searched for "escape" or similar because of the commit message). Can we add a note in [head section](https://vitepress.dev/reference/site-config#head) about the cause for this build failure, or emit more informations with the log exception?
