### ISSUE TITLE
Fails to build with yarn v4 PnP, rollup error

### ISSUE THREAD

**Issue by l3d00m** [vuejs/vitepress#3919]
### Describe the bug

Installing a fresh vitepress quickstart and using yarn with PnP installs. `yarn run docs:build` fails with:

```
build error:
[vite]: Rollup failed to resolve import "vue/server-renderer" from "/home/thomas/projects/testpnp/README.md".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
Error: [vite]: Rollup failed to resolve import "vue/server-renderer" from "/home/thomas/projects/testpnp/README.md".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file:///home/thomas/projects/testpnp/.yarn/__virtual__/vite-virtual-4c2197c7d1/3/.yarn/berry/cache/vite-npm-5.2.11-fa468e8533-10c0.zip/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:67612:27)
    at onRollupWarning (file:///home/thomas/projects/testpnp/.yarn/__virtual__/vite-virtual-4c2197c7d1/3/.yarn/berry/cache/vite-npm-5.2.11-fa468e8533-10c0.zip/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:67640:9)
    at onwarn (file:///home/thomas/projects/testpnp/.yarn/__virtual__/vite-virtual-4c2197c7d1/3/.yarn/berry/cache/vite-npm-5.2.11-fa468e8533-10c0.zip/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:67356:13)
    at file:///home/thomas/.yarn/berry/cache/rollup-npm-4.18.0-9eadb97a09-10c0.zip/node_modules/rollup/dist/es/shared/node-entry.js:18514:13
    at Object.logger [as onLog] (file:///home/thomas/.yarn/berry/cache/rollup-npm-4.18.0-9eadb97a09-10c0.zip/node_modules/rollup/dist/es/shared/node-entry.js:20162:9)
    at ModuleLoader.handleInvalidResolvedId (file:///home/thomas/.yarn/berry/cache/rollup-npm-4.18.0-9eadb97a09-10c0.zip/node_modules/rollup/dist/es/shared/node-entry.js:19104:26)
    at file:///home/thomas/.yarn/berry/cache/rollup-npm-4.18.0-9eadb97a09-10c0.zip/node_modules/rollup/dist/es/shared/node-entry.js:19062:26
```

### Reproduction

Use this repo: https://github.com/l3d00m/vitepress-yarn-repro and run `corepack enable && yarn install && yarn run docs:build`

Alternatively: 

1. Create New folder
1. `yarn set version stable`
2. `yarn add -D vitepress` 
3. `yarn vitepress init` (use default settings, just press enter)
4. `yarn run docs:build` fails

### Expected behavior

Should not fail, should work out of the box

### System Info

```Text
System:
    OS: Linux 6.9 Manjaro Linux
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
    Memory: 6.45 GB / 15.53 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 20.13.1 - ~/.nvm/versions/node/v20.13.1/bin/node
    Yarn: 4.2.2 - ~/.nvm/versions/node/v20.13.1/bin/yarn
    npm: 10.5.2 - ~/.nvm/versions/node/v20.13.1/bin/npm
  Browsers:
    Chromium: 124.0.6367.155
```

### Additional context

This is similar to #3035, but here it always fails, also with a fresh repo.

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
On yarn pnp you need to manually install vue.

**Comment by l3d00m** [comment]
This fixes it, thank you. Would it be possible to document that somewhere?

**Comment by brc-dd** [comment]
Yeah.

**Comment by l3d00m** [comment]
thanks for the quick fix!
