### ISSUE TITLE
[vitepress] Internal server error: At least one <template> or <script> is required in a single file component.

### ISSUE THREAD

**Issue by wspromise** [vuejs/vitepress#3986]
### Describe the bug

20:36:36 [vitepress] Internal server error: At least one <template> or <script> is required in a single file component.
  Plugin: vite:vue
  File: C:/Users/wingwang/Desktop/Oceanpayment-ui/node_modules/.pnpm/vitepress@1.2.2_@algolia+client-search@4.23.3_@types+node@20.14.5_async-validator@4.2.5_axios_v2np3kzxvdru2wjixovc3nnoya/node_modules/vitepress/dist/client/theme-default/components/VPTeamMembers.vue
      at Object.parse$2 [as parse] (C:\Users\wingwang\Desktop\Oceanpayment-ui\node_modules\.pnpm\@vue+compiler-sfc@3.3.4\node_modules\@vue\compiler-sfc\dist\compiler-sfc.cjs.js:1275:7)
      at createDescriptor (file:///C:/Users/wingwang/Desktop/Oceanpayment-ui/node_modules/.pnpm/@vitejs+plugin-vue@4.3.1_vite@5.2.12_@types+node@20.14.5_less@4.2.0_sass@1.77.4__vue@3.3.4/node_modules/@vitejs/plugin-vue/dist/index.mjs:70:43)
      at transformMain (file:///C:/Users/wingwang/Desktop/Oceanpayment-ui/node_modules/.pnpm/@vitejs+plugin-vue@4.3.1_vite@5.2.12_@types+node@20.14.5_less@4.2.0_sass@1.77.4__vue@3.3.4/node_modules/@vitejs/plugin-vue/dist/index.mjs:2261:34)
      at TransformContext.transform (file:///C:/Users/wingwang/Desktop/Oceanpayment-ui/node_modules/.pnpm/@vitejs+plugin-vue@4.3.1_vite@5.2.12_@types+node@20.14.5_less@4.2.0_sass@1.77.4__vue@3.3.4/node_modules/@vitejs/plugin-vue/dist/index.mjs:2782:16)
      at Object.transform (file:///C:/Users/wingwang/Desktop/Oceanpayment-ui/node_modules/.pnpm/vite@5.2.12_@types+node@20.14.5_less@4.2.0_sass@1.77.4/node_modules/vite/dist/node/chunks/dep-BKbDVx1T.js:52312:62)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async loadAndTransform (file:///C:/Users/wingwang/Desktop/Oceanpayment-ui/node_modules/.pnpm/vite@5.2.12_@types+node@20.14.5_less@4.2.0_sass@1.77.4/node_modules/vite/dist/node/chunks/dep-BKbDVx1T.js:55067:29)

### Reproduction

https://stackblitz.com/edit/vite-nnfopi?file=docs%2F.vitepress%2Fconfig.ts

### Expected behavior

normal

### System Info

```Text
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 9.1.3 - /usr/local/bin/pnpm
  npmPackages:
    vitepress: 1.2.2
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by wspromise** [comment]
<script setup lang="ts">
import type { DefaultTheme } from 'vitepress/theme'
import { computed } from 'vue'
import VPTeamMembersItem from './VPTeamMembersItem.vue'

interface Props {
  size?: 'small' | 'medium'
  members: DefaultTheme.TeamMember[]
}

const props = withDefaults(defineProps<Props>(), {
  size: 'medium'
})

const classes = computed(() => [props.size, `count-${props.members.length}`])
</script>

<template>
  <div class="VPTeamMembers" :class="classes">
    <div class="container">
      <div v-for="member in members" :key="member.name" class="item">
        <VPTeamMembersItem :size="size" :member="member" />
      </div>
    </div>
  </div>
</template>

<style scoped>
.VPTeamMembers.small .container {
  grid-template-columns: repeat(auto-fit, minmax(224px, 1fr));
}

.VPTeamMembers.small.count-1 .container {
  max-width: 276px;
}
.VPTeamMembers.small.count-2 .container {
  max-width: calc(276px * 2 + 24px);
}
.VPTeamMembers.small.count-3 .container {
  max-width: calc(276px * 3 + 24px * 2);
}

.VPTeamMembers.medium .container {
  grid-template-columns: repeat(auto-fit, minmax(256px, 1fr));
}

@media (min-width: 375px) {
  .VPTeamMembers.medium .container {
    grid-template-columns: repeat(auto-fit, minmax(288px, 1fr));
  }
}

.VPTeamMembers.medium.count-1 .container {
  max-width: 368px;
}
.VPTeamMembers.medium.count-2 .container {
  max-width: calc(368px * 2 + 24px);
}

.container {
  display: grid;
  gap: 24px;
  margin: 0 auto;
  max-width: 1152px;
}
</style>

**Comment by Zhengqbbb** [comment]
Emmm... What error ?
Can u provide a mini reproduction: https://vitepress.new/
Or screenshot

**Comment by wspromise** [comment]
![企业微信截图_1719364418769](https://github.com/vuejs/vitepress/assets/43053038/3941a4f3-f606-49b5-ad32-0487e924691f)

**Comment by wspromise** [comment]
> Emmm... What error ? Can u provide a mini reproduction: https://vitepress.new/ Or screenshot

https://stackblitz.com/edit/vite-qkyrnr?file=docs%2F.vitepress%2Fconfig.ts

**Comment by brc-dd** [comment]
You're manually adding vue plugin. VitePress already adds that for you. This is duplicating the logic. Pass options using `vue` instead of adding vue plugin manually - https://stackblitz.com/edit/vite-h7uxrj?file=docs/.vitepress/config.ts,docs/index.md
