### ISSUE TITLE
[vite:vue] [plugin vite:vue]  Element is missing end tag.

### ISSUE THREAD

**Issue by linwumingshi** [vuejs/vitepress#4018]
### Describe the bug

"vitepress": "^1.2.3"

vitepress dev is normal, but vitepress build reports an error, SyntaxError: Element is missing end tag. 

detail:  
```
build error:
[vite:vue] [plugin vite:vue] docs/en/guide/javadoc.md (116:219): Element is missing end tag.
file: /home/runner/work/vitepress/vitepress/docs/en/guide/javadoc.md:116:219
[vite:vue] [plugin vite:vue] docs/en/guide/javadoc.md (116:219): Element is missing end tag.
file: /home/runner/work/vitepress/vitepress/docs/en/guide/javadoc.md:116:219
SyntaxError: Element is missing end tag.
    at createCompilerError (/home/runner/work/vitepress/vitepress/node_modules/.pnpm/@vue+compiler-core@3.4.31/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:1324:17)
    at emitError (/home/runner/work/vitepress/vitepress/node_modules/.pnpm/@vue+compiler-core@3.4.31/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:[27](https://github.com/linwumingshi/vitepress/actions/runs/9779010066/job/26997171278#step:8:28)78:5)
    at Object.onclosetag (/home/runner/work/vitepress/vitepress/node_modules/.pnpm/@vue+compiler-core@3.4.31/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:2175:13)
    at Tokenizer.stateInClosingTagName (/home/runner/work/vitepress/vitepress/node_modules/.pnpm/@vue+compiler-core@3.4.31/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:749:16)
    at Tokenizer.parse (/home/runner/work/vitepress/vitepress/node_modules/.pnpm/@vue+compiler-core@3.4.31/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:1107:16)
    at Object.baseParse (/home/runner/work/vitepress/vitepress/node_modules/.pnpm/@vue+compiler-core@3.4.31/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:[28](https://github.com/linwumingshi/vitepress/actions/runs/9779010066/job/26997171278#step:8:29)10:13)
    at Object.parse (/home/runner/work/vitepress/vitepress/node_modules/.pnpm/@vue+compiler-dom@3.4.31/node_modules/@vue/compiler-dom/dist/compiler-dom.cjs.prod.js:636:23)
    at Object.parse$2 [as parse] (/home/runner/work/vitepress/vitepress/node_modules/.pnpm/@vue+compiler-sfc@3.4.[31](https://github.com/linwumingshi/vitepress/actions/runs/9779010066/job/26997171278#step:8:32)/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:1850:24)
    at createDescriptor (file:///home/runner/work/vitepress/vitepress/node_modules/.pnpm/@vitejs+plugin-vue@5.0.5_vite@5.3.2_@types+node@20.14.9_sass@1.77.6__vue@3.4.31/node_modules/@vitejs/plugin-vue/dist/index.mjs:64:43)
    at transformMain (file:///home/runner/work/vitepress/vitepress/node_modules/.pnpm/@vitejs+plugin-vue@5.0.5_vite@5.3.2_@types+node@20.14.9_sass@1.77.6__vue@3.4.31/node_modules/@vitejs/plugin-vue/dist/index.mjs:2376:34)
 ELIFECYCLE  Command failed with exit code 1.
```

https://github.com/linwumingshi/vitepress/actions/runs/9779010066/job/26997171278

### Reproduction

vitepress build

### Expected behavior

build normally

### System Info

```Text
System:
    OS: Windows 11 10.0.22631
    CPU: (18) x64 Intel(R) Core(TM) Ultra 5 125H
    Memory: 16.52 GB / 31.61 GB
  Binaries:
    Node: 20.15.0 - D:\Program Files\nodejs\node.EXE
    npm: 10.7.0 - D:\Program Files\nodejs\npm.CMD
    pnpm: 9.4.0 - D:\Program Files\nodejs\pnpm.CMD
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
In this line it should be ``` `Result<String>` ``` (escaped in backticks, this is currently wrongfully treated as element. You can also escape it - `Result\<String>`)

https://github.com/linwumingshi/vitepress/blob/56bc1ddd75aff153d951d7bd749acfe46676e709/docs/en/guide/javadoc.md?plain=1#L73
