### ISSUE TITLE
ReferenceError: Cannot access 'B' before initialization

### ISSUE THREAD

**Issue by ytattn009** [vuejs/vitepress#4077]
### Describe the bug

项目打包部署后导航菜单不可用,控制台报错 framework.D6fyXT9h.js:13  Uncaught ReferenceError: Cannot access 'B' before initialization
    at Qr (framework.D6fyXT9h.js:13:5534)
    at theme.C-4cHeO8.js:1:460

### Reproduction

项目打包部署后导航菜单不可用,控制台报错 framework.D6fyXT9h.js:13  Uncaught ReferenceError: Cannot access 'B' before initialization
    at Qr (framework.D6fyXT9h.js:13:5534)
    at theme.C-4cHeO8.js:1:460

### Expected behavior

项目打包部署后导航菜单不可用,控制台报错 framework.D6fyXT9h.js:13  Uncaught ReferenceError: Cannot access 'B' before initialization
    at Qr (framework.D6fyXT9h.js:13:5534)
    at theme.C-4cHeO8.js:1:460

### System Info

```Text
window11,
npm:8.19.4,
{
 "markdown-it-mathjax3": "^4.3.2",
 "markdown-to-text": "^0.1.1",
 "vitepress": "^1.3.1",
 "vitepress-markdown-timeline": "^1.2.1"
}
MS Edge
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Please provide a minimal reproducible example using https://vitepress.new or a github repository. There is a likely a circular reference.

**Comment by ytattn009** [comment]
> Please provide a minimal reproducible example using https://vitepress.new or a github repository. There is a likely a circular reference.

you can start a new project 

1. npm i vitepress
2. npm vitepress init
3. open config.mts, add nav items. 
nav: [
      { text: 'Home', link: '/' },
      {
        text: 'Examples',
        items: [
          {
            text: 'Examples`', link: '/'
          }]
      }
    ],
5. npm run docs:build 
6. npm run docs:preview 


1. npm i vitepress
2. npm vitepress init
3. open config.mts, add nav items. 
nav: [
      { text: 'Home', link: '/' },
      {
        text: 'Examples',
        items: [
          {
            text: 'Examples`', link: '/'
          }]
      }
    ],
5. npm run docs:build 
6. npm run docs:preview

**Comment by ytattn009** [comment]
![Uploading 2024-07-26 152104.png…]()

**Comment by ytattn009** [comment]
<img width="400" alt="2024-07-26 152104" src="https://github.com/user-attachments/assets/42ac7ba7-9ae8-4ad5-ae34-878041b9095a">

**Comment by brc-dd** [comment]
There isn't any such error with the steps you mentioned. Please create a repo with that content and share a link here.
