### ISSUE TITLE
The text in `{{text}}` in single line code is treated as a JS expression

### ISSUE THREAD

**Issue by SoClear** [vuejs/vitepress#4088]
### Describe the bug

I want to display `docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' 容器名或容器ID` in single line text

Just like below

| 需求              | 命令                                                                                      |
|-----------------|-----------------------------------------------------------------------------------------|
| 查看正在运行的容器       | `docker ps`                                                                             |
| 查看所有容器          | `docker ps -a`                                                                          |
| 启动容器            | `docker start 容器名或容器ID`                                                                 |
| 停止容器            | `docker stop 容器名或容器ID`                                                                  |
| 重启容器            | `docker restart 容器名或容器ID`                                                               |
| 删除容器            | `docker rm 容器名或容器ID`                                                                    |
| 查看容器IP          | `docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' 容器名或容器ID` |

but I got an error

```txt
[vitepress] Internal server error: Error parsing JavaScript expression: Unexpected token (1:1)
  Plugin: vite:vue
  File: D:/IdeaProjects/soclear.github.io-vitepress/docs/InfoTech/Linux/docker.md:39:67
      at <parse> (:0)
      at createCompilerError (D:\IdeaProjects\soclear.github.io-vitepress\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:1328:21)
      at emitError (D:\IdeaProjects\soclear.github.io-vitepress\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:2812:5)
      at createExp (D:\IdeaProjects\soclear.github.io-vitepress\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:2805:7)
      at oninterpolation (D:\IdeaProjects\soclear.github.io-vitepress\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:2149:16)
      at stateInterpolationClose (D:\IdeaProjects\soclear.github.io-vitepress\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:546:18)
      at parse (D:\IdeaProjects\soclear.github.io-vitepress\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:1047:16)
      at baseParse (D:\IdeaProjects\soclear.github.io-vitepress\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:2851:13)
      at parse (D:\IdeaProjects\soclear.github.io-vitepress\node_modules\@vue\compiler-dom\dist\compiler-dom.cjs.js:706:23)
      at parse$2 (D:\IdeaProjects\soclear.github.io-vitepress\node_modules\@vue\compiler-sfc\dist\compiler-sfc.cjs.js:1850:24)
      at createDescriptor (D:\IdeaProjects\soclear.github.io-vitepress\node_modules\@vitejs\plugin-vue\dist\index.mjs:64:43) (x2)
```

however, multi line code is not treated {{text}} as a JS expression

<pre><code>
```sh
docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' 容器名或容器ID
```
</code></pre>

![image](https://github.com/user-attachments/assets/6bdd9022-e8fb-4252-91c6-9bb93382277e)

### Reproduction

https://stackblitz.com/edit/vite-q7bavu?file=docs%2Fexample.md

### Expected behavior

I expect the text in {{text}} in single line code  is treated  the same as in multi line code. just original text not JS expression

### System Info

```Text
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD Eng Sample: 100-000000534-40_Y
    Memory: 19.52 GB / 31.19 GB
  Binaries:
    bun: 1.1.21 - ~\AppData\Local\Temp\bun-node-70ca2b76c\bun.EXE
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    vitepress: ^1.3.1 => 1.3.1
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
#480
