### ISSUE TITLE
bug: Repeated builds doesn't always succeed every time

### ISSUE THREAD

**Issue by tianheg** [vuejs/vitepress#4130]
### Describe the bug

When building my VitePress site, sometimes will got this error:

```log
✓ building client + server bundles...
✖ rendering pages...
build error:
Cannot read properties of undefined (reading 'some')
TypeError: Cannot read properties of undefined (reading 'some')
    at isChildActive (file:///mnt/disk/MAIN/read/.vitepress/.temp/app.js:2935:28)
    at file:///mnt/disk/MAIN/read/.vitepress/.temp/app.js:2937:43
    at ReactiveEffect.fn (/mnt/disk/MAIN/read/node_modules/@vue/reactivity/dist/reactivity.cjs.prod.js:928:13)
    at ReactiveEffect.run (/mnt/disk/MAIN/read/node_modules/@vue/reactivity/dist/reactivity.cjs.prod.js:162:19)
    at get value [as value] (/mnt/disk/MAIN/read/node_modules/@vue/reactivity/dist/reactivity.cjs.prod.js:940:109)
    at file:///mnt/disk/MAIN/read/.vitepress/.temp/app.js:2942:127
    at renderComponentSubTree (/mnt/disk/MAIN/read/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:442:9)
    at renderComponentVNode (/mnt/disk/MAIN/read/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:386:12)
    at ssrRenderComponent (/mnt/disk/MAIN/read/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:84:10)
    at file:///mnt/disk/MAIN/read/.vitepress/.temp/app.js:2974:19
error: script "build" exited with code 1
```

Didnot know how to figure it out.

### Reproduction

https://github.com/tianheg/read/tree/0a2c670076d0bec5db10500807eb4c31bb5c80da

### Expected behavior

build succeed every time

### System Info

```Text
System:
  OS: Linux 6.10 Arch Linux
  CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  Memory: 13.31 GB / 23.36 GB
  Container: Yes
  Shell: 5.9 - /usr/bin/zsh
Binaries:
  Node: 20.16.0 - ~/.nvm/versions/node/v20.16.0/bin/node
  npm: 10.8.1 - ~/.nvm/versions/node/v20.16.0/bin/npm
  bun: 1.1.22 - /usr/bin/bun
npmPackages:
  vitepress: ^1.3.2 => 1.3.2
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Both of them behave the same way. You don't need base. If this is fixed then the cause of your issue was likely something else.

**Comment by tianheg** [comment]
> If this is fixed then the cause of your issue was likely something else.

Yeah, you're right.

However I no matter how many times I try again, I can't reproduce the previous error.
