### ISSUE TITLE
Verbose Build option to be able to track down errors

### ISSUE THREAD

**Issue by mythz** [vuejs/vitepress#422]
### Is your feature request related to a problem? Please describe.

I'm getting an opaque build error when trying to build a vitepress site which works without issue during dev (i.e. npm run docs:dev) but fails during build.

```bash
$ npm run docs:build
```

```
✓ building client + server bundles...
✖ rendering pages...
build error:
 TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at normalizePropsOptions (C:\src\docs\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:2150:15)
    at createComponentInstance (C:\src\docs\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:4983:23)        
    at renderComponentVNode (C:\src\docs\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:194:22)      
    at Object.ssrRenderComponent (C:\src\docs\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:620:12) 
    at _sfc_ssrRender (C:\src\docs\node_modules\vitepress\dist\client\app\temp\wire-format.md.js:12:24)
    at renderComponentSubTree (C:\src\docs\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:260:13)    
    at renderComponentVNode (C:\src\docs\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:211:16)      
    at renderVNode (C:\src\docs\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:301:22)
    at renderVNodeChildren (C:\src\docs\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:316:9)    
```

I would like extra info during the build, like which page or component failed to renderer so there's some hope in being able to track it down.

### Describe the solution you'd like

Ideally the extra info of what Page and Component failed to render would be included in the error message by default, alternatively being able to run the build with verbose build output, e.g:

```bash
$ vitepress build docs --verbose
```

### Describe alternatives you've considered

Couldn't find a way to generate verbose build output, e.g:

```bash
$ vitepress build docs --verbose
$ vitepress build docs -v
```

I wasn't able to find what the supported switches for the build command are, it would be nice if the available command options was available in the standard help options, e.g:

```bash
$ vitepress build -h
$ vitepress build --help
$ vitepress build ?
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/master/.github/contributing.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by Jinjiang** [comment]
Met the same problem here:
https://github.com/vuejs/v3-migration-guide/pull/19
https://app.netlify.com/sites/eager-kowalevski-41f498/deploys/63671c4b5ebaaa0009f899ed

**Comment by Jinjiang** [comment]
FYI. After debugging, I found the reason was an undefined component name in a markdown file. Now, the undefined component name has been deleted. However, it would be great if we could figure out a better error message for this kind of case.

> Met the same problem here: [vuejs/v3-migration-guide#19](https://github.com/vuejs/v3-migration-guide/pull/19) https://app.netlify.com/sites/eager-kowalevski-41f498/deploys/63671c4b5ebaaa0009f899ed

**Comment by brc-dd** [comment]
These errors are from `@vue/runtime-core`. Not sure if we can fix them at VitePress. 👀

**Comment by brc-dd** [comment]
Few updates on this. Vue no longer throws that error during SSR if the component is not registered. So, the builds will succeed fine, however on viewing the site there will be hydration mismatches. So, from next version, one will be able to run `vitepress build` in slightly more verbose mode by setting `DEBUG` environment variable to true or any value recognized by [the debug package](https://www.npmjs.com/package/debug) (for example, `DEBUG='vitepress:*'` or `DEBUG='vite:*'`).

<img width="1075" alt="image" src="https://github.com/vuejs/vitepress/assets/40380293/01ef80b7-c05d-46ab-9df7-b70ac925aae0">
