### ISSUE TITLE
build error:Blob is not defined

### ISSUE THREAD

**Issue by Ryokutouto** [vuejs/vitepress#539]
### Describe the bug

vitepress v0.22.2
✓ building client + server bundles...
⠙ rendering pages...ReferenceError: Blob is not defined
    at Module.<anonymous> (...\docs\.vitepress\.temp\File_Blob.md.js:6:11)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at ...e\docs\.vitepress\.temp\app.js:1817:12
    at loadPage (...\docs\.vitepress\.temp\app.js:180:18)
    at Object.go (...\docs\.vitepress\.temp\app.js:173:12)
✖ rendering pages...
build error:
 ReferenceError: Blob is not defined
    at Module.<anonymous> (...\docs\.vitepress\.temp\File_Blob.md.js:6:11)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at renderPage (...\node_modules\vitepress\dist\node\serve-cf4b2162.js:40892:26)
    at async Object.build (...\node_modules\vitepress\dist\node\serve-cf4b2162.js:41023:9)

### Reproduction

```
//BlobCreate.vue
<script>
let foo = new Blob(["foo"]);
console.log(foo);
</script>
```
```
//Blob.md
 <script setup>
import BlobCreate from "./components/BlobCreate.vue";
 </script>

 <BlobCreate />
```

### Expected behavior

successfully 

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
    Memory: 6.54 GB / 15.88 GB
  Binaries:
    Node: 16.13.0 - C:\nodejs\node.EXE
    npm: 8.1.4 - C:\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (98.0.1108.50)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    vitepress: ^0.22.2 => 0.22.2
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by Ryokutouto** [comment]
solved
```diff
//BlobCreate.vue
-<script>
+<script setup>
let foo = new Blob(["foo"]);
console.log(foo);
</script>
```
