### ISSUE TITLE
vue.shallowRef is not a function

### ISSUE THREAD

**Issue by peterroe** [vuejs/vitepress#571]
### Describe the bug

vue version: 2.5.16
vitepress version: 0.22.3
node version: 16.13.1

shell error:

```shell
$ vite docs build

✓ building client + server bundles...
✖ rendering pages...
build error:
 TypeError: vue.shallowRef is not a function
    at Module.<anonymous> (D:\VscodeItems\lost-and-found-admin-front\docs\.vitepress\.temp\app.js:80:25)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at renderPage (D:\VscodeItems\lost-and-found-admin-front\node_modules\.pnpm\vitepress@0.22.3_stylus@0.52.4\node_modules\vitepress\dist\node\serve-777539c0.js:40890:25)
    at Object.build (D:\VscodeItems\lost-and-found-admin-front\node_modules\.pnpm\vitepress@0.22.3_stylus@0.52.4\node_modules\vitepress\dist\node\serve-777539c0.js:41039:15)
 ELIFECYCLE  Command failed with exit code 1.
```

### Reproduction

not sure

### Expected behavior

not sure

### System Info

```shell
$ npx envinfo --system --npmPackages vitepress --binaries --browsers

npm ERR! cb.apply is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2022-03-06T05_34_10_677Z-debug.log
Install for [ 'envinfo@latest' ] failed with code 1
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by yl-199807** [comment]
我也遇到了，你解决了吗
`build error:
 TypeError: Vue.defineComponent is not a function
`
