### ISSUE TITLE
[next] Unable to build on Windows

### ISSUE THREAD

**Issue by brc-dd** [vuejs/vitepress#671]
Put anything inside a markdown file and run build:

```sh
npx vitepress@next build .
```

Output:

```txt
vitepress v1.0.0-draft.4
✓ building client + server bundles...
✖ rendering pages...
build error:
 Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at new NodeError (node:internal/errors:372:5)
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:1120:11)
    at defaultResolve (node:internal/modules/esm/resolve:1200:3)
    at ESMLoader.resolve (node:internal/modules/esm/loader:580:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:294:18)
    at ESMLoader.import (node:internal/modules/esm/loader:380:22)
    at importModuleDynamically (node:internal/modules/esm/translators:106:35)
    at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)
    at renderPage (file:///C:/Users/brc-dd/AppData/Local/npm-cache/_npx/fd8208cc6eb378bf/node_modules/vitepress/dist/node/serve-f7c10936.js:39511:45)
    at build (file:///C:/Users/brc-dd/AppData/Local/npm-cache/_npx/fd8208cc6eb378bf/node_modules/vitepress/dist/node/serve-f7c10936.js:39827:15) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}
```

Works fine on dev and should work on *nix. Probably has something to do with the recent ESM refactor. Also, running VitePress logs wrong version on console.

System details:

```txt
OS: Windows 10 10.0.25120
Node: 16.15.0
```

**Comment by kiaking** [comment]
Oh good you're running Windows. Yeah this is bad issue I just notice this like 5 sec ago via Vite doc test.
https://github.com/vitejs/vite/runs/6636747127?check_suite_focus=true

It's showing pretty much the same thing as you posted. On Mac, it works fine and also it shows `vitepress v1.0.0-draft.5` correctly.

Do you think you can dig into this 🤔 Don'T have windows machine and I have no idea what this error is...

**Comment by brc-dd** [comment]
Yeah, I'm looking.

**Comment by kiaking** [comment]
YOU ARE THE BEST

**Comment by brc-dd** [comment]
> also it shows vitepress `v1.0.0-draft.5` correctly.

You are probably running vitepress from the repo, not from registry. Look the logs [here](https://github.com/vitejs/vite/runs/6636747097?check_suite_focus=true#step:11:17). This issue is because you probably built the project "before" updating version in package.json. See the `version` variable in [here](https://cdn.jsdelivr.net/npm/vitepress@1.0.0-draft.5/dist/node/cli.js).

**Comment by kiaking** [comment]
Thanks a bunch!

> You are probably running vitepress from the repo, not from registry...

Oh... yeah you were right. I was testing with Vite docs so I was confident but indeed, I was linking VitePress locally... 🤮 

New release is coming up soon!

And, this is fixed!
