### ISSUE TITLE
'collapsible-sidebar-groups' pages 'Multiple Sidebars' code content is not true

### ISSUE THREAD

**Issue by Whbbit1999** [vuejs/vitepress#722]
### Describe the bug

Yesterday when I tested using vitepress to build my own project, I found that there is a problem if I follow the documentation.

````js
  sidebar: {
       // This sidebar gets displayed when user is
       // under `guide` directory.
       '/guide/': {
         text: 'Guide',
         items: [
           // This shows the `/guide/index.md` page.
           { text: 'Index', link: '/guide/' }, // /guide/index.md
           { text: 'One', link: '/guide/one' }, // /guide/one.md
           { text: 'Two', link: '/guide/two' } // /guide/two.md
         ]
       },
 }
````
The content after '/guide/' needs to be an array, but the document content is written as an object

### Reproduction

``` js
sidebar: {
      "/channel/": {
        text: "视频制作",
        collapsible: true,
        items: [
          { text: "剪辑软件选择", link: "/channel/video/software" },
          { text: "视频教程地址", link: "/channel/video/videos" },
        ],
      },
    },
```

### Expected behavior

I hope the documentation can give some hints

### System Info

```shell
-- browsers 

sidebar.js:23 Uncaught (in promise) TypeError: sidebar is not iterable
    at getFlatSideBarLinks (sidebar.js:23:25)
    at ReactiveEffect.fn (prev-next.js:9:28)
    at ReactiveEffect.run (reactivity.esm-bundler.js:185:25)
    at get value [as value] (reactivity.esm-bundler.js:1144:39)
    at unref (reactivity.esm-bundler.js:1052:29)
    at Object.get (reactivity.esm-bundler.js:1055:37)
    at Proxy._sfc_render (VPDocFooter.vue:17:17)
    at renderComponentRoot (runtime-core.esm-bundler.js:896:44)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5575:57)
    at ReactiveEffect.run (reactivity.esm-bundler.js:185:25)
```
```


### Additional context

_No response_

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Yeah that section of docs have some issues. We will fix that. Thanks.
