### ISSUE TITLE
No language registration for CSS

### ISSUE THREAD

**Issue by Jack-Zhang-1314** [vuejs/vitepress#772]
### Describe the bug

>If the css logo of my css code block is uppercase (CSS) like the following

>\```CSS
>p{}
>\```

* When building it produces an error like this:`[vitepress] No language registration for CSS`

### Reproduction

`pnpm build`-->cause an error,
`pnpm dev`-->and the preview also creates problems

### Expected behavior

Case insensitive on code block identifiers

### System Info

```shell
[vite] Internal server error: No language registration for CSS
  Plugin: vitepress
  File: E:/Project/CSS/blog-css/docs/css布局/grid.md
      at getGrammar (E:\Project\CSS\blog-css\node_modules\.pnpm\shiki@0.10.1\node_modules\shiki\dist\index.js:2175:19)
      at codeToThemedTokens (E:\Project\CSS\blog-css\node_modules\.pnpm\shiki@0.10.1\node_modules\shiki\dist\index.js:2184:30)
      at Object.codeToHtml (E:\Project\CSS\blog-css\node_modules\.pnpm\shiki@0.10.1\node_modules\shiki\dist\index.js:2201:24)
      at Object.highlight (file:///E:/Project/CSS/blog-css/node_modules/.pnpm/vitepress@1.0.0-alpha.1/node_modules/vitepress/dist/node/serve-e8d58be3.js:31999:26)    
      at default_rules.fence (file:///E:/Project/CSS/blog-css/node_modules/.pnpm/vitepress@1.0.0-alpha.1/node_modules/vitepress/dist/node/serve-e8d58be3.js:25746:27) 
      at md.renderer.rules.fence (file:///E:/Project/CSS/blog-css/node_modules/.pnpm/vitepress@1.0.0-alpha.1/node_modules/vitepress/dist/node/serve-e8d58be3.js:32339:16)
      at md.renderer.rules.fence (file:///E:/Project/CSS/blog-css/node_modules/.pnpm/vitepress@1.0.0-alpha.1/node_modules/vitepress/dist/node/serve-e8d58be3.js:32828:21)
      at Object.md.renderer.rules.fence (file:///E:/Project/CSS/blog-css/node_modules/.pnpm/vitepress@1.0.0-alpha.1/node_modules/vitepress/dist/node/serve-e8d58be3.js:32803:12)
      at Renderer$1.render (file:///E:/Project/CSS/blog-css/node_modules/.pnpm/vitepress@1.0.0-alpha.1/node_modules/vitepress/dist/node/serve-e8d58be3.js:26025:38)   
      at MarkdownIt.render (file:///E:/Project/CSS/blog-css/node_modules/.pnpm/vitepress@1.0.0-alpha.1/node_modules/vitepress/dist/node/serve-e8d58be3.js:31950:24)
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
It should be in lowercase always.

**Comment by Jack-Zhang-1314** [comment]
> It should be in lowercase always.

😯，but compatible uppercase will have better support

**Comment by brc-dd** [comment]
But it will be non-standard too.

**Comment by Jack-Zhang-1314** [comment]
Well, then I will provide support myself. Vuepress has no problem in this regard though
