### ISSUE TITLE
Bibtex citing with accented characters 

### ISSUE THREAD

**Issue by qeterme** [vuejs/vitepress#840]
### Describe the bug

While a BibTex fenced code block has accented characters it parses wrong and has an internal error. In Tex (and BibTex) it's a good technique to use this format when you don't set the encoding but want accented characters.

```
14:31:25 [vite] Internal server error: Invalid end tag.
  Plugin: vite:vue
  File: /home/peter/code/work/huspacy/docs/site/guide/citing.md
  7  |  @misc{HuSpaCy:2021,
  8  |    title = {{HuSpaCy: an industrial-strength Hungarian natural language processing toolkit}},
  9  |    booktitle = {{XVIII. Magyar Sz{\'a}m{\'\i}t{\'o}g{\'e}pes Nyelv{\'e}szeti Konferencia}},
     |                                                ^
  10 |    location = {{Szeged}},
      at createCompilerError (/home/peter/code/work/huspacy/docs/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:19:19)
      at emitError (/home/peter/code/work/huspacy/docs/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:1594:29)
      at parseChildren (/home/peter/code/work/huspacy/docs/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:927:25)
      at parseElement (/home/peter/code/work/huspacy/docs/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:1125:22)
      at parseChildren (/home/peter/code/work/huspacy/docs/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:937:28)
      at parseElement (/home/peter/code/work/huspacy/docs/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:1125:22)
      at parseChildren (/home/peter/code/work/huspacy/docs/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:937:28)
      at parseElement (/home/peter/code/work/huspacy/docs/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:1125:22)
      at parseChildren (/home/peter/code/work/huspacy/docs/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:937:28)
      at Object.baseParse (/home/peter/code/work/huspacy/docs/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:852:23)

```

### Reproduction

Fenced code block in BibTex, having this format of accented characters.
For example:
````
```bibtex
@misc{HuSpaCy:2021,
  title = {{HuSpaCy: an industrial-strength Hungarian natural language processing toolkit}},
  booktitle = {{XVIII. Magyar Sz{\'a}m{\'\i}t{\'o}g{\'e}pes Nyelv{\'e}szeti Konferencia}},
  location = {{Szeged}},
  year = {2022},
}
```
````

### Expected behavior

Don' have errors :D

### System Info

```shell
System:
    OS: Linux 5.13 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 902.48 MB / 15.32 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 18.4.0 - /usr/bin/node
    npm: 8.12.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 102.0.5005.115
    Firefox: 101.0.1
  npmPackages:
    vitepress: ^1.0.0-alpha.2 => 1.0.0-alpha.2
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Not reproducible:

![image](https://user-images.githubusercontent.com/40380293/175032566-094fabe7-416f-4926-a07d-d02ea0b82037.png)

**Comment by qeterme** [comment]
Well, I was inattentive. It had a `<\br>` tag before, but vite said the error was in the BibTex block... Thanks for the quick response, my bad
